insert INTO boards (owner_id, title, description, date_posted) VALUES (1, 'Online Learning', 'List of websites that have online courses', '3/7/2018');
insert INTO boards (owner_id, title, description, date_posted) VALUES (1, 'WTFunctions', 'Basically just stackoverflow', '10/18/2019');
insert INTO boards (owner_id, title, description, date_posted) VALUES (1, 'Bootcamp reference guide', 'Cheatsheets to reference when completely lost', '3/7/2018');
insert into boards (owner_id, title, description, date_posted) values (84, ' Organic Chemistry stuff for school', 'Curabitur convallis.', '3/7/2018');
insert into boards (owner_id, title, description, date_posted) values (45, ' Russian Topics', 'Nullam porttitor lacus at turpis.', '1/24/2017');
insert into boards (owner_id, title, description, date_posted) values (50, ' German Homework', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '8/4/2020');
insert into boards (owner_id, title, description, date_posted) values (41, ' Astrophysics Topics', 'Nam nulla.', '8/2/2020');
insert into boards (owner_id, title, description, date_posted) values (6, ' Science stuff for school', 'Integer ac neque.', '7/7/2019');
insert into boards (owner_id, title, description, date_posted) values (18, ' Cognitive Psychology links and articles', 'Vestibulum sed magna at nunc commodo placerat.', '5/19/2016');
insert into boards (owner_id, title, description, date_posted) values (75, ' English - useful material', 'Cras in purus eu magna vulputate luctus.', '3/24/2017');
insert into boards (owner_id, title, description, date_posted) values (4, ' Organic Chemistry undefined', 'Aliquam sit amet diam in magna bibendum imperdiet.', '11/18/2018');
insert into boards (owner_id, title, description, date_posted) values (52, ' Neuroscience stuff for school', 'In hac habitasse platea dictumst.', '1/29/2017');
insert into boards (owner_id, title, description, date_posted) values (57, ' Microeconomics School Work', 'Praesent blandit lacinia erat.', '10/3/2018');
insert into boards (owner_id, title, description, date_posted) values (36, ' Economics stuff for school', 'Vivamus in felis eu sapien cursus vestibulum.', '7/25/2020');
insert into boards (owner_id, title, description, date_posted) values (69, ' German Resources', 'Curabitur in libero ut massa volutpat convallis.', '2/24/2020');
insert into boards (owner_id, title, description, date_posted) values (69, ' Literature stuff for school', 'Sed sagittis.', '12/20/2018');
insert into boards (owner_id, title, description, date_posted) values (46, ' Arabic Links', 'Quisque porta volutpat erat.', '11/23/2016');
insert into boards (owner_id, title, description, date_posted) values (18, ' Quantum Physics Material', 'Praesent id massa id nisl venenatis lacinia.', '10/18/2018');
insert into boards (owner_id, title, description, date_posted) values (54, ' Organic Chemistry undefined', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '9/2/2016');
insert into boards (owner_id, title, description, date_posted) values (93, ' Neuroscience stuff for school', 'Vestibulum rutrum rutrum neque.', '5/16/2017');
insert into boards (owner_id, title, description, date_posted) values (51, ' Spanish Articles', 'Donec vitae nisi.', '11/30/2018');
insert into boards (owner_id, title, description, date_posted) values (13, ' German links and articles', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '10/26/2018');
insert into boards (owner_id, title, description, date_posted) values (88, ' Microeconomics School Work', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '12/10/2017');
insert into boards (owner_id, title, description, date_posted) values (71, ' English Material', 'Vivamus vel nulla eget eros elementum pellentesque.', '1/14/2019');
insert into boards (owner_id, title, description, date_posted) values (68, ' German links and articles', 'Mauris lacinia sapien quis libero.', '7/5/2020');
insert into boards (owner_id, title, description, date_posted) values (5, ' Astrophysics - Freshman Year', 'Aliquam sit amet diam in magna bibendum imperdiet.', '4/26/2017');
insert into boards (owner_id, title, description, date_posted) values (77, ' History - Freshman Year', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '6/8/2019');
insert into boards (owner_id, title, description, date_posted) values (32, ' Microeconomics Journals', 'Integer ac neque.', '5/19/2019');
insert into boards (owner_id, title, description, date_posted) values (28, ' Cognitive Psychology links and articles', 'Mauris lacinia sapien quis libero.', '6/11/2016');
insert into boards (owner_id, title, description, date_posted) values (94, ' Spanish Articles', 'Morbi porttitor lorem id ligula.', '3/16/2020');
insert into boards (owner_id, title, description, date_posted) values (57, ' Language Links', 'Nulla mollis molestie lorem.', '11/20/2018');
insert into boards (owner_id, title, description, date_posted) values (71, ' Literature Stuff', 'Pellentesque at nulla.', '8/7/2016');
insert into boards (owner_id, title, description, date_posted) values (54, ' Russian Links', 'Aliquam non mauris.', '11/25/2016');
insert into boards (owner_id, title, description, date_posted) values (38, ' Linguistics Articles', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '10/2/2019');
insert into boards (owner_id, title, description, date_posted) values (5, ' German links and articles', 'Etiam pretium iaculis justo.', '5/3/2019');
insert into boards (owner_id, title, description, date_posted) values (79, ' Economics - Freshman Year', 'Donec quis orci eget orci vehicula condimentum.', '5/15/2016');
insert into boards (owner_id, title, description, date_posted) values (50, ' Philosophy links and articles', 'Vivamus tortor.', '3/12/2017');
insert into boards (owner_id, title, description, date_posted) values (65, ' Geography College Work', 'Integer tincidunt ante vel ipsum.', '7/4/2019');
insert into boards (owner_id, title, description, date_posted) values (34, ' Philosophy stuff for school', 'Nullam molestie nibh in lectus.', '1/12/2019');
insert into boards (owner_id, title, description, date_posted) values (84, ' Classics School Work', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '7/22/2020');
insert into boards (owner_id, title, description, date_posted) values (42, ' Microeconomics School Work', 'Aliquam erat volutpat.', '11/26/2019');
insert into boards (owner_id, title, description, date_posted) values (67, ' Cognitive Psychology links and articles', 'Praesent lectus.', '8/31/2018');
insert into boards (owner_id, title, description, date_posted) values (48, ' Literature Links', 'Etiam vel augue.', '4/26/2020');
insert into boards (owner_id, title, description, date_posted) values (70, ' Microbiology - useful material', 'Duis aliquam convallis nunc.', '4/19/2019');
insert into boards (owner_id, title, description, date_posted) values (62, ' Cognitive Psychology links and articles', 'In hac habitasse platea dictumst.', '9/25/2016');
insert into boards (owner_id, title, description, date_posted) values (92, ' Ancient History - useful material', 'Curabitur at ipsum ac tellus semper interdum.', '8/22/2018');
insert into boards (owner_id, title, description, date_posted) values (1, ' Geology Articles', 'Nulla tellus.', '11/23/2019');
insert into boards (owner_id, title, description, date_posted) values (59, ' Cognitive Psychology links and articles', 'Praesent id massa id nisl venenatis lacinia.', '7/29/2020');
insert into boards (owner_id, title, description, date_posted) values (4, ' Ancient History - useful material', 'Nulla ac enim.', '12/11/2019');
insert into boards (owner_id, title, description, date_posted) values (90, ' Astrophysics Topics', 'Morbi non quam nec dui luctus rutrum.', '9/24/2017');
insert into boards (owner_id, title, description, date_posted) values (39, ' Microbiology - useful material', 'Pellentesque at nulla.', '2/24/2018');
insert into boards (owner_id, title, description, date_posted) values (2, ' Anthropology Links', 'Nulla tellus.', '9/1/2018');
insert into boards (owner_id, title, description, date_posted) values (76, ' Inorganic Chemistry Journals', 'In hac habitasse platea dictumst.', '11/26/2016');
insert into boards (owner_id, title, description, date_posted) values (27, ' Microeconomics undefined', 'Etiam vel augue.', '7/25/2017');
insert into boards (owner_id, title, description, date_posted) values (20, ' Classics Resources', 'Proin eu mi.', '5/18/2018');
insert into boards (owner_id, title, description, date_posted) values (91, ' Geology - Freshman Year', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '9/30/2018');
insert into boards (owner_id, title, description, date_posted) values (71, ' Organic Chemistry Homework', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '7/7/2019');
insert into boards (owner_id, title, description, date_posted) values (36, ' Inorganic Chemistry Journals', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '8/3/2018');
insert into boards (owner_id, title, description, date_posted) values (47, ' Organic Chemistry Homework', 'Curabitur convallis.', '7/12/2017');
insert into boards (owner_id, title, description, date_posted) values (97, ' Classics Resources', 'Donec vitae nisi.', '1/23/2020');
insert into boards (owner_id, title, description, date_posted) values (84, ' Linguistics Articles', 'Nunc nisl.', '4/3/2018');
insert into boards (owner_id, title, description, date_posted) values (54, ' Linguistics undefined', 'Nulla tempus.', '11/16/2016');
insert into boards (owner_id, title, description, date_posted) values (66, ' Organic Chemistry undefined', 'Donec posuere metus vitae ipsum.', '4/29/2018');
insert into boards (owner_id, title, description, date_posted) values (70, ' Anthropology - useful material', 'Vestibulum ac est lacinia nisi venenatis tristique.', '6/8/2020');
insert into boards (owner_id, title, description, date_posted) values (84, ' English Material', 'Nulla tellus.', '3/8/2018');
insert into boards (owner_id, title, description, date_posted) values (76, ' German Homework', 'Integer ac neque.', '3/20/2019');
insert into boards (owner_id, title, description, date_posted) values (72, ' English undefined', 'Cras non velit nec nisi vulputate nonummy.', '5/20/2019');
insert into boards (owner_id, title, description, date_posted) values (29, ' Anthropology - useful material', 'Praesent blandit.', '5/12/2020');
insert into boards (owner_id, title, description, date_posted) values (64, ' Physics Articles', 'Etiam justo.', '3/22/2017');
insert into boards (owner_id, title, description, date_posted) values (62, ' Politics Articles', 'Curabitur at ipsum ac tellus semper interdum.', '9/17/2018');
insert into boards (owner_id, title, description, date_posted) values (77, ' Mandarin School Work', 'In hac habitasse platea dictumst.', '1/21/2018');
insert into boards (owner_id, title, description, date_posted) values (33, ' Organic Chemistry Homework', 'Donec semper sapien a libero.', '4/22/2017');
insert into boards (owner_id, title, description, date_posted) values (81, ' German Homework', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '4/30/2020');
insert into boards (owner_id, title, description, date_posted) values (95, ' Philosophy stuff for school', 'Pellentesque ultrices mattis odio.', '7/24/2020');
insert into boards (owner_id, title, description, date_posted) values (15, ' Science Videos', 'Integer tincidunt ante vel ipsum.', '8/19/2018');
insert into boards (owner_id, title, description, date_posted) values (73, ' English Articles', 'Proin at turpis a pede posuere nonummy.', '9/12/2018');
insert into boards (owner_id, title, description, date_posted) values (60, ' German Resources', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '10/5/2016');
insert into boards (owner_id, title, description, date_posted) values (71, ' Philosophy Board', 'In sagittis dui vel nisl.', '5/21/2016');
insert into boards (owner_id, title, description, date_posted) values (94, ' History Journals', 'Phasellus sit amet erat.', '7/11/2018');
insert into boards (owner_id, title, description, date_posted) values (59, ' Astrophysics - Freshman Year', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '7/29/2017');
insert into boards (owner_id, title, description, date_posted) values (8, ' Classics School Work', 'Maecenas ut massa quis augue luctus tincidunt.', '5/15/2018');
insert into boards (owner_id, title, description, date_posted) values (95, ' Ancient History - useful material', 'Integer non velit.', '3/4/2018');
insert into boards (owner_id, title, description, date_posted) values (95, ' Cognitive Psychology Resources', 'Quisque ut erat.', '10/15/2017');
insert into boards (owner_id, title, description, date_posted) values (73, ' German links and articles', 'Suspendisse accumsan tortor quis turpis.', '6/6/2016');
insert into boards (owner_id, title, description, date_posted) values (45, ' Psychologyand other stuff', 'Praesent blandit.', '9/13/2020');
insert into boards (owner_id, title, description, date_posted) values (52, ' Business Material', 'Morbi vel lectus in quam fringilla rhoncus.', '5/29/2020');
insert into boards (owner_id, title, description, date_posted) values (21, ' Russian Links', 'Donec quis orci eget orci vehicula condimentum.', '10/26/2018');
insert into boards (owner_id, title, description, date_posted) values (41, ' Organic Chemistry Homework', 'Integer tincidunt ante vel ipsum.', '10/23/2017');
insert into boards (owner_id, title, description, date_posted) values (12, ' Philosophy stuff for school', 'Etiam pretium iaculis justo.', '11/22/2017');
insert into boards (owner_id, title, description, date_posted) values (55, ' German links and articles', 'Integer non velit.', '8/31/2017');
insert into boards (owner_id, title, description, date_posted) values (61, ' Geophysics links and articles', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '7/30/2017');
insert into boards (owner_id, title, description, date_posted) values (13, ' Physics Articles', 'Cras non velit nec nisi vulputate nonummy.', '5/13/2019');
insert into boards (owner_id, title, description, date_posted) values (90, ' Philosophy stuff for school', 'Vivamus tortor.', '10/30/2016');
insert into boards (owner_id, title, description, date_posted) values (46, ' Classics Topics', 'Nulla ut erat id mauris vulputate elementum.', '1/14/2020');
insert into boards (owner_id, title, description, date_posted) values (96, ' Philosophy stuff for school', 'Aliquam sit amet diam in magna bibendum imperdiet.', '10/6/2017');
insert into boards (owner_id, title, description, date_posted) values (95, ' Astrophysics stuff for school', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '3/24/2017');
insert into boards (owner_id, title, description, date_posted) values (41, ' Astrophysics Topics', 'Duis mattis egestas metus.', '6/2/2020');
insert into boards (owner_id, title, description, date_posted) values (39, ' Art Journals', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '8/2/2020');
insert into boards (owner_id, title, description, date_posted) values (79, ' Inorganic Chemistry Journals', 'Cras in purus eu magna vulputate luctus.', '6/10/2017');
insert into boards (owner_id, title, description, date_posted) values (32, ' Cognitive Psychology Journals', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '9/10/2020');
insert into boards (owner_id, title, description, date_posted) values (71, ' Spanish - Freshman Year', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '4/17/2018');
insert into boards (owner_id, title, description, date_posted) values (43, ' Microeconomics Resources', 'Aliquam erat volutpat.', '9/6/2019');
insert into boards (owner_id, title, description, date_posted) values (34, ' Philosophy Links', 'Nullam sit amet turpis elementum ligula vehicula consequat.', '1/26/2017');
