insert into board_categories (type, board_id) values ('Geophysics', 86);
insert into board_categories (type, board_id) values ('Marine Biology', 32);
insert into board_categories (type, board_id) values ('Astronomy', 89);
insert into board_categories (type, board_id) values ('Spanish', 62);
insert into board_categories (type, board_id) values ('French', 11);
insert into board_categories (type, board_id) values ('Politics', 8);
insert into board_categories (type, board_id) values ('Neuropsychology', 98);
insert into board_categories (type, board_id) values ('Anthropology', 7);
insert into board_categories (type, board_id) values ('Astronomy', 64);
insert into board_categories (type, board_id) values ('Russian', 13);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 44);
insert into board_categories (type, board_id) values ('Psychology', 42);
insert into board_categories (type, board_id) values ('Ancient History', 64);
insert into board_categories (type, board_id) values ('Arabic', 63);
insert into board_categories (type, board_id) values ('Neuropsychology', 38);
insert into board_categories (type, board_id) values ('Cell Biology', 50);
insert into board_categories (type, board_id) values ('Macroeconomics', 27);
insert into board_categories (type, board_id) values ('Cognitive Psychology', 51);
insert into board_categories (type, board_id) values ('Quantum Physics', 24);
insert into board_categories (type, board_id) values ('Ancient History', 93);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 14);
insert into board_categories (type, board_id) values ('Physiology', 51);
insert into board_categories (type, board_id) values ('History', 80);
insert into board_categories (type, board_id) values ('Geophysics', 21);
insert into board_categories (type, board_id) values ('English', 99);
insert into board_categories (type, board_id) values ('Ancient History', 95);
insert into board_categories (type, board_id) values ('Cell Biology', 5);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 68);
insert into board_categories (type, board_id) values ('Microeconomics', 93);
insert into board_categories (type, board_id) values ('Quantum Physics', 66);
insert into board_categories (type, board_id) values ('Physics', 54);
insert into board_categories (type, board_id) values ('Politics', 6);
insert into board_categories (type, board_id) values ('Neuroscience', 34);
insert into board_categories (type, board_id) values ('French', 18);
insert into board_categories (type, board_id) values ('Spanish', 20);
insert into board_categories (type, board_id) values ('Russian', 2);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 34);
insert into board_categories (type, board_id) values ('Politics', 100);
insert into board_categories (type, board_id) values ('Spanish', 39);
insert into board_categories (type, board_id) values ('Physics', 43);
insert into board_categories (type, board_id) values ('Cell Biology', 69);
insert into board_categories (type, board_id) values ('Neuroscience', 64);
insert into board_categories (type, board_id) values ('Organic Chemistry', 86);
insert into board_categories (type, board_id) values ('Ancient History ', 97);
insert into board_categories (type, board_id) values ('Marine Biology ', 97);
insert into board_categories (type, board_id) values ('English', 33);
insert into board_categories (type, board_id) values ('Geology', 56);
insert into board_categories (type, board_id) values ('Astronomy', 66);
insert into board_categories (type, board_id) values ('Spanish', 83);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 46);
insert into board_categories (type, board_id) values ('English', 80);
insert into board_categories (type, board_id) values ('Cognitive Psychology', 16);
insert into board_categories (type, board_id) values ('Spanish', 23);
insert into board_categories (type, board_id) values ('Classics', 17);
insert into board_categories (type, board_id) values ('Geology', 78);
insert into board_categories (type, board_id) values ('Sociology', 82);
insert into board_categories (type, board_id) values ('Economics', 77);
insert into board_categories (type, board_id) values ('Marine Biology', 72);
insert into board_categories (type, board_id) values ('Organic Chemistry', 66);
insert into board_categories (type, board_id) values ('Astrophysics', 27);
insert into board_categories (type, board_id) values ('Geography', 52);
insert into board_categories (type, board_id) values ('Animal Biology', 62);
insert into board_categories (type, board_id) values ('Philosophy', 56);
insert into board_categories (type, board_id) values ('Astrophysics', 50);
insert into board_categories (type, board_id) values ('Economics', 10);
insert into board_categories (type, board_id) values ('Art', 50);
insert into board_categories (type, board_id) values ('Physiology', 71);
insert into board_categories (type, board_id) values ('Literature', 6);
insert into board_categories (type, board_id) values ('Cell Biology', 3);
insert into board_categories (type, board_id) values ('Mathematics', 47);
insert into board_categories (type, board_id) values ('Microbiology', 70);
insert into board_categories (type, board_id) values ('Physics', 97);
insert into board_categories (type, board_id) values ('Marine Biology', 98);
insert into board_categories (type, board_id) values ('History', 29);
insert into board_categories (type, board_id) values ('Microbiology', 36);
insert into board_categories (type, board_id) values ('Sociology', 48);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 64);
insert into board_categories (type, board_id) values ('Spanish', 19);
insert into board_categories (type, board_id) values ('History', 42);
insert into board_categories (type, board_id) values ('Russian', 90);
insert into board_categories (type, board_id) values ('Neuropsychology', 14);
insert into board_categories (type, board_id) values ('Neuropsychology', 20);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 50);
insert into board_categories (type, board_id) values ('Arabic', 83);
insert into board_categories (type, board_id) values ('Philosophy', 37);
insert into board_categories (type, board_id) values ('Art', 14);
insert into board_categories (type, board_id) values ('Anthropology', 3);
insert into board_categories (type, board_id) values ('Science', 26);
insert into board_categories (type, board_id) values ('Neuroscience', 98);
insert into board_categories (type, board_id) values ('Linguistics', 18);
insert into board_categories (type, board_id) values ('Mandarin', 81);
insert into board_categories (type, board_id) values ('History', 15);
insert into board_categories (type, board_id) values ('Science', 77);
insert into board_categories (type, board_id) values ('Cell Biology', 77);
insert into board_categories (type, board_id) values ('Philosophy', 98);
insert into board_categories (type, board_id) values ('Marine Biology', 42);
insert into board_categories (type, board_id) values ('Inorganic Chemistry', 47);
insert into board_categories (type, board_id) values ('Physics', 60);
insert into board_categories (type, board_id) values ('Classics', 91);
insert into board_categories (type, board_id) values ('Geology', 94);
insert into board_categories (type, board_id) values ('Geology', 30);
