insert into board_categories (type, board_id) values ('business studies', 1);
insert into board_categories (type, board_id) values ('short-presentations', 2);
insert into board_categories (type, board_id) values ('endocrinology', 3);
insert into board_categories (type, board_id) values ('animation development studies', 4);
insert into board_categories (type, board_id) values ('synthetic materials chromatography', 5);
insert into board_categories (type, board_id) values ('phytopathology', 6);
insert into board_categories (type, board_id) values ('', 7);
insert into board_categories (type, board_id) values ('materials physics', 8);
insert into board_categories (type, board_id) values ('oncology', 9);
insert into board_categories (type, board_id) values ('electromagnetism', 10);
insert into board_categories (type, board_id) values ('aerospace', 11);
insert into board_categories (type, board_id) values ('limnology', 12);
insert into board_categories (type, board_id) values ('materials science', 13);
insert into board_categories (type, board_id) values ('extragalactic astronomy', 14);
insert into board_categories (type, board_id) values ('mineral processing', 15);
insert into board_categories (type, board_id) values ('standard model representation theory', 16);
insert into board_categories (type, board_id) values ('production ecosystems', 17);
insert into board_categories (type, board_id) values ('nuclear chemistry', 18);
insert into board_categories (type, board_id) values ('stochastic finance text mining', 19);
insert into board_categories (type, board_id) values ('natural language processing', 20);
insert into board_categories (type, board_id) values ('physics', 21);
insert into board_categories (type, board_id) values ('physics', 22);
insert into board_categories (type, board_id) values ('ultracold atoms', 23);
insert into board_categories (type, board_id) values ('infectious diseases', 24);
insert into board_categories (type, board_id) values ('palynology', 25);
insert into board_categories (type, board_id) values ('mammography', 26);
insert into board_categories (type, board_id) values ('predictive analytics', 27);
insert into board_categories (type, board_id) values ('computer architecture', 28);
insert into board_categories (type, board_id) values ('philosophy', 29);
insert into board_categories (type, board_id) values ('architecture', 30);
insert into board_categories (type, board_id) values ('bioinformatics', 31);
insert into board_categories (type, board_id) values ('conference meteorology', 32);
insert into board_categories (type, board_id) values ('law', 33);
insert into board_categories (type, board_id) values ('programming language theory', 34);
insert into board_categories (type, board_id) values ('group theory', 35);
insert into board_categories (type, board_id) values ('complex variables geography', 36);
insert into board_categories (type, board_id) values ('special relativity', 37);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 38);
insert into board_categories (type, board_id) values ('classical mechanics', 39);
insert into board_categories (type, board_id) values ('atom optics', 40);
insert into board_categories (type, board_id) values ('algorithms', 41);
insert into board_categories (type, board_id) values ('accelerators', 42);
insert into board_categories (type, board_id) values ('archaeology', 43);
insert into board_categories (type, board_id) values ('physical chemistry', 44);
insert into board_categories (type, board_id) values ('commutative algebra', 45);
insert into board_categories (type, board_id) values ('knowledge representation', 46);
insert into board_categories (type, board_id) values ('biomaterials optimization and control', 47);
insert into board_categories (type, board_id) values ('programming language theory', 48);
insert into board_categories (type, board_id) values ('gaming', 49);
insert into board_categories (type, board_id) values ('cybernetics', 50);
insert into board_categories (type, board_id) values ('power engineering', 51);
insert into board_categories (type, board_id) values ('descriptive statistics', 52);
insert into board_categories (type, board_id) values ('portfolio management', 53);
insert into board_categories (type, board_id) values ('ultrafast phenomena', 54);
insert into board_categories (type, board_id) values ('processing hazardous materials', 55);
insert into board_categories (type, board_id) values ('knowledge engineering', 56);
insert into board_categories (type, board_id) values ('ergodic theory', 57);
insert into board_categories (type, board_id) values ('sleep medicine', 58);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 59);
insert into board_categories (type, board_id) values ('metabolic diseases', 60);
insert into board_categories (type, board_id) values ('quantum information', 61);
insert into board_categories (type, board_id) values ('evolutionary computation', 62);
insert into board_categories (type, board_id) values ('laser physics', 63);
insert into board_categories (type, board_id) values ('microtechnology', 64);
insert into board_categories (type, board_id) values ('gynecology', 65);
insert into board_categories (type, board_id) values ('classical mechanics', 66);
insert into board_categories (type, board_id) values ('data management', 67);
insert into board_categories (type, board_id) values ('addication', 68);
insert into board_categories (type, board_id) values ('survival analysis', 69);
insert into board_categories (type, board_id) values ('transportation malaria', 70);
insert into board_categories (type, board_id) values ('galactic astronomy', 71);
insert into board_categories (type, board_id) values ('supramolecular chemistry', 72);
insert into board_categories (type, board_id) values ('ichthyology', 73);
insert into board_categories (type, board_id) values ('gaming', 74);
insert into board_categories (type, board_id) values ('open source', 75);
insert into board_categories (type, board_id) values ('data mining', 76);
insert into board_categories (type, board_id) values ('geostatistics', 77);
insert into board_categories (type, board_id) values ('ubiquitous computing', 78);
insert into board_categories (type, board_id) values ('computational finance', 79);
insert into board_categories (type, board_id) values ('knowledge discovery', 80);
insert into board_categories (type, board_id) values ('chemo-informatics queues', 81);
insert into board_categories (type, board_id) values ('nanobiology', 82);
insert into board_categories (type, board_id) values ('display devices', 83);
insert into board_categories (type, board_id) values ('survival analysis', 84);
insert into board_categories (type, board_id) values ('processing hazardous materials', 85);
insert into board_categories (type, board_id) values ('quantum information', 86);
insert into board_categories (type, board_id) values ('applied chemistry', 87);
insert into board_categories (type, board_id) values ('biodiversity', 88);
insert into board_categories (type, board_id) values ('phytopathology', 89);
insert into board_categories (type, board_id) values ('computational physics', 90);
insert into board_categories (type, board_id) values ('evolutionary computation', 91);
insert into board_categories (type, board_id) values ('quantum optics', 92);
insert into board_categories (type, board_id) values ('supersymmetry', 93);
insert into board_categories (type, board_id) values ('railways', 94);
insert into board_categories (type, board_id) values ('radiology', 95);
insert into board_categories (type, board_id) values ('parallel computing', 96);
insert into board_categories (type, board_id) values ('data mining', 97);
insert into board_categories (type, board_id) values ('spectroscopy', 98);
insert into board_categories (type, board_id) values ('sustainable development', 99);
insert into board_categories (type, board_id) values ('environmental science', 100);
insert into board_categories (type, board_id) values ('physiology', 101);
insert into board_categories (type, board_id) values ('chemo-informatics queues', 102);
insert into board_categories (type, board_id) values ('molecular mechanics', 103);
insert into board_categories (type, board_id) values ('synthetic biology science', 104);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 105);
insert into board_categories (type, board_id) values ('history of cosmic ray research', 106);
insert into board_categories (type, board_id) values ('microtechnology', 107);
insert into board_categories (type, board_id) values ('network science', 108);
insert into board_categories (type, board_id) values ('accelerators', 109);
insert into board_categories (type, board_id) values ('oncology', 110);
insert into board_categories (type, board_id) values ('statistical computing', 111);
insert into board_categories (type, board_id) values ('cosmology', 112);
insert into board_categories (type, board_id) values ('architecture', 113);
insert into board_categories (type, board_id) values ('family practice', 114);
insert into board_categories (type, board_id) values ('psychology', 115);
insert into board_categories (type, board_id) values ('descriptive statistics', 116);
insert into board_categories (type, board_id) values ('computer architecture', 117);
insert into board_categories (type, board_id) values ('processing hazardous materials', 118);
insert into board_categories (type, board_id) values ('mammography', 119);
insert into board_categories (type, board_id) values ('sonochemistry', 120);
insert into board_categories (type, board_id) values ('climate change analytics', 121);
insert into board_categories (type, board_id) values ('special relativity', 122);
insert into board_categories (type, board_id) values ('sustainable development', 123);
insert into board_categories (type, board_id) values ('petrology', 124);
insert into board_categories (type, board_id) values ('quantum information', 125);
insert into board_categories (type, board_id) values ('group theory', 126);
insert into board_categories (type, board_id) values ('network security', 127);
insert into board_categories (type, board_id) values ('operating systems', 128);
insert into board_categories (type, board_id) values ('statistical mechanics', 129);
insert into board_categories (type, board_id) values ('mathematical chemistry', 130);
insert into board_categories (type, board_id) values ('data management', 131);
insert into board_categories (type, board_id) values ('many body systems', 132);
insert into board_categories (type, board_id) values ('tectonics', 133);
insert into board_categories (type, board_id) values ('general biology', 134);
insert into board_categories (type, board_id) values ('autoimmunity', 135);
insert into board_categories (type, board_id) values ('energy', 136);
insert into board_categories (type, board_id) values ('natural language processing', 137);
insert into board_categories (type, board_id) values ('haematology', 138);
insert into board_categories (type, board_id) values ('microenvironment', 139);
insert into board_categories (type, board_id) values ('entomology', 140);
insert into board_categories (type, board_id) values ('computational finance', 141);
insert into board_categories (type, board_id) values ('computational physics', 142);
insert into board_categories (type, board_id) values ('addication', 143);
insert into board_categories (type, board_id) values ('algorithms', 144);
insert into board_categories (type, board_id) values ('information systems', 145);
insert into board_categories (type, board_id) values ('oligonucleotides', 146);
insert into board_categories (type, board_id) values ('sleep medicine', 147);
insert into board_categories (type, board_id) values ('archaeology', 148);
insert into board_categories (type, board_id) values ('classical mechanics', 149);
insert into board_categories (type, board_id) values ('metric geometry growth and synthesis', 150);
insert into board_categories (type, board_id) values ('gender and sexuality studies', 151);
insert into board_categories (type, board_id) values ('quantum devices', 152);
insert into board_categories (type, board_id) values ('gender and sexuality studies', 153);
insert into board_categories (type, board_id) values ('metabolic diseases', 154);
insert into board_categories (type, board_id) values ('tomography', 155);
insert into board_categories (type, board_id) values ('green computing', 156);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 157);
insert into board_categories (type, board_id) values ('sonography', 158);
insert into board_categories (type, board_id) values ('galactic astronomy', 159);
insert into board_categories (type, board_id) values ('psychobiology', 160);
insert into board_categories (type, board_id) values ('salford systems', 161);
insert into board_categories (type, board_id) values ('preventive medicine', 162);
insert into board_categories (type, board_id) values ('geochronology', 163);
insert into board_categories (type, board_id) values ('optoelectronics', 164);
insert into board_categories (type, board_id) values ('physiology', 165);
insert into board_categories (type, board_id) values ('metabolic diseases', 166);
insert into board_categories (type, board_id) values ('quantum information', 167);
insert into board_categories (type, board_id) values ('electric power', 168);
insert into board_categories (type, board_id) values ('cognitive science', 169);
insert into board_categories (type, board_id) values ('human-computer interaction', 170);
insert into board_categories (type, board_id) values ('biophysics', 171);
insert into board_categories (type, board_id) values ('classical analysis', 172);
insert into board_categories (type, board_id) values ('radiation therapy', 173);
insert into board_categories (type, board_id) values ('network science', 174);
insert into board_categories (type, board_id) values ('knowledge engineering', 175);
insert into board_categories (type, board_id) values ('windpower', 176);
insert into board_categories (type, board_id) values ('algorithms', 177);
insert into board_categories (type, board_id) values ('systems security', 178);
insert into board_categories (type, board_id) values ('optical lattices', 179);
insert into board_categories (type, board_id) values ('survival analysis', 180);
insert into board_categories (type, board_id) values ('asymptotic inference', 181);
insert into board_categories (type, board_id) values ('e-business', 182);
insert into board_categories (type, board_id) values ('teaching', 183);
insert into board_categories (type, board_id) values ('entomology', 184);
insert into board_categories (type, board_id) values ('circuits', 185);
insert into board_categories (type, board_id) values ('nuclear magnetic resonance imaging', 186);
insert into board_categories (type, board_id) values ('psychology', 187);
insert into board_categories (type, board_id) values ('quantum algebra', 188);
insert into board_categories (type, board_id) values ('many body systems', 189);
insert into board_categories (type, board_id) values ('neuroimaging ophthalmology', 190);
insert into board_categories (type, board_id) values ('human resource management', 191);
insert into board_categories (type, board_id) values ('femtochemistry', 192);
insert into board_categories (type, board_id) values ('mineral processing', 193);
insert into board_categories (type, board_id) values ('geomorphology botany', 194);
insert into board_categories (type, board_id) values ('sustainable development', 195);
insert into board_categories (type, board_id) values ('atmospheric chemistry', 196);
insert into board_categories (type, board_id) values ('microenvironment', 197);
insert into board_categories (type, board_id) values ('ultracold atoms', 198);
insert into board_categories (type, board_id) values ('quantum devices', 199);
insert into board_categories (type, board_id) values ('digital multimedia', 200);
insert into board_categories (type, board_id) values ('cognitive science', 201);
insert into board_categories (type, board_id) values ('synthetic materials chromatography', 202);
insert into board_categories (type, board_id) values ('philosophical quantum algorithms', 203);
insert into board_categories (type, board_id) values ('synthetic biology science', 204);
insert into board_categories (type, board_id) values ('archaeology', 205);
insert into board_categories (type, board_id) values ('metallurgy', 206);
insert into board_categories (type, board_id) values ('materials engineering', 207);
insert into board_categories (type, board_id) values ('self-organizing systems', 208);
insert into board_categories (type, board_id) values ('darkenergy scanning probe', 209);
insert into board_categories (type, board_id) values ('metallurgy', 210);
insert into board_categories (type, board_id) values ('nuclear energy', 211);
insert into board_categories (type, board_id) values ('addication', 212);
insert into board_categories (type, board_id) values ('open source', 213);
insert into board_categories (type, board_id) values ('social networks', 214);
insert into board_categories (type, board_id) values ('flavor chemistry', 215);
insert into board_categories (type, board_id) values ('quantum field theory', 216);
insert into board_categories (type, board_id) values ('railways', 217);
insert into board_categories (type, board_id) values ('laser physics', 218);
insert into board_categories (type, board_id) values ('light curves', 219);
insert into board_categories (type, board_id) values ('neurology', 220);
insert into board_categories (type, board_id) values ('architecture', 221);
insert into board_categories (type, board_id) values ('complexity theory', 222);
insert into board_categories (type, board_id) values ('open source', 223);
insert into board_categories (type, board_id) values ('addication', 224);
insert into board_categories (type, board_id) values ('network security', 225);
insert into board_categories (type, board_id) values ('nuclear chemistry', 226);
insert into board_categories (type, board_id) values ('data management', 227);
insert into board_categories (type, board_id) values ('physics', 228);
insert into board_categories (type, board_id) values ('multiagent systems', 229);
insert into board_categories (type, board_id) values ('automotive engineering', 230);
insert into board_categories (type, board_id) values ('quantum channels', 231);
insert into board_categories (type, board_id) values ('systems biology', 232);
insert into board_categories (type, board_id) values ('mass spectroscopy nmr', 233);
insert into board_categories (type, board_id) values ('digital libraries', 234);
insert into board_categories (type, board_id) values ('special relativity', 235);
insert into board_categories (type, board_id) values ('computational biology', 236);
insert into board_categories (type, board_id) values ('atmospheric science', 237);
insert into board_categories (type, board_id) values ('entomology', 238);
insert into board_categories (type, board_id) values ('nuclear magnetic resonance imaging', 239);
insert into board_categories (type, board_id) values ('radiobiology', 240);
insert into board_categories (type, board_id) values ('climatology', 241);
insert into board_categories (type, board_id) values ('treenet', 242);
insert into board_categories (type, board_id) values ('symbolic computation', 243);
insert into board_categories (type, board_id) values ('neurobiology', 244);
insert into board_categories (type, board_id) values ('haematology', 245);
insert into board_categories (type, board_id) values ('environmental science', 246);
insert into board_categories (type, board_id) values ('sonochemistry', 247);
insert into board_categories (type, board_id) values ('differential equations', 248);
insert into board_categories (type, board_id) values ('flavor chemistry', 249);
insert into board_categories (type, board_id) values ('m-theory', 250);
insert into board_categories (type, board_id) values ('international studies', 251);
insert into board_categories (type, board_id) values ('integrative biology', 252);
insert into board_categories (type, board_id) values ('machine learning', 253);
insert into board_categories (type, board_id) values ('programming language theory', 254);
insert into board_categories (type, board_id) values ('mass spectroscopy nmr', 255);
insert into board_categories (type, board_id) values ('open science', 256);
insert into board_categories (type, board_id) values ('mathematical chemistry', 257);
insert into board_categories (type, board_id) values ('international studies', 258);
insert into board_categories (type, board_id) values ('atmospheric science', 259);
insert into board_categories (type, board_id) values ('business area studies', 260);
insert into board_categories (type, board_id) values ('programming language theory', 261);
insert into board_categories (type, board_id) values ('palynology', 262);
insert into board_categories (type, board_id) values ('quantum electrodynamics', 263);
insert into board_categories (type, board_id) values ('symbolic computation', 264);
insert into board_categories (type, board_id) values ('nutrition science', 265);
insert into board_categories (type, board_id) values ('neuropeptides', 266);
insert into board_categories (type, board_id) values ('systems biology', 267);
insert into board_categories (type, board_id) values ('evolutionary dynamics', 268);
insert into board_categories (type, board_id) values ('quantum channels', 269);
insert into board_categories (type, board_id) values ('building materials', 270);
insert into board_categories (type, board_id) values ('dementia', 271);
insert into board_categories (type, board_id) values ('operating systems', 272);
insert into board_categories (type, board_id) values ('many body systems', 273);
insert into board_categories (type, board_id) values ('image processing', 274);
insert into board_categories (type, board_id) values ('clinical immunology', 275);
insert into board_categories (type, board_id) values ('oligonucleotides', 276);
insert into board_categories (type, board_id) values ('astrobiology', 277);
insert into board_categories (type, board_id) values ('radiation therapy', 278);
insert into board_categories (type, board_id) values ('public health', 279);
insert into board_categories (type, board_id) values ('symbolic computation', 280);
insert into board_categories (type, board_id) values ('circuits', 281);
insert into board_categories (type, board_id) values ('physics', 282);
insert into board_categories (type, board_id) values ('gender and sexuality studies', 283);
insert into board_categories (type, board_id) values ('trichology', 284);
insert into board_categories (type, board_id) values ('salford predictive modeler', 285);
insert into board_categories (type, board_id) values ('chemical biology', 286);
insert into board_categories (type, board_id) values ('cognitive science', 287);
insert into board_categories (type, board_id) values ('clinical immunology', 288);
insert into board_categories (type, board_id) values ('e-business', 289);
insert into board_categories (type, board_id) values ('computation and language', 290);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 291);
insert into board_categories (type, board_id) values ('philosophy', 292);
insert into board_categories (type, board_id) values ('human-computer interaction', 293);
insert into board_categories (type, board_id) values ('cryptography', 294);
insert into board_categories (type, board_id) values ('theoretical computer science', 295);
insert into board_categories (type, board_id) values ('stochastic PDE devices and applications', 296);
insert into board_categories (type, board_id) values ('computer vision', 297);
insert into board_categories (type, board_id) values ('nuclear technology', 298);
insert into board_categories (type, board_id) values ('knowledge discovery', 299);
insert into board_categories (type, board_id) values ('metric geometry growth and synthesis', 300);
insert into board_categories (type, board_id) values ('quantum algebra', 301);
insert into board_categories (type, board_id) values ('quantum channels', 302);
insert into board_categories (type, board_id) values ('circuits', 303);
insert into board_categories (type, board_id) values ('geochronology', 304);
insert into board_categories (type, board_id) values ('computational neuroscience', 305);
insert into board_categories (type, board_id) values ('computer vision', 306);
insert into board_categories (type, board_id) values ('ultrafast phenomena', 307);
insert into board_categories (type, board_id) values ('aerobiology', 308);
insert into board_categories (type, board_id) values ('particle physics', 309);
insert into board_categories (type, board_id) values ('microtechnology', 310);
insert into board_categories (type, board_id) values ('metric geometry growth and synthesis', 311);
insert into board_categories (type, board_id) values ('clinical immunology', 312);
insert into board_categories (type, board_id) values ('sedimentology', 313);
insert into board_categories (type, board_id) values ('m-theory', 314);
insert into board_categories (type, board_id) values ('cell signalling', 315);
insert into board_categories (type, board_id) values ('endocrinology', 316);
insert into board_categories (type, board_id) values ('atmospheric science', 317);
insert into board_categories (type, board_id) values ('integrative biology', 318);
insert into board_categories (type, board_id) values ('computation and language', 319);
insert into board_categories (type, board_id) values ('sonochemistry', 320);
insert into board_categories (type, board_id) values ('applied mathematics', 321);
insert into board_categories (type, board_id) values ('open science', 322);
insert into board_categories (type, board_id) values ('stochastic PDE devices and applications', 323);
insert into board_categories (type, board_id) values ('ultrafast phenomena', 324);
insert into board_categories (type, board_id) values ('numerical analysis', 325);
insert into board_categories (type, board_id) values ('thermochemistry', 326);
insert into board_categories (type, board_id) values ('metabolism', 327);
insert into board_categories (type, board_id) values ('knowledge discovery', 328);
insert into board_categories (type, board_id) values ('microtechnology', 329);
insert into board_categories (type, board_id) values ('ethology', 330);
insert into board_categories (type, board_id) values ('high performance computing', 331);
insert into board_categories (type, board_id) values ('public health', 332);
insert into board_categories (type, board_id) values ('human resource management', 333);
insert into board_categories (type, board_id) values ('thermochemistry', 334);
insert into board_categories (type, board_id) values ('accelerators', 335);
insert into board_categories (type, board_id) values ('differential games', 336);
insert into board_categories (type, board_id) values ('nonlinear science', 337);
insert into board_categories (type, board_id) values ('developmental biology', 338);
insert into board_categories (type, board_id) values ('nuclear medicine', 339);
insert into board_categories (type, board_id) values ('salford systems', 340);
insert into board_categories (type, board_id) values ('hypertension solid', 341);
insert into board_categories (type, board_id) values ('light curves', 342);
insert into board_categories (type, board_id) values ('balloon and satellite measurements', 343);
insert into board_categories (type, board_id) values ('tumor', 344);
insert into board_categories (type, board_id) values ('materials physics', 345);
insert into board_categories (type, board_id) values ('cognitive science', 346);
insert into board_categories (type, board_id) values ('petrochemistry', 347);
insert into board_categories (type, board_id) values ('geology', 348);
insert into board_categories (type, board_id) values ('computational neuroscience', 349);
insert into board_categories (type, board_id) values ('tomography', 350);
insert into board_categories (type, board_id) values ('pharmaceutical chemistry', 351);
insert into board_categories (type, board_id) values ('applied mathematics', 352);
insert into board_categories (type, board_id) values ('web services', 353);
insert into board_categories (type, board_id) values ('open source', 354);
insert into board_categories (type, board_id) values ('light curves', 355);
insert into board_categories (type, board_id) values ('agrochemistry', 356);
insert into board_categories (type, board_id) values ('habitable zone psychophysiology', 357);
insert into board_categories (type, board_id) values ('haematology', 358);
insert into board_categories (type, board_id) values ('metabolism', 359);
insert into board_categories (type, board_id) values ('teaching', 360);
insert into board_categories (type, board_id) values ('history', 361);
insert into board_categories (type, board_id) values ('mechanochemistry', 362);
insert into board_categories (type, board_id) values ('aerospace', 363);
insert into board_categories (type, board_id) values ('complex systems', 364);
insert into board_categories (type, board_id) values ('computation and language', 365);
insert into board_categories (type, board_id) values ('mechanochemistry', 366);
insert into board_categories (type, board_id) values ('general biology', 367);
insert into board_categories (type, board_id) values ('computational intelligence', 368);
insert into board_categories (type, board_id) values ('thermochemistry', 369);
insert into board_categories (type, board_id) values ('topological', 370);
insert into board_categories (type, board_id) values ('numerical analysis', 371);
insert into board_categories (type, board_id) values ('human resource management', 372);
insert into board_categories (type, board_id) values ('programming languages', 373);
insert into board_categories (type, board_id) values ('mathematcics', 374);
insert into board_categories (type, board_id) values ('survival analysis', 375);
insert into board_categories (type, board_id) values ('multiagent systems', 376);
insert into board_categories (type, board_id) values ('international studies', 377);
insert into board_categories (type, board_id) values ('evolutionary computation', 378);
insert into board_categories (type, board_id) values ('biology', 379);
insert into board_categories (type, board_id) values ('limnology', 380);
insert into board_categories (type, board_id) values ('microbiology', 381);
insert into board_categories (type, board_id) values ('hepatology', 382);
insert into board_categories (type, board_id) values ('computational intelligence', 383);
insert into board_categories (type, board_id) values ('statistical finance', 384);
insert into board_categories (type, board_id) values ('plant biology', 385);
insert into board_categories (type, board_id) values ('sustainable development', 386);
insert into board_categories (type, board_id) values ('quantum states', 387);
insert into board_categories (type, board_id) values ('electrochemistry', 388);
insert into board_categories (type, board_id) values ('solar physics', 389);
insert into board_categories (type, board_id) values ('preventive medicine', 390);
insert into board_categories (type, board_id) values ('nursing', 391);
insert into board_categories (type, board_id) values ('plastic', 392);
insert into board_categories (type, board_id) values ('production ecosystems', 393);
insert into board_categories (type, board_id) values ('proteins', 394);
insert into board_categories (type, board_id) values ('computing sensor networks', 395);
insert into board_categories (type, board_id) values ('molecular mechanics', 396);
insert into board_categories (type, board_id) values ('cart ultra-high energy', 397);
insert into board_categories (type, board_id) values ('plastic', 398);
insert into board_categories (type, board_id) values ('game theory', 399);
insert into board_categories (type, board_id) values ('plant science', 400);
insert into board_categories (type, board_id) values ('systems security', 401);
insert into board_categories (type, board_id) values ('computational physics', 402);
insert into board_categories (type, board_id) values ('communication studies', 403);
insert into board_categories (type, board_id) values ('astrobiology', 404);
insert into board_categories (type, board_id) values ('haematology', 405);
insert into board_categories (type, board_id) values ('network science', 406);
insert into board_categories (type, board_id) values ('volcanology', 407);
insert into board_categories (type, board_id) values ('ultrashort pulses', 408);
insert into board_categories (type, board_id) values ('stochastic processes', 409);
insert into board_categories (type, board_id) values ('cognitive science', 410);
insert into board_categories (type, board_id) values ('physicochemical atomic physics', 411);
insert into board_categories (type, board_id) values ('neurobiology', 412);
insert into board_categories (type, board_id) values ('complex networks', 413);
insert into board_categories (type, board_id) values ('virology', 414);
insert into board_categories (type, board_id) values ('optoelectronics', 415);
insert into board_categories (type, board_id) values ('limit theory', 416);
insert into board_categories (type, board_id) values ('mathematcics', 417);
insert into board_categories (type, board_id) values ('metallurgy', 418);
insert into board_categories (type, board_id) values ('numerical simulation', 419);
insert into board_categories (type, board_id) values ('ultrashort pulses', 420);
insert into board_categories (type, board_id) values ('privacy signal processing', 421);
insert into board_categories (type, board_id) values ('nanomaterials', 422);
insert into board_categories (type, board_id) values ('femtochemistry', 423);
insert into board_categories (type, board_id) values ('quantum electronics', 424);
insert into board_categories (type, board_id) values ('spaceflight', 425);
insert into board_categories (type, board_id) values ('oncology', 426);
insert into board_categories (type, board_id) values ('computational finance', 427);
insert into board_categories (type, board_id) values ('nursing', 428);
insert into board_categories (type, board_id) values ('chemo-informatics queues', 429);
insert into board_categories (type, board_id) values ('embedded systems', 430);
insert into board_categories (type, board_id) values ('tumor', 431);
insert into board_categories (type, board_id) values ('many body systems', 432);
insert into board_categories (type, board_id) values ('quantum channels', 433);
insert into board_categories (type, board_id) values ('cosmology', 434);
insert into board_categories (type, board_id) values ('parallel computing', 435);
insert into board_categories (type, board_id) values ('diabetes', 436);
insert into board_categories (type, board_id) values ('electronics', 437);
insert into board_categories (type, board_id) values ('quantum information processing', 438);
insert into board_categories (type, board_id) values ('cryptography', 439);
insert into board_categories (type, board_id) values ('quantum devices', 440);
insert into board_categories (type, board_id) values ('metallurgy', 441);
insert into board_categories (type, board_id) values ('archaeology', 442);
insert into board_categories (type, board_id) values ('drug discovery', 443);
insert into board_categories (type, board_id) values ('internal medicine', 444);
insert into board_categories (type, board_id) values ('cart ultra-high energy', 445);
insert into board_categories (type, board_id) values ('food chemistry', 446);
insert into board_categories (type, board_id) values ('geology', 447);
insert into board_categories (type, board_id) values ('autoimmunity', 448);
insert into board_categories (type, board_id) values ('fuzzy systems', 449);
insert into board_categories (type, board_id) values ('numerical analysis', 450);
insert into board_categories (type, board_id) values ('mechanochemistry', 451);
insert into board_categories (type, board_id) values ('cosmic rays', 452);
insert into board_categories (type, board_id) values ('microbial stresses transit', 453);
insert into board_categories (type, board_id) values ('quantum devices', 454);
insert into board_categories (type, board_id) values ('spaceflight', 455);
insert into board_categories (type, board_id) values ('electronics', 456);
insert into board_categories (type, board_id) values ('addication', 457);
insert into board_categories (type, board_id) values ('thermochemistry', 458);
insert into board_categories (type, board_id) values ('numerical analysis', 459);
insert into board_categories (type, board_id) values ('computer architecture', 460);
insert into board_categories (type, board_id) values ('computer graphics', 461);
insert into board_categories (type, board_id) values ('short-presentations', 462);
insert into board_categories (type, board_id) values ('e-commerce', 463);
insert into board_categories (type, board_id) values ('multiagent systems', 464);
insert into board_categories (type, board_id) values ('cardiovascular medicine allergy', 465);
insert into board_categories (type, board_id) values ('privacy signal processing', 466);
insert into board_categories (type, board_id) values ('evolutionary computation', 467);
insert into board_categories (type, board_id) values ('resting state optical fibres', 468);
insert into board_categories (type, board_id) values ('mammography', 469);
insert into board_categories (type, board_id) values ('computational geometry', 470);
insert into board_categories (type, board_id) values ('geology', 471);
insert into board_categories (type, board_id) values ('high performance computing', 472);
insert into board_categories (type, board_id) values ('high performance computing', 473);
insert into board_categories (type, board_id) values ('microbiology', 474);
insert into board_categories (type, board_id) values ('bioinformatics', 475);
insert into board_categories (type, board_id) values ('naturalproduct chemistry', 476);
insert into board_categories (type, board_id) values ('habitable zone psychophysiology', 477);
insert into board_categories (type, board_id) values ('control theory', 478);
insert into board_categories (type, board_id) values ('systems biology', 479);
insert into board_categories (type, board_id) values ('geophysics', 480);
insert into board_categories (type, board_id) values ('ultracold atoms', 481);
insert into board_categories (type, board_id) values ('policy', 482);
insert into board_categories (type, board_id) values ('plastic', 483);
insert into board_categories (type, board_id) values ('machine learning', 484);
insert into board_categories (type, board_id) values ('cart ultra-high energy', 485);
insert into board_categories (type, board_id) values ('physical chemistry', 486);
insert into board_categories (type, board_id) values ('infectious diseases', 487);
insert into board_categories (type, board_id) values ('biology', 488);
insert into board_categories (type, board_id) values ('human resource management', 489);
insert into board_categories (type, board_id) values ('cultural and ethnic studies', 490);
insert into board_categories (type, board_id) values ('communication and control', 491);
insert into board_categories (type, board_id) values ('mobile computing', 492);
insert into board_categories (type, board_id) values ('energy', 493);
insert into board_categories (type, board_id) values ('data management', 494);
insert into board_categories (type, board_id) values ('metabolism', 495);
insert into board_categories (type, board_id) values ('quantum algebra', 496);
insert into board_categories (type, board_id) values ('metabolic diseases', 497);
insert into board_categories (type, board_id) values ('gamma rays', 498);
insert into board_categories (type, board_id) values ('endocrinology', 499);
insert into board_categories (type, board_id) values ('quantum optics', 500);
