insert into board_categories (type, board_id) values (' Geophysics ', 86);
insert into board_categories (type, board_id) values (' Marine Biology ', 32);
insert into board_categories (type, board_id) values (' Astronomy ', 89);
insert into board_categories (type, board_id) values (' Spanish ', 62);
insert into board_categories (type, board_id) values (' French ', 11);
insert into board_categories (type, board_id) values (' Politics ', 8);
insert into board_categories (type, board_id) values (' Neuropsychology ', 98);
insert into board_categories (type, board_id) values (' Anthropology ', 7);
insert into board_categories (type, board_id) values (' Astronomy ', 64);
insert into board_categories (type, board_id) values (' Russian ', 13);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 44);
insert into board_categories (type, board_id) values (' Psychology', 42);
insert into board_categories (type, board_id) values (' Ancient History ', 64);
insert into board_categories (type, board_id) values (' Arabic ', 63);
insert into board_categories (type, board_id) values (' Neuropsychology ', 38);
insert into board_categories (type, board_id) values (' Cell Biology ', 50);
insert into board_categories (type, board_id) values (' Macroeconomics ', 27);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 51);
insert into board_categories (type, board_id) values (' Quantum Physics ', 24);
insert into board_categories (type, board_id) values (' Ancient History ', 93);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 14);
insert into board_categories (type, board_id) values (' Physiology ', 51);
insert into board_categories (type, board_id) values (' History ', 80);
insert into board_categories (type, board_id) values (' Geophysics ', 21);
insert into board_categories (type, board_id) values (' English ', 99);
insert into board_categories (type, board_id) values (' Ancient History ', 95);
insert into board_categories (type, board_id) values (' Cell Biology ', 5);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 68);
insert into board_categories (type, board_id) values (' Microeconomics ', 93);
insert into board_categories (type, board_id) values (' Quantum Physics ', 66);
insert into board_categories (type, board_id) values (' Physics ', 54);
insert into board_categories (type, board_id) values (' Politics ', 6);
insert into board_categories (type, board_id) values (' Neuroscience ', 34);
insert into board_categories (type, board_id) values (' French ', 18);
insert into board_categories (type, board_id) values (' Spanish ', 20);
insert into board_categories (type, board_id) values (' Russian ', 2);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 34);
insert into board_categories (type, board_id) values (' Politics ', 100);
insert into board_categories (type, board_id) values (' Spanish ', 39);
insert into board_categories (type, board_id) values (' Physics ', 43);
insert into board_categories (type, board_id) values (' Cell Biology ', 69);
insert into board_categories (type, board_id) values (' Neuroscience ', 64);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 86);
insert into board_categories (type, board_id) values (' Ancient History ', 97);
insert into board_categories (type, board_id) values (' Marine Biology ', 97);
insert into board_categories (type, board_id) values (' English ', 33);
insert into board_categories (type, board_id) values (' Geology ', 56);
insert into board_categories (type, board_id) values (' Astronomy ', 66);
insert into board_categories (type, board_id) values (' Spanish ', 83);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 46);
insert into board_categories (type, board_id) values (' English ', 80);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 16);
insert into board_categories (type, board_id) values (' Spanish ', 23);
insert into board_categories (type, board_id) values (' Classics ', 17);
insert into board_categories (type, board_id) values (' Geology ', 78);
insert into board_categories (type, board_id) values (' Sociology ', 82);
insert into board_categories (type, board_id) values (' Economics ', 77);
insert into board_categories (type, board_id) values (' Marine Biology ', 72);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 66);
insert into board_categories (type, board_id) values (' Astrophysics ', 27);
insert into board_categories (type, board_id) values (' Geography ', 52);
insert into board_categories (type, board_id) values (' Animal Biology ', 62);
insert into board_categories (type, board_id) values (' Philosophy ', 56);
insert into board_categories (type, board_id) values (' Astrophysics ', 50);
insert into board_categories (type, board_id) values (' Economics ', 10);
insert into board_categories (type, board_id) values (' Art ', 50);
insert into board_categories (type, board_id) values (' Physiology ', 71);
insert into board_categories (type, board_id) values (' Literature ', 6);
insert into board_categories (type, board_id) values (' Cell Biology ', 3);
insert into board_categories (type, board_id) values (' Mathematics ', 47);
insert into board_categories (type, board_id) values (' Microbiology ', 70);
insert into board_categories (type, board_id) values (' Physics ', 97);
insert into board_categories (type, board_id) values (' Marine Biology ', 98);
insert into board_categories (type, board_id) values (' History ', 29);
insert into board_categories (type, board_id) values (' Microbiology ', 36);
insert into board_categories (type, board_id) values (' Sociology ', 48);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 64);
insert into board_categories (type, board_id) values (' Spanish ', 19);
insert into board_categories (type, board_id) values (' History ', 42);
insert into board_categories (type, board_id) values (' Russian ', 90);
insert into board_categories (type, board_id) values (' Neuropsychology ', 14);
insert into board_categories (type, board_id) values (' Neuropsychology ', 20);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 50);
insert into board_categories (type, board_id) values (' Arabic ', 83);
insert into board_categories (type, board_id) values (' Philosophy ', 37);
insert into board_categories (type, board_id) values (' Art ', 14);
insert into board_categories (type, board_id) values (' Anthropology ', 3);
insert into board_categories (type, board_id) values (' Science ', 26);
insert into board_categories (type, board_id) values (' Neuroscience ', 98);
insert into board_categories (type, board_id) values (' Linguistics ', 18);
insert into board_categories (type, board_id) values (' Mandarin ', 81);
insert into board_categories (type, board_id) values (' History ', 15);
insert into board_categories (type, board_id) values (' Science ', 77);
insert into board_categories (type, board_id) values (' Cell Biology ', 77);
insert into board_categories (type, board_id) values (' Philosophy ', 98);
insert into board_categories (type, board_id) values (' Marine Biology ', 42);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 47);
insert into board_categories (type, board_id) values (' Physics ', 60);
insert into board_categories (type, board_id) values (' Classics ', 91);
insert into board_categories (type, board_id) values (' Geology ', 94);
insert into board_categories (type, board_id) values (' Geology ', 30);
insert into board_categories (type, board_id) values (' Geology ', 30);
insert into board_categories (type, board_id) values (' Neuropsychology ', 97);
insert into board_categories (type, board_id) values (' Neuropsychology ', 64);
insert into board_categories (type, board_id) values (' Language ', 38);
insert into board_categories (type, board_id) values (' Physiology ', 74);
insert into board_categories (type, board_id) values (' German ', 91);
insert into board_categories (type, board_id) values (' Physics ', 89);
insert into board_categories (type, board_id) values (' Physiology ', 28);
insert into board_categories (type, board_id) values (' Philosophy ', 43);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 9);
insert into board_categories (type, board_id) values (' Mandarin ', 65);
insert into board_categories (type, board_id) values (' Neuroscience ', 99);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 30);
insert into board_categories (type, board_id) values (' Quantum Physics ', 28);
insert into board_categories (type, board_id) values (' Physics ', 59);
insert into board_categories (type, board_id) values (' Geography ', 96);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 89);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 71);
insert into board_categories (type, board_id) values (' Physics ', 32);
insert into board_categories (type, board_id) values (' Economics ', 18);
insert into board_categories (type, board_id) values (' Physics ', 1);
insert into board_categories (type, board_id) values (' Anthropology ', 75);
insert into board_categories (type, board_id) values (' Marine Biology ', 30);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 39);
insert into board_categories (type, board_id) values (' Art ', 84);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 63);
insert into board_categories (type, board_id) values (' Ancient History ', 61);
insert into board_categories (type, board_id) values (' Physiology ', 1);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 18);
insert into board_categories (type, board_id) values (' Science ', 16);
insert into board_categories (type, board_id) values (' Psychology', 23);
insert into board_categories (type, board_id) values (' Mandarin ', 54);
insert into board_categories (type, board_id) values (' Science ', 64);
insert into board_categories (type, board_id) values (' Animal Biology ', 97);
insert into board_categories (type, board_id) values (' French ', 91);
insert into board_categories (type, board_id) values (' Business ', 50);
insert into board_categories (type, board_id) values (' Ancient History ', 34);
insert into board_categories (type, board_id) values (' Physics ', 42);
insert into board_categories (type, board_id) values (' Business ', 39);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 63);
insert into board_categories (type, board_id) values (' German ', 69);
insert into board_categories (type, board_id) values (' English ', 78);
insert into board_categories (type, board_id) values (' Language ', 18);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 26);
insert into board_categories (type, board_id) values (' Art ', 42);
insert into board_categories (type, board_id) values (' Geography ', 21);
insert into board_categories (type, board_id) values (' Macroeconomics ', 85);
insert into board_categories (type, board_id) values (' German ', 80);
insert into board_categories (type, board_id) values (' Physics ', 91);
insert into board_categories (type, board_id) values (' Russian ', 79);
insert into board_categories (type, board_id) values (' Russian ', 33);
insert into board_categories (type, board_id) values (' Microbiology ', 27);
insert into board_categories (type, board_id) values (' Neuropsychology ', 93);
insert into board_categories (type, board_id) values (' Mandarin ', 79);
insert into board_categories (type, board_id) values (' Mathematics ', 47);
insert into board_categories (type, board_id) values (' Neuropsychology ', 8);
insert into board_categories (type, board_id) values (' Geography ', 44);
insert into board_categories (type, board_id) values (' English ', 27);
insert into board_categories (type, board_id) values (' Macroeconomics ', 54);
insert into board_categories (type, board_id) values (' German ', 100);
insert into board_categories (type, board_id) values (' Classics ', 31);
insert into board_categories (type, board_id) values (' Neuroscience ', 87);
insert into board_categories (type, board_id) values (' Politics ', 7);
insert into board_categories (type, board_id) values (' Cell Biology ', 15);
insert into board_categories (type, board_id) values (' Psychology', 24);
insert into board_categories (type, board_id) values (' Quantum Physics ', 20);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 57);
insert into board_categories (type, board_id) values (' German ', 67);
insert into board_categories (type, board_id) values (' Microbiology ', 82);
insert into board_categories (type, board_id) values (' Science ', 78);
insert into board_categories (type, board_id) values (' Animal Biology ', 80);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 19);
insert into board_categories (type, board_id) values (' Literature ', 26);
insert into board_categories (type, board_id) values (' Microbiology ', 15);
insert into board_categories (type, board_id) values (' Macroeconomics ', 90);
insert into board_categories (type, board_id) values (' Art ', 44);
insert into board_categories (type, board_id) values (' Classics ', 50);
insert into board_categories (type, board_id) values (' Macroeconomics ', 60);
insert into board_categories (type, board_id) values (' Psychology', 67);
insert into board_categories (type, board_id) values (' Anthropology ', 13);
insert into board_categories (type, board_id) values (' History ', 41);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 71);
insert into board_categories (type, board_id) values (' German ', 88);
insert into board_categories (type, board_id) values (' Quantum Physics ', 95);
insert into board_categories (type, board_id) values (' Business ', 89);
insert into board_categories (type, board_id) values (' Anthropology ', 73);
insert into board_categories (type, board_id) values (' Astrophysics ', 3);
insert into board_categories (type, board_id) values (' Politics ', 75);
insert into board_categories (type, board_id) values (' Linguistics ', 30);
insert into board_categories (type, board_id) values (' English ', 65);
insert into board_categories (type, board_id) values (' Arabic ', 60);
insert into board_categories (type, board_id) values (' Literature ', 87);
insert into board_categories (type, board_id) values (' Geography ', 2);
insert into board_categories (type, board_id) values (' Literature ', 68);
insert into board_categories (type, board_id) values (' Astronomy ', 12);
insert into board_categories (type, board_id) values (' Astrophysics ', 11);
insert into board_categories (type, board_id) values (' Quantum Physics ', 22);
insert into board_categories (type, board_id) values (' Language ', 63);
insert into board_categories (type, board_id) values (' Russian ', 83);
insert into board_categories (type, board_id) values (' Arabic ', 85);
insert into board_categories (type, board_id) values (' Literature ', 100);
insert into board_categories (type, board_id) values (' Business ', 97);
insert into board_categories (type, board_id) values (' Art ', 79);
insert into board_categories (type, board_id) values (' Astrophysics ', 57);
insert into board_categories (type, board_id) values (' Marine Biology ', 12);
insert into board_categories (type, board_id) values (' Microbiology ', 30);
insert into board_categories (type, board_id) values (' Sociology ', 31);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 78);
insert into board_categories (type, board_id) values (' Classics ', 80);
insert into board_categories (type, board_id) values (' Mandarin ', 41);
insert into board_categories (type, board_id) values (' Neuroscience ', 95);
insert into board_categories (type, board_id) values (' Classics ', 95);
insert into board_categories (type, board_id) values (' French ', 79);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 24);
insert into board_categories (type, board_id) values (' Psychology', 78);
insert into board_categories (type, board_id) values (' Microeconomics ', 12);
insert into board_categories (type, board_id) values (' Russian ', 60);
insert into board_categories (type, board_id) values (' Microeconomics ', 20);
insert into board_categories (type, board_id) values (' Economics ', 99);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 95);
insert into board_categories (type, board_id) values (' Arabic ', 20);
insert into board_categories (type, board_id) values (' Physiology ', 100);
insert into board_categories (type, board_id) values (' Arabic ', 31);
insert into board_categories (type, board_id) values (' Art ', 2);
insert into board_categories (type, board_id) values (' Neuroscience ', 84);
insert into board_categories (type, board_id) values (' History ', 21);
insert into board_categories (type, board_id) values (' Microeconomics ', 74);
insert into board_categories (type, board_id) values (' Astronomy ', 17);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 59);
insert into board_categories (type, board_id) values (' Sociology ', 34);
insert into board_categories (type, board_id) values (' Neuropsychology ', 50);
insert into board_categories (type, board_id) values (' Geology ', 56);
insert into board_categories (type, board_id) values (' History ', 14);
insert into board_categories (type, board_id) values (' Mandarin ', 68);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 20);
insert into board_categories (type, board_id) values (' Economics ', 59);
insert into board_categories (type, board_id) values (' Business ', 55);
insert into board_categories (type, board_id) values (' History ', 74);
insert into board_categories (type, board_id) values (' Neuroscience ', 33);
insert into board_categories (type, board_id) values (' History ', 52);
insert into board_categories (type, board_id) values (' Geophysics ', 77);
insert into board_categories (type, board_id) values (' Astronomy ', 30);
insert into board_categories (type, board_id) values (' Linguistics ', 89);
insert into board_categories (type, board_id) values (' French ', 24);
insert into board_categories (type, board_id) values (' Art ', 46);
insert into board_categories (type, board_id) values (' Sociology ', 77);
insert into board_categories (type, board_id) values (' Business ', 52);
insert into board_categories (type, board_id) values (' Macroeconomics ', 28);
insert into board_categories (type, board_id) values (' Mandarin ', 85);
insert into board_categories (type, board_id) values (' Politics ', 46);
insert into board_categories (type, board_id) values (' Neuroscience ', 1);
insert into board_categories (type, board_id) values (' Neuropsychology ', 46);
insert into board_categories (type, board_id) values (' French ', 65);
insert into board_categories (type, board_id) values (' Geology ', 46);
insert into board_categories (type, board_id) values (' Science ', 95);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 36);
insert into board_categories (type, board_id) values (' Geography ', 22);
insert into board_categories (type, board_id) values (' Physiology ', 21);
insert into board_categories (type, board_id) values (' Astrophysics ', 65);
insert into board_categories (type, board_id) values (' Economics ', 81);
insert into board_categories (type, board_id) values (' German ', 68);
insert into board_categories (type, board_id) values (' Politics ', 20);
insert into board_categories (type, board_id) values (' French ', 2);
insert into board_categories (type, board_id) values (' Art ', 33);
insert into board_categories (type, board_id) values (' Philosophy ', 35);
insert into board_categories (type, board_id) values (' Business ', 88);
insert into board_categories (type, board_id) values (' Sociology ', 91);
insert into board_categories (type, board_id) values (' Geography ', 52);
insert into board_categories (type, board_id) values (' Russian ', 98);
insert into board_categories (type, board_id) values (' Astrophysics ', 86);
insert into board_categories (type, board_id) values (' Animal Biology ', 81);
insert into board_categories (type, board_id) values (' Mandarin ', 27);
insert into board_categories (type, board_id) values (' Neuropsychology ', 51);
insert into board_categories (type, board_id) values (' Psychology', 26);
insert into board_categories (type, board_id) values (' Marine Biology ', 4);
insert into board_categories (type, board_id) values (' Cell Biology ', 41);
insert into board_categories (type, board_id) values (' Philosophy ', 99);
insert into board_categories (type, board_id) values (' Microbiology ', 47);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 86);
insert into board_categories (type, board_id) values (' French ', 43);
insert into board_categories (type, board_id) values (' Philosophy ', 86);
insert into board_categories (type, board_id) values (' Macroeconomics ', 32);
insert into board_categories (type, board_id) values (' Language ', 65);
insert into board_categories (type, board_id) values (' French ', 22);
insert into board_categories (type, board_id) values (' Geophysics ', 57);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 64);
insert into board_categories (type, board_id) values (' Anthropology ', 56);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 63);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 39);
insert into board_categories (type, board_id) values (' French ', 94);
insert into board_categories (type, board_id) values (' Microbiology ', 84);
insert into board_categories (type, board_id) values (' Anthropology ', 93);
insert into board_categories (type, board_id) values (' Science ', 33);
insert into board_categories (type, board_id) values (' Arabic ', 26);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 49);
insert into board_categories (type, board_id) values (' Quantum Physics ', 37);
insert into board_categories (type, board_id) values (' Politics ', 53);
insert into board_categories (type, board_id) values (' Quantum Physics ', 30);
insert into board_categories (type, board_id) values (' Neuropsychology ', 91);
insert into board_categories (type, board_id) values (' Linguistics ', 63);
insert into board_categories (type, board_id) values (' French ', 40);
insert into board_categories (type, board_id) values (' Neuroscience ', 91);
insert into board_categories (type, board_id) values (' Psychology', 21);
insert into board_categories (type, board_id) values (' Science ', 44);
insert into board_categories (type, board_id) values (' Astronomy ', 79);
insert into board_categories (type, board_id) values (' Geography ', 24);
insert into board_categories (type, board_id) values (' Mathematics ', 95);
insert into board_categories (type, board_id) values (' Economics ', 25);
insert into board_categories (type, board_id) values (' Geophysics ', 7);
insert into board_categories (type, board_id) values (' Microeconomics ', 10);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 24);
insert into board_categories (type, board_id) values (' Sociology ', 91);
insert into board_categories (type, board_id) values (' Macroeconomics ', 59);
insert into board_categories (type, board_id) values (' Philosophy ', 49);
insert into board_categories (type, board_id) values (' Classics ', 71);
insert into board_categories (type, board_id) values (' Mandarin ', 44);
insert into board_categories (type, board_id) values (' English ', 48);
insert into board_categories (type, board_id) values (' German ', 26);
insert into board_categories (type, board_id) values (' Arabic ', 73);
insert into board_categories (type, board_id) values (' Geography ', 28);
insert into board_categories (type, board_id) values (' French ', 18);
insert into board_categories (type, board_id) values (' Art ', 77);
insert into board_categories (type, board_id) values (' Psychology', 57);
insert into board_categories (type, board_id) values (' Arabic ', 54);
insert into board_categories (type, board_id) values (' Psychology', 32);
insert into board_categories (type, board_id) values (' Microeconomics ', 49);
insert into board_categories (type, board_id) values (' Ancient History ', 7);
insert into board_categories (type, board_id) values (' Science ', 68);
insert into board_categories (type, board_id) values (' Quantum Physics ', 19);
insert into board_categories (type, board_id) values (' French ', 17);
insert into board_categories (type, board_id) values (' Language ', 46);
insert into board_categories (type, board_id) values (' Anthropology ', 41);
insert into board_categories (type, board_id) values (' Neuroscience ', 92);
insert into board_categories (type, board_id) values (' Language ', 72);
insert into board_categories (type, board_id) values (' Economics ', 62);
insert into board_categories (type, board_id) values (' Microbiology ', 60);
insert into board_categories (type, board_id) values (' Philosophy ', 59);
insert into board_categories (type, board_id) values (' Neuropsychology ', 65);
insert into board_categories (type, board_id) values (' Linguistics ', 49);
insert into board_categories (type, board_id) values (' Astronomy ', 82);
insert into board_categories (type, board_id) values (' Business ', 18);
insert into board_categories (type, board_id) values (' Macroeconomics ', 73);
insert into board_categories (type, board_id) values (' Anthropology ', 39);
insert into board_categories (type, board_id) values (' Classics ', 20);
insert into board_categories (type, board_id) values (' Microeconomics ', 35);
insert into board_categories (type, board_id) values (' Economics ', 7);
insert into board_categories (type, board_id) values (' Microbiology ', 18);
insert into board_categories (type, board_id) values (' Psychology', 85);
insert into board_categories (type, board_id) values (' Philosophy ', 54);
insert into board_categories (type, board_id) values (' Ancient History ', 75);
insert into board_categories (type, board_id) values (' Russian ', 82);
insert into board_categories (type, board_id) values (' Geology ', 81);
insert into board_categories (type, board_id) values (' Geography ', 82);
insert into board_categories (type, board_id) values (' Microeconomics ', 69);
insert into board_categories (type, board_id) values (' Microeconomics ', 66);
insert into board_categories (type, board_id) values (' Microeconomics ', 53);
insert into board_categories (type, board_id) values (' Macroeconomics ', 69);
insert into board_categories (type, board_id) values (' Classics ', 79);
insert into board_categories (type, board_id) values (' Marine Biology ', 47);
insert into board_categories (type, board_id) values (' Geology ', 87);
insert into board_categories (type, board_id) values (' Language ', 48);
insert into board_categories (type, board_id) values (' History ', 94);
insert into board_categories (type, board_id) values (' Art ', 100);
insert into board_categories (type, board_id) values (' Mandarin ', 2);
insert into board_categories (type, board_id) values (' Geology ', 65);
insert into board_categories (type, board_id) values (' Ancient History ', 79);
insert into board_categories (type, board_id) values (' Psychology', 64);
insert into board_categories (type, board_id) values (' Cell Biology ', 50);
insert into board_categories (type, board_id) values (' Geology ', 41);
insert into board_categories (type, board_id) values (' Physiology ', 30);
insert into board_categories (type, board_id) values (' Mandarin ', 25);
insert into board_categories (type, board_id) values (' Astrophysics ', 6);
insert into board_categories (type, board_id) values (' Business ', 40);
insert into board_categories (type, board_id) values (' Astrophysics ', 72);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 41);
insert into board_categories (type, board_id) values (' Physics ', 74);
insert into board_categories (type, board_id) values (' Macroeconomics ', 90);
insert into board_categories (type, board_id) values (' Mandarin ', 56);
insert into board_categories (type, board_id) values (' Physiology ', 24);
insert into board_categories (type, board_id) values (' German ', 95);
insert into board_categories (type, board_id) values (' Cell Biology ', 75);
insert into board_categories (type, board_id) values (' Linguistics ', 10);
insert into board_categories (type, board_id) values (' Astronomy ', 27);
insert into board_categories (type, board_id) values (' Language ', 57);
insert into board_categories (type, board_id) values (' Mandarin ', 49);
insert into board_categories (type, board_id) values (' Geology ', 37);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 26);
insert into board_categories (type, board_id) values (' Sociology ', 5);
insert into board_categories (type, board_id) values (' Geology ', 54);
insert into board_categories (type, board_id) values (' Microeconomics ', 66);
insert into board_categories (type, board_id) values (' Mathematics ', 70);
insert into board_categories (type, board_id) values (' French ', 3);
insert into board_categories (type, board_id) values (' Macroeconomics ', 57);
insert into board_categories (type, board_id) values (' Anthropology ', 17);
insert into board_categories (type, board_id) values (' Sociology ', 9);
insert into board_categories (type, board_id) values (' Mathematics ', 6);
insert into board_categories (type, board_id) values (' Neuroscience ', 24);
insert into board_categories (type, board_id) values (' Arabic ', 53);
insert into board_categories (type, board_id) values (' Geophysics ', 23);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 41);
insert into board_categories (type, board_id) values (' Politics ', 17);
insert into board_categories (type, board_id) values (' Ancient History ', 60);
insert into board_categories (type, board_id) values (' Astrophysics ', 14);
insert into board_categories (type, board_id) values (' Language ', 72);
insert into board_categories (type, board_id) values (' Classics ', 4);
insert into board_categories (type, board_id) values (' Anthropology ', 51);
insert into board_categories (type, board_id) values (' Politics ', 87);
insert into board_categories (type, board_id) values (' Sociology ', 3);
insert into board_categories (type, board_id) values (' Business ', 98);
insert into board_categories (type, board_id) values (' Politics ', 35);
insert into board_categories (type, board_id) values (' Microbiology ', 67);
insert into board_categories (type, board_id) values (' Ancient History ', 11);
insert into board_categories (type, board_id) values (' Geography ', 24);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 7);
insert into board_categories (type, board_id) values (' History ', 29);
insert into board_categories (type, board_id) values (' Mandarin ', 31);
insert into board_categories (type, board_id) values (' Microbiology ', 58);
insert into board_categories (type, board_id) values (' Politics ', 37);
insert into board_categories (type, board_id) values (' Science ', 10);
insert into board_categories (type, board_id) values (' Philosophy ', 11);
insert into board_categories (type, board_id) values (' Cell Biology ', 36);
insert into board_categories (type, board_id) values (' Physics ', 61);
insert into board_categories (type, board_id) values (' Language ', 97);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 69);
insert into board_categories (type, board_id) values (' Arabic ', 97);
insert into board_categories (type, board_id) values (' French ', 52);
insert into board_categories (type, board_id) values (' Microeconomics ', 100);
insert into board_categories (type, board_id) values (' Classics ', 95);
insert into board_categories (type, board_id) values (' Animal Biology ', 58);
insert into board_categories (type, board_id) values (' Economics ', 85);
insert into board_categories (type, board_id) values (' Microeconomics ', 82);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 40);
insert into board_categories (type, board_id) values (' Geology ', 43);
insert into board_categories (type, board_id) values (' Animal Biology ', 36);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 70);
insert into board_categories (type, board_id) values (' Animal Biology ', 96);
insert into board_categories (type, board_id) values (' German ', 91);
insert into board_categories (type, board_id) values (' Ancient History ', 14);
insert into board_categories (type, board_id) values (' Astrophysics ', 17);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 13);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 56);
insert into board_categories (type, board_id) values (' Microeconomics ', 26);
insert into board_categories (type, board_id) values (' Language ', 20);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 56);
insert into board_categories (type, board_id) values (' Macroeconomics ', 19);
insert into board_categories (type, board_id) values (' Quantum Physics ', 89);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 20);
insert into board_categories (type, board_id) values (' Cell Biology ', 42);
insert into board_categories (type, board_id) values (' Marine Biology ', 88);
insert into board_categories (type, board_id) values (' Classics ', 33);
insert into board_categories (type, board_id) values (' German ', 45);
insert into board_categories (type, board_id) values (' Linguistics ', 96);
insert into board_categories (type, board_id) values (' Philosophy ', 30);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 84);
insert into board_categories (type, board_id) values (' Linguistics ', 74);
insert into board_categories (type, board_id) values (' German ', 22);
insert into board_categories (type, board_id) values (' English ', 41);
insert into board_categories (type, board_id) values (' Marine Biology ', 45);
insert into board_categories (type, board_id) values (' Anthropology ', 19);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 88);
insert into board_categories (type, board_id) values (' Literature ', 96);
insert into board_categories (type, board_id) values (' Marine Biology ', 88);
insert into board_categories (type, board_id) values (' Ancient History ', 84);
insert into board_categories (type, board_id) values (' Russian ', 57);
insert into board_categories (type, board_id) values (' English ', 63);
insert into board_categories (type, board_id) values (' Physics ', 50);
insert into board_categories (type, board_id) values (' Psychology', 42);
insert into board_categories (type, board_id) values (' Business ', 24);
insert into board_categories (type, board_id) values (' Marine Biology ', 44);
insert into board_categories (type, board_id) values (' Philosophy ', 41);
insert into board_categories (type, board_id) values (' Quantum Physics ', 10);
insert into board_categories (type, board_id) values (' Animal Biology ', 30);
insert into board_categories (type, board_id) values (' Politics ', 83);
insert into board_categories (type, board_id) values (' Classics ', 2);
insert into board_categories (type, board_id) values (' Literature ', 65);
insert into board_categories (type, board_id) values (' History ', 44);
insert into board_categories (type, board_id) values (' Astronomy ', 72);
insert into board_categories (type, board_id) values (' Mandarin ', 48);
insert into board_categories (type, board_id) values (' Sociology ', 24);
insert into board_categories (type, board_id) values (' Astrophysics ', 11);
insert into board_categories (type, board_id) values (' History ', 92);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 95);
insert into board_categories (type, board_id) values (' Astrophysics ', 58);
insert into board_categories (type, board_id) values (' Ancient History ', 2);
insert into board_categories (type, board_id) values (' Classics ', 13);
insert into board_categories (type, board_id) values (' Geology ', 79);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 17);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 32);
insert into board_categories (type, board_id) values (' Astronomy ', 52);
insert into board_categories (type, board_id) values (' Anthropology ', 41);
insert into board_categories (type, board_id) values (' Anthropology ', 23);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 78);
insert into board_categories (type, board_id) values (' Astronomy ', 90);
insert into board_categories (type, board_id) values (' Quantum Physics ', 66);
insert into board_categories (type, board_id) values (' Microeconomics ', 28);
insert into board_categories (type, board_id) values (' Anthropology ', 79);
insert into board_categories (type, board_id) values (' Physiology ', 43);
insert into board_categories (type, board_id) values (' Quantum Physics ', 61);
insert into board_categories (type, board_id) values (' Arabic ', 92);
insert into board_categories (type, board_id) values (' French ', 27);
insert into board_categories (type, board_id) values (' Geophysics ', 61);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 9);
insert into board_categories (type, board_id) values (' Anthropology ', 30);
insert into board_categories (type, board_id) values (' Art ', 42);
insert into board_categories (type, board_id) values (' Philosophy ', 28);
insert into board_categories (type, board_id) values (' Language ', 96);
insert into board_categories (type, board_id) values (' English ', 75);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 98);
insert into board_categories (type, board_id) values (' Cell Biology ', 71);
insert into board_categories (type, board_id) values (' Ancient History ', 15);
insert into board_categories (type, board_id) values (' Mathematics ', 37);
insert into board_categories (type, board_id) values (' Neuroscience ', 6);
insert into board_categories (type, board_id) values (' Astrophysics ', 21);
insert into board_categories (type, board_id) values (' Geology ', 32);
insert into board_categories (type, board_id) values (' Quantum Physics ', 46);
insert into board_categories (type, board_id) values (' Astronomy ', 55);
insert into board_categories (type, board_id) values (' Psychology', 74);
insert into board_categories (type, board_id) values (' History ', 38);
insert into board_categories (type, board_id) values (' Philosophy ', 14);
insert into board_categories (type, board_id) values (' Physiology ', 73);
insert into board_categories (type, board_id) values (' Geology ', 18);
insert into board_categories (type, board_id) values (' Russian ', 42);
insert into board_categories (type, board_id) values (' Arabic ', 60);
insert into board_categories (type, board_id) values (' Geology ', 65);
insert into board_categories (type, board_id) values (' Physics ', 71);
insert into board_categories (type, board_id) values (' Cell Biology ', 87);
insert into board_categories (type, board_id) values (' French ', 88);
insert into board_categories (type, board_id) values (' Spanish ', 13);
insert into board_categories (type, board_id) values (' Language ', 95);
insert into board_categories (type, board_id) values (' Mathematics ', 54);
insert into board_categories (type, board_id) values (' Economics ', 41);
insert into board_categories (type, board_id) values (' Anthropology ', 79);
insert into board_categories (type, board_id) values (' Business ', 75);
insert into board_categories (type, board_id) values (' Sociology ', 89);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 16);
insert into board_categories (type, board_id) values (' Sociology ', 64);
insert into board_categories (type, board_id) values (' Anthropology ', 86);
insert into board_categories (type, board_id) values (' Microeconomics ', 66);
insert into board_categories (type, board_id) values (' Russian ', 84);
insert into board_categories (type, board_id) values (' Astrophysics ', 87);
insert into board_categories (type, board_id) values (' Marine Biology ', 2);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 16);
insert into board_categories (type, board_id) values (' Sociology ', 41);
insert into board_categories (type, board_id) values (' Sociology ', 32);
insert into board_categories (type, board_id) values (' Classics ', 8);
insert into board_categories (type, board_id) values (' Business ', 60);
insert into board_categories (type, board_id) values (' Microeconomics ', 97);
insert into board_categories (type, board_id) values (' Geography ', 90);
insert into board_categories (type, board_id) values (' Cell Biology ', 53);
insert into board_categories (type, board_id) values (' Physiology ', 99);
insert into board_categories (type, board_id) values (' History ', 62);
insert into board_categories (type, board_id) values (' Sociology ', 41);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 68);
insert into board_categories (type, board_id) values (' Geology ', 38);
insert into board_categories (type, board_id) values (' Astrophysics ', 27);
insert into board_categories (type, board_id) values (' Anthropology ', 41);
insert into board_categories (type, board_id) values (' Art ', 95);
insert into board_categories (type, board_id) values (' Art ', 49);
insert into board_categories (type, board_id) values (' Art ', 46);
insert into board_categories (type, board_id) values (' Geophysics ', 56);
insert into board_categories (type, board_id) values (' Astrophysics ', 77);
insert into board_categories (type, board_id) values (' Literature ', 5);
insert into board_categories (type, board_id) values (' Mathematics ', 27);
insert into board_categories (type, board_id) values (' Neuropsychology ', 19);
insert into board_categories (type, board_id) values (' Microbiology ', 22);
insert into board_categories (type, board_id) values (' Animal Biology ', 99);
insert into board_categories (type, board_id) values (' Business ', 80);
insert into board_categories (type, board_id) values (' Animal Biology ', 56);
insert into board_categories (type, board_id) values (' Astrophysics ', 28);
insert into board_categories (type, board_id) values (' Cell Biology ', 89);
insert into board_categories (type, board_id) values (' Macroeconomics ', 1);
insert into board_categories (type, board_id) values (' Marine Biology ', 75);
insert into board_categories (type, board_id) values (' Politics ', 58);
insert into board_categories (type, board_id) values (' Spanish ', 61);
insert into board_categories (type, board_id) values (' Ancient History ', 11);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 57);
insert into board_categories (type, board_id) values (' Literature ', 1);
insert into board_categories (type, board_id) values (' Anthropology ', 11);
insert into board_categories (type, board_id) values (' Russian ', 35);
insert into board_categories (type, board_id) values (' Mathematics ', 54);
insert into board_categories (type, board_id) values (' Business ', 35);
insert into board_categories (type, board_id) values (' Quantum Physics ', 49);
insert into board_categories (type, board_id) values (' Science ', 11);
insert into board_categories (type, board_id) values (' Economics ', 35);
insert into board_categories (type, board_id) values (' Psychology', 69);
insert into board_categories (type, board_id) values (' Arabic ', 15);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 69);
insert into board_categories (type, board_id) values (' Sociology ', 68);
insert into board_categories (type, board_id) values (' Animal Biology ', 11);
insert into board_categories (type, board_id) values (' Art ', 29);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 9);
insert into board_categories (type, board_id) values (' Mathematics ', 38);
insert into board_categories (type, board_id) values (' Microeconomics ', 62);
insert into board_categories (type, board_id) values (' Physics ', 30);
insert into board_categories (type, board_id) values (' Russian ', 89);
insert into board_categories (type, board_id) values (' Mandarin ', 10);
insert into board_categories (type, board_id) values (' Anthropology ', 84);
insert into board_categories (type, board_id) values (' Economics ', 2);
insert into board_categories (type, board_id) values (' Physics ', 71);
insert into board_categories (type, board_id) values (' Arabic ', 71);
insert into board_categories (type, board_id) values (' Microeconomics ', 85);
insert into board_categories (type, board_id) values (' Geology ', 87);
insert into board_categories (type, board_id) values (' Astronomy ', 52);
insert into board_categories (type, board_id) values (' Geophysics ', 7);
insert into board_categories (type, board_id) values (' German ', 60);
insert into board_categories (type, board_id) values (' Spanish ', 58);
insert into board_categories (type, board_id) values (' Mandarin ', 63);
insert into board_categories (type, board_id) values (' Literature ', 60);
insert into board_categories (type, board_id) values (' History ', 27);
insert into board_categories (type, board_id) values (' Science ', 48);
insert into board_categories (type, board_id) values (' Classics ', 63);
insert into board_categories (type, board_id) values (' Neuropsychology ', 89);
insert into board_categories (type, board_id) values (' Anthropology ', 81);
insert into board_categories (type, board_id) values (' Anthropology ', 46);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 14);
insert into board_categories (type, board_id) values (' Business ', 41);
insert into board_categories (type, board_id) values (' Russian ', 89);
insert into board_categories (type, board_id) values (' Business ', 72);
insert into board_categories (type, board_id) values (' Astrophysics ', 8);
insert into board_categories (type, board_id) values (' French ', 93);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 48);
insert into board_categories (type, board_id) values (' Geology ', 95);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 90);
insert into board_categories (type, board_id) values (' English ', 90);
insert into board_categories (type, board_id) values (' French ', 26);
insert into board_categories (type, board_id) values (' Geophysics ', 49);
insert into board_categories (type, board_id) values (' Neuropsychology ', 40);
insert into board_categories (type, board_id) values (' Neuroscience ', 10);
insert into board_categories (type, board_id) values (' Neuropsychology ', 1);
insert into board_categories (type, board_id) values (' Art ', 37);
insert into board_categories (type, board_id) values (' Art ', 25);
insert into board_categories (type, board_id) values (' Mandarin ', 29);
insert into board_categories (type, board_id) values (' Physiology ', 91);
insert into board_categories (type, board_id) values (' German ', 87);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 57);
insert into board_categories (type, board_id) values (' Russian ', 27);
insert into board_categories (type, board_id) values (' Physiology ', 79);
insert into board_categories (type, board_id) values (' Astrophysics ', 100);
insert into board_categories (type, board_id) values (' Mathematics ', 51);
insert into board_categories (type, board_id) values (' Physiology ', 86);
insert into board_categories (type, board_id) values (' Anthropology ', 11);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 12);
insert into board_categories (type, board_id) values (' Classics ', 79);
insert into board_categories (type, board_id) values (' Geophysics ', 58);
insert into board_categories (type, board_id) values (' Science ', 26);
insert into board_categories (type, board_id) values (' Classics ', 97);
insert into board_categories (type, board_id) values (' Astronomy ', 57);
insert into board_categories (type, board_id) values (' Politics ', 76);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 39);
insert into board_categories (type, board_id) values (' Macroeconomics ', 23);
insert into board_categories (type, board_id) values (' Art ', 39);
insert into board_categories (type, board_id) values (' Science ', 62);
insert into board_categories (type, board_id) values (' English ', 28);
insert into board_categories (type, board_id) values (' Quantum Physics ', 35);
insert into board_categories (type, board_id) values (' Cell Biology ', 51);
insert into board_categories (type, board_id) values (' Physics ', 6);
insert into board_categories (type, board_id) values (' Spanish ', 72);
insert into board_categories (type, board_id) values (' Language ', 25);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 71);
insert into board_categories (type, board_id) values (' Classics ', 15);
insert into board_categories (type, board_id) values (' Neuropsychology ', 70);
insert into board_categories (type, board_id) values (' Classics ', 76);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 46);
insert into board_categories (type, board_id) values (' Geography ', 23);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 67);
insert into board_categories (type, board_id) values (' Cell Biology ', 57);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 28);
insert into board_categories (type, board_id) values (' Economics ', 9);
insert into board_categories (type, board_id) values (' Ancient History ', 90);
insert into board_categories (type, board_id) values (' Marine Biology ', 36);
insert into board_categories (type, board_id) values (' Microeconomics ', 55);
insert into board_categories (type, board_id) values (' Psychology', 3);
insert into board_categories (type, board_id) values (' Mathematics ', 98);
insert into board_categories (type, board_id) values (' Marine Biology ', 27);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 21);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 53);
insert into board_categories (type, board_id) values (' Language ', 62);
insert into board_categories (type, board_id) values (' Anthropology ', 12);
insert into board_categories (type, board_id) values (' Language ', 90);
insert into board_categories (type, board_id) values (' Economics ', 11);
insert into board_categories (type, board_id) values (' French ', 16);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 76);
insert into board_categories (type, board_id) values (' Literature ', 59);
insert into board_categories (type, board_id) values (' Astrophysics ', 91);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 28);
insert into board_categories (type, board_id) values (' Cell Biology ', 76);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 94);
insert into board_categories (type, board_id) values (' Geophysics ', 22);
insert into board_categories (type, board_id) values (' Geology ', 82);
insert into board_categories (type, board_id) values (' Anthropology ', 13);
insert into board_categories (type, board_id) values (' Geology ', 36);
insert into board_categories (type, board_id) values (' Philosophy ', 67);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 81);
insert into board_categories (type, board_id) values (' Mandarin ', 52);
insert into board_categories (type, board_id) values (' Philosophy ', 66);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 83);
insert into board_categories (type, board_id) values (' Art ', 76);
insert into board_categories (type, board_id) values (' English ', 28);
insert into board_categories (type, board_id) values (' Science ', 38);
insert into board_categories (type, board_id) values (' Microeconomics ', 36);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 11);
insert into board_categories (type, board_id) values (' Economics ', 71);
insert into board_categories (type, board_id) values (' Spanish ', 17);
insert into board_categories (type, board_id) values (' Neuropsychology ', 56);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 65);
insert into board_categories (type, board_id) values (' Philosophy ', 22);
insert into board_categories (type, board_id) values (' Business ', 41);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 97);
insert into board_categories (type, board_id) values (' German ', 3);
insert into board_categories (type, board_id) values (' Language ', 91);
insert into board_categories (type, board_id) values (' Arabic ', 61);
insert into board_categories (type, board_id) values (' Macroeconomics ', 86);
insert into board_categories (type, board_id) values (' Business ', 17);
insert into board_categories (type, board_id) values (' Marine Biology ', 46);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 94);
insert into board_categories (type, board_id) values (' Language ', 32);
insert into board_categories (type, board_id) values (' Astrophysics ', 76);
insert into board_categories (type, board_id) values (' Economics ', 38);
insert into board_categories (type, board_id) values (' Business ', 35);
insert into board_categories (type, board_id) values (' Literature ', 54);
insert into board_categories (type, board_id) values (' Neuroscience ', 63);
insert into board_categories (type, board_id) values (' Physiology ', 91);
insert into board_categories (type, board_id) values (' Animal Biology ', 57);
insert into board_categories (type, board_id) values (' Politics ', 28);
insert into board_categories (type, board_id) values (' Art ', 70);
insert into board_categories (type, board_id) values (' Geology ', 7);
insert into board_categories (type, board_id) values (' Animal Biology ', 85);
insert into board_categories (type, board_id) values (' Neuroscience ', 10);
insert into board_categories (type, board_id) values (' Physiology ', 61);
insert into board_categories (type, board_id) values (' Linguistics ', 75);
insert into board_categories (type, board_id) values (' Neuropsychology ', 84);
insert into board_categories (type, board_id) values (' Russian ', 71);
insert into board_categories (type, board_id) values (' French ', 10);
insert into board_categories (type, board_id) values (' Physics ', 31);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 13);
insert into board_categories (type, board_id) values (' Philosophy ', 72);
insert into board_categories (type, board_id) values (' Philosophy ', 75);
insert into board_categories (type, board_id) values (' Astronomy ', 16);
insert into board_categories (type, board_id) values (' Russian ', 77);
insert into board_categories (type, board_id) values (' Astrophysics ', 56);
insert into board_categories (type, board_id) values (' Marine Biology ', 62);
insert into board_categories (type, board_id) values (' Geology ', 97);
insert into board_categories (type, board_id) values (' Business ', 85);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 95);
insert into board_categories (type, board_id) values (' Neuropsychology ', 85);
insert into board_categories (type, board_id) values (' Quantum Physics ', 83);
insert into board_categories (type, board_id) values (' Sociology ', 28);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 68);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 29);
insert into board_categories (type, board_id) values (' Psychology', 53);
insert into board_categories (type, board_id) values (' Science ', 86);
insert into board_categories (type, board_id) values (' Spanish ', 43);
insert into board_categories (type, board_id) values (' Geography ', 41);
insert into board_categories (type, board_id) values (' Microbiology ', 19);
insert into board_categories (type, board_id) values (' English ', 18);
insert into board_categories (type, board_id) values (' Cell Biology ', 96);
insert into board_categories (type, board_id) values (' Sociology ', 60);
insert into board_categories (type, board_id) values (' Arabic ', 84);
insert into board_categories (type, board_id) values (' Art ', 68);
insert into board_categories (type, board_id) values (' Psychology', 33);
insert into board_categories (type, board_id) values (' Neuropsychology ', 71);
insert into board_categories (type, board_id) values (' Neuropsychology ', 47);
insert into board_categories (type, board_id) values (' Economics ', 21);
insert into board_categories (type, board_id) values (' Art ', 23);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 71);
insert into board_categories (type, board_id) values (' Microbiology ', 58);
insert into board_categories (type, board_id) values (' Russian ', 24);
insert into board_categories (type, board_id) values (' Mathematics ', 74);
insert into board_categories (type, board_id) values (' Physics ', 88);
insert into board_categories (type, board_id) values (' Astronomy ', 31);
insert into board_categories (type, board_id) values (' Anthropology ', 1);
insert into board_categories (type, board_id) values (' Mathematics ', 31);
insert into board_categories (type, board_id) values (' French ', 89);
insert into board_categories (type, board_id) values (' Microeconomics ', 34);
insert into board_categories (type, board_id) values (' Astronomy ', 57);
insert into board_categories (type, board_id) values (' Economics ', 100);
insert into board_categories (type, board_id) values (' Arabic ', 3);
insert into board_categories (type, board_id) values (' Ancient History ', 38);
insert into board_categories (type, board_id) values (' Astronomy ', 42);
insert into board_categories (type, board_id) values (' Literature ', 72);
insert into board_categories (type, board_id) values (' Geophysics ', 8);
insert into board_categories (type, board_id) values (' Astrophysics ', 67);
insert into board_categories (type, board_id) values (' Astronomy ', 51);
insert into board_categories (type, board_id) values (' Physiology ', 91);
insert into board_categories (type, board_id) values (' Microbiology ', 49);
insert into board_categories (type, board_id) values (' Science ', 58);
insert into board_categories (type, board_id) values (' Physics ', 42);
insert into board_categories (type, board_id) values (' Language ', 9);
insert into board_categories (type, board_id) values (' Neuroscience ', 12);
insert into board_categories (type, board_id) values (' Art ', 43);
insert into board_categories (type, board_id) values (' Politics ', 3);
insert into board_categories (type, board_id) values (' Literature ', 27);
insert into board_categories (type, board_id) values (' Philosophy ', 96);
insert into board_categories (type, board_id) values (' Literature ', 92);
insert into board_categories (type, board_id) values (' French ', 86);
insert into board_categories (type, board_id) values (' Literature ', 71);
insert into board_categories (type, board_id) values (' Marine Biology ', 46);
insert into board_categories (type, board_id) values (' Politics ', 41);
insert into board_categories (type, board_id) values (' Astronomy ', 66);
insert into board_categories (type, board_id) values (' Arabic ', 34);
insert into board_categories (type, board_id) values (' History ', 60);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 85);
insert into board_categories (type, board_id) values (' Physiology ', 87);
insert into board_categories (type, board_id) values (' Cell Biology ', 79);
insert into board_categories (type, board_id) values (' Business ', 47);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 31);
insert into board_categories (type, board_id) values (' Politics ', 81);
insert into board_categories (type, board_id) values (' Art ', 50);
insert into board_categories (type, board_id) values (' Geophysics ', 64);
insert into board_categories (type, board_id) values (' Language ', 7);
insert into board_categories (type, board_id) values (' German ', 88);
insert into board_categories (type, board_id) values (' Literature ', 81);
insert into board_categories (type, board_id) values (' Microeconomics ', 17);
insert into board_categories (type, board_id) values (' Animal Biology ', 2);
insert into board_categories (type, board_id) values (' Cell Biology ', 87);
insert into board_categories (type, board_id) values (' Economics ', 19);
insert into board_categories (type, board_id) values (' Spanish ', 35);
insert into board_categories (type, board_id) values (' Politics ', 48);
insert into board_categories (type, board_id) values (' Business ', 69);
insert into board_categories (type, board_id) values (' Economics ', 49);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 77);
insert into board_categories (type, board_id) values (' Geography ', 28);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 40);
insert into board_categories (type, board_id) values (' Quantum Physics ', 18);
insert into board_categories (type, board_id) values (' Cell Biology ', 7);
insert into board_categories (type, board_id) values (' Macroeconomics ', 21);
insert into board_categories (type, board_id) values (' Microbiology ', 25);
insert into board_categories (type, board_id) values (' Business ', 43);
insert into board_categories (type, board_id) values (' Literature ', 26);
insert into board_categories (type, board_id) values (' French ', 64);
insert into board_categories (type, board_id) values (' Cell Biology ', 80);
insert into board_categories (type, board_id) values (' Geology ', 63);
insert into board_categories (type, board_id) values (' English ', 51);
insert into board_categories (type, board_id) values (' Neuroscience ', 72);
insert into board_categories (type, board_id) values (' Neuroscience ', 21);
insert into board_categories (type, board_id) values (' History ', 10);
insert into board_categories (type, board_id) values (' Neuropsychology ', 82);
insert into board_categories (type, board_id) values (' Neuroscience ', 91);
insert into board_categories (type, board_id) values (' Neuropsychology ', 59);
insert into board_categories (type, board_id) values (' Literature ', 80);
insert into board_categories (type, board_id) values (' Classics ', 40);
insert into board_categories (type, board_id) values (' Ancient History ', 78);
insert into board_categories (type, board_id) values (' Russian ', 62);
insert into board_categories (type, board_id) values (' Microeconomics ', 58);
insert into board_categories (type, board_id) values (' Language ', 13);
insert into board_categories (type, board_id) values (' English ', 73);
insert into board_categories (type, board_id) values (' German ', 98);
insert into board_categories (type, board_id) values (' Classics ', 47);
insert into board_categories (type, board_id) values (' History ', 39);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 90);
insert into board_categories (type, board_id) values (' Economics ', 60);
insert into board_categories (type, board_id) values (' Literature ', 37);
insert into board_categories (type, board_id) values (' Mandarin ', 73);
insert into board_categories (type, board_id) values (' Anthropology ', 34);
insert into board_categories (type, board_id) values (' Macroeconomics ', 89);
insert into board_categories (type, board_id) values (' Physiology ', 100);
insert into board_categories (type, board_id) values (' Neuroscience ', 99);
insert into board_categories (type, board_id) values (' Business ', 98);
insert into board_categories (type, board_id) values (' Geophysics ', 73);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 28);
insert into board_categories (type, board_id) values (' History ', 86);
insert into board_categories (type, board_id) values (' Ancient History ', 63);
insert into board_categories (type, board_id) values (' Physiology ', 1);
insert into board_categories (type, board_id) values (' Macroeconomics ', 76);
insert into board_categories (type, board_id) values (' Macroeconomics ', 82);
insert into board_categories (type, board_id) values (' Neuropsychology ', 90);
insert into board_categories (type, board_id) values (' German ', 45);
insert into board_categories (type, board_id) values (' Animal Biology ', 94);
insert into board_categories (type, board_id) values (' French ', 84);
insert into board_categories (type, board_id) values (' Geography ', 44);
insert into board_categories (type, board_id) values (' Anthropology ', 65);
insert into board_categories (type, board_id) values (' Astronomy ', 51);
insert into board_categories (type, board_id) values (' Astronomy ', 21);
insert into board_categories (type, board_id) values (' Microbiology ', 28);
insert into board_categories (type, board_id) values (' Politics ', 25);
insert into board_categories (type, board_id) values (' Neuropsychology ', 23);
insert into board_categories (type, board_id) values (' Russian ', 44);
insert into board_categories (type, board_id) values (' Language ', 57);
insert into board_categories (type, board_id) values (' Literature ', 73);
insert into board_categories (type, board_id) values (' Psychology', 43);
insert into board_categories (type, board_id) values (' Philosophy ', 72);
insert into board_categories (type, board_id) values (' Astronomy ', 38);
insert into board_categories (type, board_id) values (' German ', 35);
insert into board_categories (type, board_id) values (' Politics ', 93);
insert into board_categories (type, board_id) values (' Quantum Physics ', 92);
insert into board_categories (type, board_id) values (' English ', 91);
insert into board_categories (type, board_id) values (' Literature ', 18);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 45);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 100);
insert into board_categories (type, board_id) values (' Quantum Physics ', 36);
insert into board_categories (type, board_id) values (' Animal Biology ', 66);
insert into board_categories (type, board_id) values (' Astronomy ', 26);
insert into board_categories (type, board_id) values (' Arabic ', 57);
insert into board_categories (type, board_id) values (' Microbiology ', 84);
insert into board_categories (type, board_id) values (' Spanish ', 67);
insert into board_categories (type, board_id) values (' Language ', 37);
insert into board_categories (type, board_id) values (' Sociology ', 53);
insert into board_categories (type, board_id) values (' Neuropsychology ', 25);
insert into board_categories (type, board_id) values (' Geophysics ', 82);
insert into board_categories (type, board_id) values (' English ', 74);
insert into board_categories (type, board_id) values (' Cell Biology ', 37);
insert into board_categories (type, board_id) values (' Physiology ', 55);
insert into board_categories (type, board_id) values (' Politics ', 77);
insert into board_categories (type, board_id) values (' Linguistics ', 41);
insert into board_categories (type, board_id) values (' English ', 81);
insert into board_categories (type, board_id) values (' Anthropology ', 42);
insert into board_categories (type, board_id) values (' Economics ', 21);
insert into board_categories (type, board_id) values (' Geophysics ', 90);
insert into board_categories (type, board_id) values (' Microbiology ', 82);
insert into board_categories (type, board_id) values (' Neuropsychology ', 15);
insert into board_categories (type, board_id) values (' Russian ', 14);
insert into board_categories (type, board_id) values (' Philosophy ', 59);
insert into board_categories (type, board_id) values (' Cell Biology ', 55);
insert into board_categories (type, board_id) values (' Linguistics ', 94);
insert into board_categories (type, board_id) values (' Philosophy ', 54);
insert into board_categories (type, board_id) values (' Ancient History ', 7);
insert into board_categories (type, board_id) values (' Mandarin ', 21);
insert into board_categories (type, board_id) values (' Science ', 15);
insert into board_categories (type, board_id) values (' French ', 46);
insert into board_categories (type, board_id) values (' Literature ', 47);
insert into board_categories (type, board_id) values (' Linguistics ', 55);
insert into board_categories (type, board_id) values (' Mathematics ', 29);
insert into board_categories (type, board_id) values (' Arabic ', 7);
insert into board_categories (type, board_id) values (' English ', 40);
insert into board_categories (type, board_id) values (' Cell Biology ', 51);
insert into board_categories (type, board_id) values (' Linguistics ', 15);
insert into board_categories (type, board_id) values (' Marine Biology ', 14);
insert into board_categories (type, board_id) values (' Neuroscience ', 70);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 69);
insert into board_categories (type, board_id) values (' Neuropsychology ', 18);
insert into board_categories (type, board_id) values (' Microeconomics ', 84);
insert into board_categories (type, board_id) values (' German ', 66);
insert into board_categories (type, board_id) values (' Inorganic Chemistry ', 66);
insert into board_categories (type, board_id) values (' Psychology', 83);
insert into board_categories (type, board_id) values (' Art ', 6);
insert into board_categories (type, board_id) values (' Microeconomics ', 30);
insert into board_categories (type, board_id) values (' Astrophysics ', 55);
insert into board_categories (type, board_id) values (' Astronomy ', 39);
insert into board_categories (type, board_id) values (' Mathematics ', 15);
insert into board_categories (type, board_id) values (' Neuroscience ', 90);
insert into board_categories (type, board_id) values (' Neuropsychology ', 82);
insert into board_categories (type, board_id) values (' French ', 97);
insert into board_categories (type, board_id) values (' Ancient History ', 85);
insert into board_categories (type, board_id) values (' Language ', 73);
insert into board_categories (type, board_id) values (' Science ', 45);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 98);
insert into board_categories (type, board_id) values (' Spanish ', 62);
insert into board_categories (type, board_id) values (' Microeconomics ', 1);
insert into board_categories (type, board_id) values (' Neuropsychology ', 18);
insert into board_categories (type, board_id) values (' Geology ', 4);
insert into board_categories (type, board_id) values (' Marine Biology ', 40);
insert into board_categories (type, board_id) values (' Neuropsychology ', 94);
insert into board_categories (type, board_id) values (' Geography ', 45);
insert into board_categories (type, board_id) values (' Psychology', 48);
insert into board_categories (type, board_id) values (' Geophysics ', 2);
insert into board_categories (type, board_id) values (' Linguistics ', 30);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 35);
insert into board_categories (type, board_id) values (' Mandarin ', 99);
insert into board_categories (type, board_id) values (' Mandarin ', 86);
insert into board_categories (type, board_id) values (' Animal Biology ', 31);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 4);
insert into board_categories (type, board_id) values (' German ', 30);
insert into board_categories (type, board_id) values (' Ancient History ', 51);
insert into board_categories (type, board_id) values (' Science ', 90);
insert into board_categories (type, board_id) values (' Animal Biology ', 8);
insert into board_categories (type, board_id) values (' Politics ', 1);
insert into board_categories (type, board_id) values (' Literature ', 44);
insert into board_categories (type, board_id) values (' Science ', 38);
insert into board_categories (type, board_id) values (' Art ', 8);
insert into board_categories (type, board_id) values (' Arabic ', 3);
insert into board_categories (type, board_id) values (' Philosophy ', 28);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 85);
insert into board_categories (type, board_id) values (' Astronomy ', 3);
insert into board_categories (type, board_id) values (' Physics ', 59);
insert into board_categories (type, board_id) values (' Organic Chemistry ', 69);
insert into board_categories (type, board_id) values (' Physiology ', 86);
insert into board_categories (type, board_id) values (' Animal Biology ', 9);
insert into board_categories (type, board_id) values (' Philosophy ', 58);
insert into board_categories (type, board_id) values (' Astronomy ', 70);
insert into board_categories (type, board_id) values (' Language ', 30);
insert into board_categories (type, board_id) values (' Ancient History ', 72);
insert into board_categories (type, board_id) values (' Microbiology ', 27);
insert into board_categories (type, board_id) values (' Cell Biology ', 51);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 35);
insert into board_categories (type, board_id) values (' Art ', 67);
insert into board_categories (type, board_id) values (' Neuroscience ', 19);
insert into board_categories (type, board_id) values (' Astronomy ', 57);
insert into board_categories (type, board_id) values (' Physics ', 42);
insert into board_categories (type, board_id) values (' Ancient History ', 67);
insert into board_categories (type, board_id) values (' Cognitive Psychology ', 13);
insert into board_categories (type, board_id) values (' Animal Biology ', 14);
insert into board_categories (type, board_id) values (' Arabic ', 21);
insert into board_categories (type, board_id) values (' Behavioural Psychology ', 10);
insert into board_categories (type, board_id) values (' Geography ', 31);
insert into board_categories (type, board_id) values (' Mandarin ', 23);
insert into board_categories (type, board_id) values (' Anthropology ', 1);
insert into board_categories (type, board_id) values (' Geology ', 32);
insert into board_categories (type, board_id) values (' Cell Biology ', 54);
insert into board_categories (type, board_id) values (' Russian ', 18);
