insert into resource_categories (type, resource_id) values ('TSS', 110);
insert into resource_categories (type, resource_id) values ('WGA', 321);
insert into resource_categories (type, resource_id) values ('PDM', 604);
insert into resource_categories (type, resource_id) values ('HCP', 368);
insert into resource_categories (type, resource_id) values ('JDE One World', 904);
insert into resource_categories (type, resource_id) values ('Overcome Objections', 275);
insert into resource_categories (type, resource_id) values ('NMON', 174);
insert into resource_categories (type, resource_id) values ('Case Management', 14);
insert into resource_categories (type, resource_id) values ('Software Design', 477);
insert into resource_categories (type, resource_id) values ('MCH', 673);
insert into resource_categories (type, resource_id) values ('Long-term Care', 463);
insert into resource_categories (type, resource_id) values ('Foreign Trade Zone', 898);
insert into resource_categories (type, resource_id) values ('TDM', 52);
insert into resource_categories (type, resource_id) values ('Bookkeeping', 395);
insert into resource_categories (type, resource_id) values ('IBM Certified', 225);
insert into resource_categories (type, resource_id) values ('Federal Law Enforcement', 815);
insert into resource_categories (type, resource_id) values ('CISSP', 331);
insert into resource_categories (type, resource_id) values ('Acute Care', 682);
insert into resource_categories (type, resource_id) values ('Eggs', 258);
insert into resource_categories (type, resource_id) values ('CPCU', 364);
insert into resource_categories (type, resource_id) values ('GNU', 229);
insert into resource_categories (type, resource_id) values ('Ministry Of Defence', 470);
insert into resource_categories (type, resource_id) values ('PPDS', 865);
insert into resource_categories (type, resource_id) values ('Microsoft Dynamics SL', 807);
insert into resource_categories (type, resource_id) values ('Content Strategy', 439);
insert into resource_categories (type, resource_id) values ('Lyris ListManager', 440);
insert into resource_categories (type, resource_id) values ('Kayak', 628);
insert into resource_categories (type, resource_id) values ('Social Services', 261);
insert into resource_categories (type, resource_id) values ('Private Events', 388);
insert into resource_categories (type, resource_id) values ('Pulse Oximetry', 688);
insert into resource_categories (type, resource_id) values ('Tiles', 643);
insert into resource_categories (type, resource_id) values ('Allergy', 288);
insert into resource_categories (type, resource_id) values ('LCD', 919);
insert into resource_categories (type, resource_id) values ('MM7', 542);
insert into resource_categories (type, resource_id) values ('xPression', 336);
insert into resource_categories (type, resource_id) values ('BPL', 186);
insert into resource_categories (type, resource_id) values ('LCD Projectors', 823);
insert into resource_categories (type, resource_id) values ('Social Media', 918);
insert into resource_categories (type, resource_id) values ('Nanotechnology', 176);
insert into resource_categories (type, resource_id) values ('MRV', 777);
insert into resource_categories (type, resource_id) values ('Psychological Testing', 234);
insert into resource_categories (type, resource_id) values ('GXT', 883);
insert into resource_categories (type, resource_id) values ('Fund Administration', 790);
insert into resource_categories (type, resource_id) values ('Cybercrime', 322);
insert into resource_categories (type, resource_id) values ('GBS', 269);
insert into resource_categories (type, resource_id) values ('Logistics', 627);
insert into resource_categories (type, resource_id) values ('HR Transformation', 893);
insert into resource_categories (type, resource_id) values ('Vocal Coaching', 400);
insert into resource_categories (type, resource_id) values ('JiBX', 827);
insert into resource_categories (type, resource_id) values ('CWTS', 605);
insert into resource_categories (type, resource_id) values ('Ocean Transportation', 177);
insert into resource_categories (type, resource_id) values ('Flight Test', 478);
insert into resource_categories (type, resource_id) values ('ePub', 42);
insert into resource_categories (type, resource_id) values ('MPLAB', 185);
insert into resource_categories (type, resource_id) values ('Ubiquitous Computing', 473);
insert into resource_categories (type, resource_id) values ('Lunch', 726);
insert into resource_categories (type, resource_id) values ('Partner Management', 136);
insert into resource_categories (type, resource_id) values ('Videography', 470);
insert into resource_categories (type, resource_id) values ('VCI', 732);
insert into resource_categories (type, resource_id) values ('PCI DSS', 111);
insert into resource_categories (type, resource_id) values ('RMADS', 654);
insert into resource_categories (type, resource_id) values ('HR Metrics', 891);
insert into resource_categories (type, resource_id) values ('PBUSE', 732);
insert into resource_categories (type, resource_id) values ('Digital Media', 313);
insert into resource_categories (type, resource_id) values ('Loans', 101);
insert into resource_categories (type, resource_id) values ('EoMPLS', 90);
insert into resource_categories (type, resource_id) values ('Notary Public', 38);
insert into resource_categories (type, resource_id) values ('Social TV', 732);
insert into resource_categories (type, resource_id) values ('IGOR Pro', 675);
insert into resource_categories (type, resource_id) values ('Utility Construction', 531);
insert into resource_categories (type, resource_id) values ('cDNA', 765);
insert into resource_categories (type, resource_id) values ('IC', 432);
insert into resource_categories (type, resource_id) values ('OS/390', 114);
insert into resource_categories (type, resource_id) values ('SSL', 105);
insert into resource_categories (type, resource_id) values ('Holistic Health', 370);
insert into resource_categories (type, resource_id) values ('Omnibus', 521);
insert into resource_categories (type, resource_id) values ('Yii', 820);
insert into resource_categories (type, resource_id) values ('WLAN', 111);
insert into resource_categories (type, resource_id) values ('RWA', 125);
insert into resource_categories (type, resource_id) values ('Construction Management', 982);
insert into resource_categories (type, resource_id) values ('MHE', 908);
insert into resource_categories (type, resource_id) values ('HMS', 919);
insert into resource_categories (type, resource_id) values ('GDS', 937);
insert into resource_categories (type, resource_id) values ('Human Resources', 815);
insert into resource_categories (type, resource_id) values ('Brazilian Jiu-Jitsu', 59);
insert into resource_categories (type, resource_id) values ('TV News Production', 44);
insert into resource_categories (type, resource_id) values ('Strategic Alliances', 808);
insert into resource_categories (type, resource_id) values ('Online Journalism', 82);
insert into resource_categories (type, resource_id) values ('Post Production', 999);
insert into resource_categories (type, resource_id) values ('PVC', 805);
insert into resource_categories (type, resource_id) values ('Aeronautics', 211);
insert into resource_categories (type, resource_id) values ('JBoss ESB', 496);
insert into resource_categories (type, resource_id) values ('DWDM', 479);
insert into resource_categories (type, resource_id) values ('QSA', 659);
insert into resource_categories (type, resource_id) values ('Wind Turbines', 940);
insert into resource_categories (type, resource_id) values ('AQTF compliance', 375);
insert into resource_categories (type, resource_id) values ('Videography', 220);
insert into resource_categories (type, resource_id) values ('Driving Results', 734);
insert into resource_categories (type, resource_id) values ('Pyrography', 574);
insert into resource_categories (type, resource_id) values ('Lubricants', 343);
insert into resource_categories (type, resource_id) values ('UV coating', 309);
insert into resource_categories (type, resource_id) values ('VLAN', 43);
insert into resource_categories (type, resource_id) values ('Roofers', 826);
insert into resource_categories (type, resource_id) values ('BPH', 657);
insert into resource_categories (type, resource_id) values ('LTD', 437);
insert into resource_categories (type, resource_id) values ('QRadar', 423);
insert into resource_categories (type, resource_id) values ('Document Imaging', 701);
insert into resource_categories (type, resource_id) values ('NVH', 277);
insert into resource_categories (type, resource_id) values ('Simple IRA', 1000);
insert into resource_categories (type, resource_id) values ('CCIM', 703);
insert into resource_categories (type, resource_id) values ('Prenuptial Agreements', 275);
insert into resource_categories (type, resource_id) values ('MPR', 35);
insert into resource_categories (type, resource_id) values ('Slope Stability', 192);
insert into resource_categories (type, resource_id) values ('SQL', 956);
insert into resource_categories (type, resource_id) values ('Training', 937);
insert into resource_categories (type, resource_id) values ('Title Searches', 103);
insert into resource_categories (type, resource_id) values ('LME', 739);
insert into resource_categories (type, resource_id) values ('Key Account Relationship Building', 248);
insert into resource_categories (type, resource_id) values ('OJEU', 311);
insert into resource_categories (type, resource_id) values ('MS Integration Services', 298);
insert into resource_categories (type, resource_id) values ('Business Intelligence Tools', 462);
insert into resource_categories (type, resource_id) values ('Biochemistry', 934);
insert into resource_categories (type, resource_id) values ('DTR', 502);
insert into resource_categories (type, resource_id) values ('Groundwater', 843);
insert into resource_categories (type, resource_id) values ('Outdoor Recreation', 176);
insert into resource_categories (type, resource_id) values ('CFML', 945);
insert into resource_categories (type, resource_id) values ('CDL Class A', 560);
insert into resource_categories (type, resource_id) values ('Boat', 748);
insert into resource_categories (type, resource_id) values ('Lyra', 923);
insert into resource_categories (type, resource_id) values ('Overtime', 971);
insert into resource_categories (type, resource_id) values ('Rhinoceros', 63);
insert into resource_categories (type, resource_id) values ('Sustainable Development', 447);
insert into resource_categories (type, resource_id) values ('Oncology', 878);
insert into resource_categories (type, resource_id) values ('SRED', 982);
insert into resource_categories (type, resource_id) values ('EU Competition Law', 227);
insert into resource_categories (type, resource_id) values ('Pneumatic Conveying', 702);
insert into resource_categories (type, resource_id) values ('TBS', 177);
insert into resource_categories (type, resource_id) values ('Townhomes', 457);
insert into resource_categories (type, resource_id) values ('Vsftpd', 991);
insert into resource_categories (type, resource_id) values ('Ektron', 267);
insert into resource_categories (type, resource_id) values ('GDI', 780);
insert into resource_categories (type, resource_id) values ('Earned Value Management', 390);
insert into resource_categories (type, resource_id) values ('UltraTax', 78);
insert into resource_categories (type, resource_id) values ('NWDI', 980);
insert into resource_categories (type, resource_id) values ('VMware vCenter', 452);
insert into resource_categories (type, resource_id) values ('Process Scheduler', 68);
insert into resource_categories (type, resource_id) values ('LSAT', 973);
insert into resource_categories (type, resource_id) values ('MPLAB', 852);
insert into resource_categories (type, resource_id) values ('Strategy', 840);
insert into resource_categories (type, resource_id) values ('Glass', 113);
insert into resource_categories (type, resource_id) values ('Listings', 255);
insert into resource_categories (type, resource_id) values ('FBCB2', 355);
insert into resource_categories (type, resource_id) values ('BCNE', 195);
insert into resource_categories (type, resource_id) values ('IVD', 588);
insert into resource_categories (type, resource_id) values ('Gyrotonic', 80);
insert into resource_categories (type, resource_id) values ('HDCAM', 111);
insert into resource_categories (type, resource_id) values ('Pneumatic Conveying', 263);
insert into resource_categories (type, resource_id) values ('Black Belt', 126);
insert into resource_categories (type, resource_id) values ('Bands', 671);
insert into resource_categories (type, resource_id) values ('Applied Kinesiology', 123);
insert into resource_categories (type, resource_id) values ('VTS', 903);
insert into resource_categories (type, resource_id) values ('Titration', 690);
insert into resource_categories (type, resource_id) values ('AHU', 150);
insert into resource_categories (type, resource_id) values ('IIA Standards', 87);
insert into resource_categories (type, resource_id) values ('Yammer', 383);
insert into resource_categories (type, resource_id) values ('ATLS', 642);
insert into resource_categories (type, resource_id) values ('Front Office', 113);
insert into resource_categories (type, resource_id) values ('BWA', 209);
insert into resource_categories (type, resource_id) values ('CWSP', 370);
insert into resource_categories (type, resource_id) values ('QALoad', 105);
insert into resource_categories (type, resource_id) values ('LDAP', 645);
insert into resource_categories (type, resource_id) values ('Functional Verification', 242);
insert into resource_categories (type, resource_id) values ('WS-Federation', 413);
insert into resource_categories (type, resource_id) values ('Workplace Safety', 349);
insert into resource_categories (type, resource_id) values ('Jenkins', 371);
insert into resource_categories (type, resource_id) values ('Internal Controls', 244);
insert into resource_categories (type, resource_id) values ('Ion Chromatography', 422);
insert into resource_categories (type, resource_id) values ('VMI Programs', 57);
insert into resource_categories (type, resource_id) values ('SNP genotyping', 655);
insert into resource_categories (type, resource_id) values ('Event Production', 665);
insert into resource_categories (type, resource_id) values ('Cost Benefit', 33);
insert into resource_categories (type, resource_id) values ('HDRI', 686);
insert into resource_categories (type, resource_id) values ('MS Axapta', 934);
insert into resource_categories (type, resource_id) values ('Mythology', 38);
insert into resource_categories (type, resource_id) values ('Platform LSF', 479);
insert into resource_categories (type, resource_id) values ('Ultrasound Therapy', 984);
insert into resource_categories (type, resource_id) values ('CCVP', 683);
insert into resource_categories (type, resource_id) values ('WLI', 467);
insert into resource_categories (type, resource_id) values ('Volunteer Management', 1000);
insert into resource_categories (type, resource_id) values ('Pilates', 58);
insert into resource_categories (type, resource_id) values ('PMBOK', 433);
insert into resource_categories (type, resource_id) values ('NLTK', 955);
insert into resource_categories (type, resource_id) values ('Xajax', 562);
insert into resource_categories (type, resource_id) values ('SnapMirror', 338);
insert into resource_categories (type, resource_id) values ('E-Learning', 94);
insert into resource_categories (type, resource_id) values ('Switchgear', 821);
insert into resource_categories (type, resource_id) values ('OEM negotiations', 631);
insert into resource_categories (type, resource_id) values ('Swimming', 422);
insert into resource_categories (type, resource_id) values ('BCM', 645);
insert into resource_categories (type, resource_id) values ('Omgeo Oasys', 845);
insert into resource_categories (type, resource_id) values ('NHS', 22);
insert into resource_categories (type, resource_id) values ('GTK', 770);
insert into resource_categories (type, resource_id) values ('DLL', 281);
insert into resource_categories (type, resource_id) values ('DV Cleared', 330);
insert into resource_categories (type, resource_id) values ('JD Edwards', 479);
insert into resource_categories (type, resource_id) values ('Usability Engineering', 603);
insert into resource_categories (type, resource_id) values ('BJJ', 172);
insert into resource_categories (type, resource_id) values ('pfSense', 447);
insert into resource_categories (type, resource_id) values ('NSA-IAM', 94);
insert into resource_categories (type, resource_id) values ('Management Due Diligence', 869);
insert into resource_categories (type, resource_id) values ('Overseas Sourcing', 508);
insert into resource_categories (type, resource_id) values ('Earthquake Engineering', 433);
insert into resource_categories (type, resource_id) values ('Planning', 10);
insert into resource_categories (type, resource_id) values ('Aviation', 766);
insert into resource_categories (type, resource_id) values ('International Law', 534);
insert into resource_categories (type, resource_id) values ('Two-phase Flow', 418);
insert into resource_categories (type, resource_id) values ('XFP', 920);
insert into resource_categories (type, resource_id) values ('Key Account Management', 847);
insert into resource_categories (type, resource_id) values ('EASA', 936);
insert into resource_categories (type, resource_id) values ('Test Planning', 682);
insert into resource_categories (type, resource_id) values ('Fashion Shows', 596);
insert into resource_categories (type, resource_id) values ('MQSI', 481);
insert into resource_categories (type, resource_id) values ('Holistic Health', 159);
insert into resource_categories (type, resource_id) values ('ILM', 747);
insert into resource_categories (type, resource_id) values ('SSAS 2008', 263);
insert into resource_categories (type, resource_id) values ('FxCop', 7);
insert into resource_categories (type, resource_id) values ('Automotive Aftermarket', 982);
insert into resource_categories (type, resource_id) values ('GTAW', 595);
insert into resource_categories (type, resource_id) values ('NICE Call Recording', 895);
insert into resource_categories (type, resource_id) values ('WDF', 426);
insert into resource_categories (type, resource_id) values ('Navigation', 393);
insert into resource_categories (type, resource_id) values ('FM200', 344);
insert into resource_categories (type, resource_id) values ('Tourism', 938);
insert into resource_categories (type, resource_id) values ('Alcohol Awareness', 360);
insert into resource_categories (type, resource_id) values ('Lymphedema', 265);
insert into resource_categories (type, resource_id) values ('Book Reviews', 837);
insert into resource_categories (type, resource_id) values ('Voice Over', 616);
insert into resource_categories (type, resource_id) values ('RCM', 550);
insert into resource_categories (type, resource_id) values ('Kindergarten', 897);
insert into resource_categories (type, resource_id) values ('RTDS', 788);
insert into resource_categories (type, resource_id) values ('HSRP', 414);
insert into resource_categories (type, resource_id) values ('Utility Industry', 609);
insert into resource_categories (type, resource_id) values ('ICH Guidelines', 841);
insert into resource_categories (type, resource_id) values ('Woodworking', 926);
insert into resource_categories (type, resource_id) values ('DTT', 768);
insert into resource_categories (type, resource_id) values ('TCD', 724);
insert into resource_categories (type, resource_id) values ('Airframe', 564);
insert into resource_categories (type, resource_id) values ('Conservation Issues', 485);
insert into resource_categories (type, resource_id) values ('MV', 578);
insert into resource_categories (type, resource_id) values ('DGA', 899);
insert into resource_categories (type, resource_id) values ('CBOT', 407);
insert into resource_categories (type, resource_id) values ('RHEV', 155);
insert into resource_categories (type, resource_id) values ('DDR3', 750);
insert into resource_categories (type, resource_id) values ('QMF for Windows', 104);
insert into resource_categories (type, resource_id) values ('AV', 379);
insert into resource_categories (type, resource_id) values ('WPF', 515);
insert into resource_categories (type, resource_id) values ('VTR', 519);
insert into resource_categories (type, resource_id) values ('Juvederm', 210);
insert into resource_categories (type, resource_id) values ('TTL', 858);
insert into resource_categories (type, resource_id) values ('MBCS', 235);
insert into resource_categories (type, resource_id) values ('Alternative Dispute Resolution', 346);
insert into resource_categories (type, resource_id) values ('PV', 341);
insert into resource_categories (type, resource_id) values ('TVCs', 287);
insert into resource_categories (type, resource_id) values ('Tax Returns', 894);
insert into resource_categories (type, resource_id) values ('Union Avoidance', 779);
insert into resource_categories (type, resource_id) values ('GLP', 362);
insert into resource_categories (type, resource_id) values ('DGGE', 272);
insert into resource_categories (type, resource_id) values ('FTIR', 93);
insert into resource_categories (type, resource_id) values ('FX Derivatives', 640);
insert into resource_categories (type, resource_id) values ('Rapid Prototyping', 736);
insert into resource_categories (type, resource_id) values ('XMLHTTP', 802);
insert into resource_categories (type, resource_id) values ('Ethical Hacking', 399);
insert into resource_categories (type, resource_id) values ('NMON', 37);
insert into resource_categories (type, resource_id) values ('Practice CS', 354);
insert into resource_categories (type, resource_id) values ('Watercolor', 46);
insert into resource_categories (type, resource_id) values ('Luxury', 649);
insert into resource_categories (type, resource_id) values ('dSPACE', 921);
insert into resource_categories (type, resource_id) values ('Pilates', 15);
insert into resource_categories (type, resource_id) values ('Strategic HR', 846);
insert into resource_categories (type, resource_id) values ('RPT', 127);
insert into resource_categories (type, resource_id) values ('Document Review', 471);
insert into resource_categories (type, resource_id) values ('JSONP', 409);
insert into resource_categories (type, resource_id) values ('Data Entry', 570);
insert into resource_categories (type, resource_id) values ('BFSI', 955);
insert into resource_categories (type, resource_id) values ('GTK', 356);
insert into resource_categories (type, resource_id) values ('SQL*Plus', 217);
insert into resource_categories (type, resource_id) values ('Educational Leadership', 212);
insert into resource_categories (type, resource_id) values ('Web TV', 843);
insert into resource_categories (type, resource_id) values ('Risk Assessment', 712);
insert into resource_categories (type, resource_id) values ('Business Efficiency', 521);
insert into resource_categories (type, resource_id) values ('FX Hedging', 310);
insert into resource_categories (type, resource_id) values ('Oil Industry', 399);
insert into resource_categories (type, resource_id) values ('Corporate Gifts', 551);
insert into resource_categories (type, resource_id) values ('Working Capital Management', 698);
insert into resource_categories (type, resource_id) values ('Corona SDK', 863);
insert into resource_categories (type, resource_id) values ('Multi-Unit', 382);
insert into resource_categories (type, resource_id) values ('Jive', 696);
insert into resource_categories (type, resource_id) values ('EEG', 39);
insert into resource_categories (type, resource_id) values ('WUFI', 388);
insert into resource_categories (type, resource_id) values ('AJAX Frameworks', 780);
insert into resource_categories (type, resource_id) values ('Kronos', 51);
insert into resource_categories (type, resource_id) values ('TF-CBT', 350);
insert into resource_categories (type, resource_id) values ('Type 1 Diabetes', 42);
insert into resource_categories (type, resource_id) values ('OSHA', 943);
insert into resource_categories (type, resource_id) values ('MRO Management', 41);
insert into resource_categories (type, resource_id) values ('FHA', 729);
insert into resource_categories (type, resource_id) values ('C-TPAT', 81);
insert into resource_categories (type, resource_id) values ('UMTS', 87);
insert into resource_categories (type, resource_id) values ('cGLP', 12);
insert into resource_categories (type, resource_id) values ('PDCA', 237);
insert into resource_categories (type, resource_id) values ('Maritime Operations', 40);
insert into resource_categories (type, resource_id) values ('Roth IRA', 573);
insert into resource_categories (type, resource_id) values ('SMS', 92);
insert into resource_categories (type, resource_id) values ('DS3', 421);
insert into resource_categories (type, resource_id) values ('Khalix', 801);
insert into resource_categories (type, resource_id) values ('McAfee', 377);
insert into resource_categories (type, resource_id) values ('Glamour', 900);
insert into resource_categories (type, resource_id) values ('BSD', 603);
insert into resource_categories (type, resource_id) values ('Sheet Metal', 204);
insert into resource_categories (type, resource_id) values ('Natural Language Processing', 228);
insert into resource_categories (type, resource_id) values ('WLM', 81);
insert into resource_categories (type, resource_id) values ('RCM', 144);
insert into resource_categories (type, resource_id) values ('Timber', 172);
insert into resource_categories (type, resource_id) values ('Nintendo DS', 501);
insert into resource_categories (type, resource_id) values ('Employer Branding', 990);
insert into resource_categories (type, resource_id) values ('BMD', 734);
insert into resource_categories (type, resource_id) values ('Childcare', 768);
insert into resource_categories (type, resource_id) values ('Music History', 3);
insert into resource_categories (type, resource_id) values ('MTTR', 519);
insert into resource_categories (type, resource_id) values ('Construction Safety', 894);
insert into resource_categories (type, resource_id) values ('HNW', 97);
insert into resource_categories (type, resource_id) values ('User Experience', 349);
insert into resource_categories (type, resource_id) values ('RED MX', 502);
insert into resource_categories (type, resource_id) values ('Vyatta', 925);
insert into resource_categories (type, resource_id) values ('NI Multisim', 594);
insert into resource_categories (type, resource_id) values ('MCNP', 348);
insert into resource_categories (type, resource_id) values ('Oxides', 143);
insert into resource_categories (type, resource_id) values ('FDMA', 944);
insert into resource_categories (type, resource_id) values ('Kontakt', 280);
insert into resource_categories (type, resource_id) values ('PNR', 980);
insert into resource_categories (type, resource_id) values ('Flight Planning', 369);
insert into resource_categories (type, resource_id) values ('Histology', 735);
insert into resource_categories (type, resource_id) values ('MCEV', 332);
insert into resource_categories (type, resource_id) values ('OAM', 870);
insert into resource_categories (type, resource_id) values ('Aerospace Structures', 655);
insert into resource_categories (type, resource_id) values ('Water Treatment', 799);
insert into resource_categories (type, resource_id) values ('TCM', 505);
insert into resource_categories (type, resource_id) values ('DSP BIOS', 885);
insert into resource_categories (type, resource_id) values ('iPhone Support', 31);
insert into resource_categories (type, resource_id) values ('Certified DDI Facilitator', 458);
insert into resource_categories (type, resource_id) values ('LCSH', 886);
insert into resource_categories (type, resource_id) values ('Claim', 398);
insert into resource_categories (type, resource_id) values ('Payroll', 770);
insert into resource_categories (type, resource_id) values ('MPIO', 860);
insert into resource_categories (type, resource_id) values ('XForms', 875);
insert into resource_categories (type, resource_id) values ('ITIL v3 Foundations Certified', 797);
insert into resource_categories (type, resource_id) values ('Biostatistics', 113);
insert into resource_categories (type, resource_id) values ('ArcGIS', 186);
insert into resource_categories (type, resource_id) values ('Jeet Kune Do', 152);
insert into resource_categories (type, resource_id) values ('Psychiatry', 557);
insert into resource_categories (type, resource_id) values ('Scheduling', 435);
insert into resource_categories (type, resource_id) values ('IaaS', 711);
insert into resource_categories (type, resource_id) values ('TPX', 734);
insert into resource_categories (type, resource_id) values ('QlikView', 611);
insert into resource_categories (type, resource_id) values ('FCoE', 297);
insert into resource_categories (type, resource_id) values ('Art', 886);
insert into resource_categories (type, resource_id) values ('FCC', 745);
insert into resource_categories (type, resource_id) values ('TDA', 6);
insert into resource_categories (type, resource_id) values ('Film', 827);
insert into resource_categories (type, resource_id) values ('OTM', 170);
insert into resource_categories (type, resource_id) values ('Ultrasound', 835);
insert into resource_categories (type, resource_id) values ('Luminex', 868);
insert into resource_categories (type, resource_id) values ('NX Unigraphics', 734);
insert into resource_categories (type, resource_id) values ('Oxygen Therapy', 500);
insert into resource_categories (type, resource_id) values ('Special Effects', 244);
insert into resource_categories (type, resource_id) values ('Github', 430);
insert into resource_categories (type, resource_id) values ('Sustainable Tourism', 692);
insert into resource_categories (type, resource_id) values ('TPR', 522);
insert into resource_categories (type, resource_id) values ('Aerohive', 758);
insert into resource_categories (type, resource_id) values ('Guitar', 46);
insert into resource_categories (type, resource_id) values ('High Net Worth Individuals', 403);
insert into resource_categories (type, resource_id) values ('DTE', 932);
insert into resource_categories (type, resource_id) values ('Aerobics', 248);
insert into resource_categories (type, resource_id) values ('IP CCTV', 65);
insert into resource_categories (type, resource_id) values ('Justice', 309);
insert into resource_categories (type, resource_id) values ('EOQ', 518);
insert into resource_categories (type, resource_id) values ('KDB+', 494);
insert into resource_categories (type, resource_id) values ('Consumer Behaviour', 413);
insert into resource_categories (type, resource_id) values ('Pipefitting', 416);
insert into resource_categories (type, resource_id) values ('Judo', 739);
insert into resource_categories (type, resource_id) values ('IBM Websphere Commerce', 303);
insert into resource_categories (type, resource_id) values ('Multi-color Flow Cytometry', 730);
insert into resource_categories (type, resource_id) values ('Akamai', 600);
insert into resource_categories (type, resource_id) values ('RED MX', 683);
insert into resource_categories (type, resource_id) values ('OMA', 501);
insert into resource_categories (type, resource_id) values ('Pallet Jack', 224);
insert into resource_categories (type, resource_id) values ('Trend Analysis', 851);
insert into resource_categories (type, resource_id) values ('Vendor Relationship Management', 695);
insert into resource_categories (type, resource_id) values ('DFR', 956);
insert into resource_categories (type, resource_id) values ('Shared Services', 92);
insert into resource_categories (type, resource_id) values ('EOU', 409);
insert into resource_categories (type, resource_id) values ('Experion PKS', 841);
insert into resource_categories (type, resource_id) values ('Aquariums', 580);
insert into resource_categories (type, resource_id) values ('TGI', 797);
insert into resource_categories (type, resource_id) values ('Software Development', 45);
insert into resource_categories (type, resource_id) values ('QPS', 359);
insert into resource_categories (type, resource_id) values ('Emotional Intelligence', 120);
insert into resource_categories (type, resource_id) values ('Beauty Industry', 674);
insert into resource_categories (type, resource_id) values ('Systems Engineering', 616);
insert into resource_categories (type, resource_id) values ('IQMS', 584);
insert into resource_categories (type, resource_id) values ('GPU', 772);
insert into resource_categories (type, resource_id) values ('Procurement', 255);
insert into resource_categories (type, resource_id) values ('EH&amp;S Compliance', 786);
insert into resource_categories (type, resource_id) values ('AXE', 607);
insert into resource_categories (type, resource_id) values ('DDI Certified Facilitator', 992);
insert into resource_categories (type, resource_id) values ('Westlaw', 574);
insert into resource_categories (type, resource_id) values ('Time &amp; Attendance', 123);
insert into resource_categories (type, resource_id) values ('Logo Design', 34);
insert into resource_categories (type, resource_id) values ('Microsoft Office', 192);
insert into resource_categories (type, resource_id) values ('Press Releases', 659);
insert into resource_categories (type, resource_id) values ('Industrial Ethernet', 43);
insert into resource_categories (type, resource_id) values ('UIM', 609);
insert into resource_categories (type, resource_id) values ('Guitar Playing', 365);
insert into resource_categories (type, resource_id) values ('Snoring', 39);
insert into resource_categories (type, resource_id) values ('WGA', 72);
insert into resource_categories (type, resource_id) values ('EBR', 88);
insert into resource_categories (type, resource_id) values ('Red Hat Linux', 119);
insert into resource_categories (type, resource_id) values ('XMLBeans', 282);
insert into resource_categories (type, resource_id) values ('CTC', 743);
insert into resource_categories (type, resource_id) values ('CMake', 831);
insert into resource_categories (type, resource_id) values ('Tax Research', 856);
insert into resource_categories (type, resource_id) values ('Updos', 672);
insert into resource_categories (type, resource_id) values ('Machine Tools', 388);
insert into resource_categories (type, resource_id) values ('CMMI Level 5', 82);
insert into resource_categories (type, resource_id) values ('PDMLink', 243);
insert into resource_categories (type, resource_id) values ('Switches', 272);
insert into resource_categories (type, resource_id) values ('Rent to Own', 110);
insert into resource_categories (type, resource_id) values ('LCL', 49);
insert into resource_categories (type, resource_id) values ('Oil Analysis', 898);
insert into resource_categories (type, resource_id) values ('Ruby on Rails', 575);
insert into resource_categories (type, resource_id) values ('E-zines', 15);
insert into resource_categories (type, resource_id) values ('Kantar', 127);
insert into resource_categories (type, resource_id) values ('Psychological Assessment', 71);
insert into resource_categories (type, resource_id) values ('Errors &amp; Omissions', 208);
insert into resource_categories (type, resource_id) values ('Time Management', 301);
insert into resource_categories (type, resource_id) values ('PDM Works', 93);
insert into resource_categories (type, resource_id) values ('ICEM CFD', 595);
insert into resource_categories (type, resource_id) values ('PyMEL', 868);
insert into resource_categories (type, resource_id) values ('BMV', 551);
insert into resource_categories (type, resource_id) values ('GTM', 877);
insert into resource_categories (type, resource_id) values ('Structural Dynamics', 6);
insert into resource_categories (type, resource_id) values ('Power Generation', 764);
insert into resource_categories (type, resource_id) values ('Evangelism', 912);
insert into resource_categories (type, resource_id) values ('Canon DSLR', 91);
insert into resource_categories (type, resource_id) values ('OGSYS', 12);
insert into resource_categories (type, resource_id) values ('McData', 767);
insert into resource_categories (type, resource_id) values ('Xactly', 112);
insert into resource_categories (type, resource_id) values ('Human Resource Development', 452);
insert into resource_categories (type, resource_id) values ('VSAT', 246);
insert into resource_categories (type, resource_id) values ('Sony HDV', 176);
insert into resource_categories (type, resource_id) values ('SIP', 142);
insert into resource_categories (type, resource_id) values ('PQQ', 739);
insert into resource_categories (type, resource_id) values ('Quantitative Research', 465);
insert into resource_categories (type, resource_id) values ('Sales Tax', 177);
insert into resource_categories (type, resource_id) values ('Employer Branding', 165);
insert into resource_categories (type, resource_id) values ('RTK', 250);
insert into resource_categories (type, resource_id) values ('DVD Replication', 286);
insert into resource_categories (type, resource_id) values ('OLEDB', 556);
insert into resource_categories (type, resource_id) values ('Production Planning', 655);
insert into resource_categories (type, resource_id) values ('Situational Awareness', 831);
insert into resource_categories (type, resource_id) values ('Core Java', 769);
insert into resource_categories (type, resource_id) values ('TSW', 86);
insert into resource_categories (type, resource_id) values ('Zebrafish', 210);
insert into resource_categories (type, resource_id) values ('CWTS', 473);
insert into resource_categories (type, resource_id) values ('Waste Management', 26);
insert into resource_categories (type, resource_id) values ('SDLC', 432);
insert into resource_categories (type, resource_id) values ('ODM management', 447);
insert into resource_categories (type, resource_id) values ('Aftersales', 558);
insert into resource_categories (type, resource_id) values ('Commercial Lending', 356);
insert into resource_categories (type, resource_id) values ('Xcart', 584);
insert into resource_categories (type, resource_id) values ('MDSD', 848);
insert into resource_categories (type, resource_id) values ('Civil Rights', 136);
insert into resource_categories (type, resource_id) values ('Osteopathy', 403);
insert into resource_categories (type, resource_id) values ('IFW', 602);
insert into resource_categories (type, resource_id) values ('Real Estate Financing', 336);
insert into resource_categories (type, resource_id) values ('MS-DOS', 75);
insert into resource_categories (type, resource_id) values ('Sheet Metal', 842);
insert into resource_categories (type, resource_id) values ('MLP', 792);
insert into resource_categories (type, resource_id) values ('Litigation Support', 667);
insert into resource_categories (type, resource_id) values ('Drip Irrigation', 32);
insert into resource_categories (type, resource_id) values ('Medical Nutrition Therapy', 333);
insert into resource_categories (type, resource_id) values ('Early Intervention', 459);
insert into resource_categories (type, resource_id) values ('Knowledge Discovery', 349);
insert into resource_categories (type, resource_id) values ('BMC Portal', 478);
insert into resource_categories (type, resource_id) values ('SMT', 874);
insert into resource_categories (type, resource_id) values ('NICE Call Recording', 582);
insert into resource_categories (type, resource_id) values ('Literature', 615);
insert into resource_categories (type, resource_id) values ('IOSH', 496);
insert into resource_categories (type, resource_id) values ('Payment by Results', 849);
insert into resource_categories (type, resource_id) values ('Software Documentation', 179);
insert into resource_categories (type, resource_id) values ('Ocean', 807);
insert into resource_categories (type, resource_id) values ('First Aid', 547);
insert into resource_categories (type, resource_id) values ('Internet Yellow Pages', 480);
insert into resource_categories (type, resource_id) values ('Pro II', 226);
insert into resource_categories (type, resource_id) values ('LPT', 368);
insert into resource_categories (type, resource_id) values ('Gourmet', 693);
insert into resource_categories (type, resource_id) values ('HMI Programming', 676);
insert into resource_categories (type, resource_id) values ('RMF', 880);
insert into resource_categories (type, resource_id) values ('Film Production', 366);
insert into resource_categories (type, resource_id) values ('ICP-MS', 126);
insert into resource_categories (type, resource_id) values ('Klocwork', 265);
insert into resource_categories (type, resource_id) values ('Hospitals', 292);
insert into resource_categories (type, resource_id) values ('CDMA2000', 649);
insert into resource_categories (type, resource_id) values ('Entertainment', 361);
insert into resource_categories (type, resource_id) values ('Emotional Intelligence', 88);
insert into resource_categories (type, resource_id) values ('NS-2', 812);
insert into resource_categories (type, resource_id) values ('Siding', 83);
insert into resource_categories (type, resource_id) values ('Luxury Travel', 451);
insert into resource_categories (type, resource_id) values ('DOT Regulations', 970);
insert into resource_categories (type, resource_id) values ('SBEM', 573);
insert into resource_categories (type, resource_id) values ('WSS 2.0', 19);
insert into resource_categories (type, resource_id) values ('Flow Cytometry', 679);
insert into resource_categories (type, resource_id) values ('FF&amp;E Specifications', 515);
insert into resource_categories (type, resource_id) values ('Observational Studies', 173);
insert into resource_categories (type, resource_id) values ('Yamaha PM5D', 959);
insert into resource_categories (type, resource_id) values ('Strategic Planning', 903);
insert into resource_categories (type, resource_id) values ('Nastran', 433);
insert into resource_categories (type, resource_id) values ('Humanitarian Assistance', 180);
insert into resource_categories (type, resource_id) values ('LCM', 369);
insert into resource_categories (type, resource_id) values ('DFMEA', 785);
insert into resource_categories (type, resource_id) values ('TLM', 414);
insert into resource_categories (type, resource_id) values ('Transportation Management', 618);
insert into resource_categories (type, resource_id) values ('HSPA', 815);
insert into resource_categories (type, resource_id) values ('FMS', 415);
insert into resource_categories (type, resource_id) values ('nVision', 678);
insert into resource_categories (type, resource_id) values ('HDTV', 406);
insert into resource_categories (type, resource_id) values ('Egyptology', 362);
insert into resource_categories (type, resource_id) values ('GPIB', 854);
insert into resource_categories (type, resource_id) values ('DBVisualizer', 981);
insert into resource_categories (type, resource_id) values ('Digital Strategy', 287);
insert into resource_categories (type, resource_id) values ('Bands', 500);
insert into resource_categories (type, resource_id) values ('GCC', 74);
insert into resource_categories (type, resource_id) values ('Change Control', 869);
insert into resource_categories (type, resource_id) values ('AJAX', 892);
insert into resource_categories (type, resource_id) values ('RAN', 619);
insert into resource_categories (type, resource_id) values ('EGL', 736);
insert into resource_categories (type, resource_id) values ('Non-fiction', 446);
insert into resource_categories (type, resource_id) values ('Powers of Attorney', 835);
insert into resource_categories (type, resource_id) values ('Judo', 691);
insert into resource_categories (type, resource_id) values ('SQL DB2', 967);
insert into resource_categories (type, resource_id) values ('SAP PP', 992);
insert into resource_categories (type, resource_id) values ('Financial Audits', 295);
insert into resource_categories (type, resource_id) values ('nCode', 163);
insert into resource_categories (type, resource_id) values ('OTDR', 589);
insert into resource_categories (type, resource_id) values ('Early Intervention', 264);
insert into resource_categories (type, resource_id) values ('Abstract Paintings', 557);
insert into resource_categories (type, resource_id) values ('Occupational Health', 382);
insert into resource_categories (type, resource_id) values ('ATG CSC', 703);
insert into resource_categories (type, resource_id) values ('Lunix', 122);
insert into resource_categories (type, resource_id) values ('Yamaha PM5D', 636);
insert into resource_categories (type, resource_id) values ('Xcart', 852);
insert into resource_categories (type, resource_id) values ('Twisted', 965);
insert into resource_categories (type, resource_id) values ('Xajax', 685);
insert into resource_categories (type, resource_id) values ('CCIE', 978);
insert into resource_categories (type, resource_id) values ('Toad', 977);
insert into resource_categories (type, resource_id) values ('Outplacement', 569);
insert into resource_categories (type, resource_id) values ('GBA', 972);
insert into resource_categories (type, resource_id) values ('Automotive', 630);
insert into resource_categories (type, resource_id) values ('Yellow Belt', 80);
insert into resource_categories (type, resource_id) values ('GPCRs', 373);
insert into resource_categories (type, resource_id) values ('Chromatography', 780);
insert into resource_categories (type, resource_id) values ('SNA', 18);
insert into resource_categories (type, resource_id) values ('HDLC', 735);
insert into resource_categories (type, resource_id) values ('European Languages', 230);
insert into resource_categories (type, resource_id) values ('Google Earth', 323);
insert into resource_categories (type, resource_id) values ('Science', 723);
insert into resource_categories (type, resource_id) values ('High Yield Bonds', 854);
insert into resource_categories (type, resource_id) values ('BSI Tax Factory', 899);
insert into resource_categories (type, resource_id) values ('Pygame', 816);
insert into resource_categories (type, resource_id) values ('HMO', 485);
insert into resource_categories (type, resource_id) values ('Animation', 130);
insert into resource_categories (type, resource_id) values ('JBuilder', 287);
insert into resource_categories (type, resource_id) values ('Outside Sales', 318);
insert into resource_categories (type, resource_id) values ('Yearbook', 758);
insert into resource_categories (type, resource_id) values ('Windows Azure', 95);
insert into resource_categories (type, resource_id) values ('VPython', 560);
insert into resource_categories (type, resource_id) values ('ZBrush', 759);
insert into resource_categories (type, resource_id) values ('HP Blade', 471);
insert into resource_categories (type, resource_id) values ('Assisting Others', 7);
insert into resource_categories (type, resource_id) values ('NHibernate', 714);
insert into resource_categories (type, resource_id) values ('Wicklander-Zulawski Interview &amp; Interrogation', 91);
insert into resource_categories (type, resource_id) values ('Social Skills', 478);
insert into resource_categories (type, resource_id) values ('Cell Biology', 692);
insert into resource_categories (type, resource_id) values ('Business Objects', 906);
insert into resource_categories (type, resource_id) values ('FCNSP', 181);
insert into resource_categories (type, resource_id) values ('Client Relations', 336);
insert into resource_categories (type, resource_id) values ('Game Development', 107);
insert into resource_categories (type, resource_id) values ('Billing Systems', 966);
insert into resource_categories (type, resource_id) values ('SMO', 385);
insert into resource_categories (type, resource_id) values ('MCEV', 466);
insert into resource_categories (type, resource_id) values ('MTOs', 309);
insert into resource_categories (type, resource_id) values ('PLC', 735);
insert into resource_categories (type, resource_id) values ('Non-profit Leadership', 169);
insert into resource_categories (type, resource_id) values ('SWIFT Payments', 774);
insert into resource_categories (type, resource_id) values ('Biopharmaceuticals', 837);
insert into resource_categories (type, resource_id) values ('Literature', 699);
insert into resource_categories (type, resource_id) values ('Screenwriting', 503);
insert into resource_categories (type, resource_id) values ('MS-DOS', 532);
insert into resource_categories (type, resource_id) values ('Trading', 548);
insert into resource_categories (type, resource_id) values ('XSLT', 559);
insert into resource_categories (type, resource_id) values ('Onshore', 465);
insert into resource_categories (type, resource_id) values ('IICRC Certifications', 118);
insert into resource_categories (type, resource_id) values ('SSCP', 722);
insert into resource_categories (type, resource_id) values ('Spanish', 854);
insert into resource_categories (type, resource_id) values ('Registered Nurses', 446);
insert into resource_categories (type, resource_id) values ('Telecommunications', 332);
insert into resource_categories (type, resource_id) values ('DNA', 300);
insert into resource_categories (type, resource_id) values ('Retirement Planning', 598);
insert into resource_categories (type, resource_id) values ('HSM', 104);
insert into resource_categories (type, resource_id) values ('IB', 470);
insert into resource_categories (type, resource_id) values ('SDTM', 174);
insert into resource_categories (type, resource_id) values ('DFR', 112);
insert into resource_categories (type, resource_id) values ('Start-up Ventures', 455);
insert into resource_categories (type, resource_id) values ('PPC', 491);
insert into resource_categories (type, resource_id) values ('TIBCO', 59);
insert into resource_categories (type, resource_id) values ('IDS', 591);
insert into resource_categories (type, resource_id) values ('American Welding Society (AWS)', 588);
insert into resource_categories (type, resource_id) values ('LynxOS', 105);
insert into resource_categories (type, resource_id) values ('Broadcast', 85);
insert into resource_categories (type, resource_id) values ('Group Policy', 432);
insert into resource_categories (type, resource_id) values ('European Studies', 88);
insert into resource_categories (type, resource_id) values ('Zines', 835);
insert into resource_categories (type, resource_id) values ('Affiliate Management', 598);
insert into resource_categories (type, resource_id) values ('TMJ Treatment', 46);
insert into resource_categories (type, resource_id) values ('Two-factor Authentication', 503);
insert into resource_categories (type, resource_id) values ('American Sign Language', 600);
insert into resource_categories (type, resource_id) values ('Epidemiology', 974);
insert into resource_categories (type, resource_id) values ('Document Drafting', 715);
insert into resource_categories (type, resource_id) values ('Csh', 115);
insert into resource_categories (type, resource_id) values ('LGBT Rights', 389);
insert into resource_categories (type, resource_id) values ('QKA', 846);
insert into resource_categories (type, resource_id) values ('Human Anatomy', 362);
insert into resource_categories (type, resource_id) values ('American English', 633);
insert into resource_categories (type, resource_id) values ('Current Affairs', 83);
insert into resource_categories (type, resource_id) values ('RNO', 497);
insert into resource_categories (type, resource_id) values ('FDDI', 19);
insert into resource_categories (type, resource_id) values ('VSAM', 295);
insert into resource_categories (type, resource_id) values ('Claim', 189);
insert into resource_categories (type, resource_id) values ('SharePoint Server', 25);
insert into resource_categories (type, resource_id) values ('Hardware Architecture', 131);
insert into resource_categories (type, resource_id) values ('AXE', 18);
insert into resource_categories (type, resource_id) values ('MV', 632);
insert into resource_categories (type, resource_id) values ('Gmail', 908);
insert into resource_categories (type, resource_id) values ('Generators', 16);
insert into resource_categories (type, resource_id) values ('Research', 71);
insert into resource_categories (type, resource_id) values ('DC Drives', 755);
insert into resource_categories (type, resource_id) values ('eGain', 984);
insert into resource_categories (type, resource_id) values ('Toyota Production System', 392);
insert into resource_categories (type, resource_id) values ('TSRM', 518);
insert into resource_categories (type, resource_id) values ('Women Owned Business', 336);
insert into resource_categories (type, resource_id) values ('EH&amp;S Compliance', 66);
insert into resource_categories (type, resource_id) values ('CMBS', 756);
insert into resource_categories (type, resource_id) values ('DL1', 614);
insert into resource_categories (type, resource_id) values ('OWA', 177);
insert into resource_categories (type, resource_id) values ('Finite Element Analysis', 606);
insert into resource_categories (type, resource_id) values ('Alarm Systems', 412);
insert into resource_categories (type, resource_id) values ('UV-Vis-NIR', 515);
insert into resource_categories (type, resource_id) values ('Sybase SQL Anywhere', 288);
insert into resource_categories (type, resource_id) values ('TPP', 501);
insert into resource_categories (type, resource_id) values ('Teaching', 484);
insert into resource_categories (type, resource_id) values ('PBASIC', 724);
insert into resource_categories (type, resource_id) values ('Purchasing', 483);
insert into resource_categories (type, resource_id) values ('BTO', 277);
insert into resource_categories (type, resource_id) values ('Know-how', 921);
insert into resource_categories (type, resource_id) values ('PMB', 247);
insert into resource_categories (type, resource_id) values ('MIS', 724);
insert into resource_categories (type, resource_id) values ('KDB', 639);
insert into resource_categories (type, resource_id) values ('Nonprofits', 730);
insert into resource_categories (type, resource_id) values ('Testing Types', 118);
insert into resource_categories (type, resource_id) values ('International Shipping', 451);
insert into resource_categories (type, resource_id) values ('Part-Time CFO Services', 631);
insert into resource_categories (type, resource_id) values ('LPR', 849);
insert into resource_categories (type, resource_id) values ('Hardware Diagnostics', 94);
insert into resource_categories (type, resource_id) values ('Oxidative Stress', 624);
insert into resource_categories (type, resource_id) values ('SBEM', 707);
insert into resource_categories (type, resource_id) values ('WFC', 166);
insert into resource_categories (type, resource_id) values ('Whiplash', 822);
insert into resource_categories (type, resource_id) values ('Fiber Optics', 404);
insert into resource_categories (type, resource_id) values ('Nagios', 133);
insert into resource_categories (type, resource_id) values ('XML Publisher', 628);
insert into resource_categories (type, resource_id) values ('HCS 2000', 75);
insert into resource_categories (type, resource_id) values ('IIS', 610);
insert into resource_categories (type, resource_id) values ('iPod', 83);
insert into resource_categories (type, resource_id) values ('Award Submissions', 883);
insert into resource_categories (type, resource_id) values ('WMI', 165);
insert into resource_categories (type, resource_id) values ('Therapeutic Massage', 800);
insert into resource_categories (type, resource_id) values ('DSI', 899);
insert into resource_categories (type, resource_id) values ('Knee', 847);
insert into resource_categories (type, resource_id) values ('JPOS', 974);
insert into resource_categories (type, resource_id) values ('Nylon', 143);
insert into resource_categories (type, resource_id) values ('Hadoop', 643);
insert into resource_categories (type, resource_id) values ('Microsoft DNS', 426);
insert into resource_categories (type, resource_id) values ('PWA', 21);
insert into resource_categories (type, resource_id) values ('HR Policy Formulation', 133);
insert into resource_categories (type, resource_id) values ('Automotive Aftermarket', 611);
insert into resource_categories (type, resource_id) values ('FX Spot', 161);
insert into resource_categories (type, resource_id) values ('Fashion Blogging', 619);
insert into resource_categories (type, resource_id) values ('Wholesale Operations', 304);
insert into resource_categories (type, resource_id) values ('IACUC', 555);
insert into resource_categories (type, resource_id) values ('CVM', 566);
insert into resource_categories (type, resource_id) values ('Youth Mentoring', 297);
insert into resource_categories (type, resource_id) values ('Loan Servicing', 528);
insert into resource_categories (type, resource_id) values ('OBIEE', 333);
insert into resource_categories (type, resource_id) values ('CBM', 149);
insert into resource_categories (type, resource_id) values ('BMV', 446);
insert into resource_categories (type, resource_id) values ('Applicant Tracking Systems', 211);
insert into resource_categories (type, resource_id) values ('HR Transformation', 643);
insert into resource_categories (type, resource_id) values ('KWP2000', 491);
insert into resource_categories (type, resource_id) values ('QSIG', 543);
insert into resource_categories (type, resource_id) values ('eCTD', 800);
insert into resource_categories (type, resource_id) values ('Vector NTI', 394);
insert into resource_categories (type, resource_id) values ('Cisco Nexus', 424);
insert into resource_categories (type, resource_id) values ('HBSS', 619);
insert into resource_categories (type, resource_id) values ('XAMPP', 457);
insert into resource_categories (type, resource_id) values ('Economic Research', 821);
insert into resource_categories (type, resource_id) values ('Rubber', 561);
insert into resource_categories (type, resource_id) values ('xCAT', 750);
insert into resource_categories (type, resource_id) values ('HR Software', 14);
insert into resource_categories (type, resource_id) values ('Yellow Pages', 610);
insert into resource_categories (type, resource_id) values ('KDB+', 334);
insert into resource_categories (type, resource_id) values ('Managerial Finance', 103);
insert into resource_categories (type, resource_id) values ('Logging', 52);
insert into resource_categories (type, resource_id) values ('HMI Configuration', 908);
insert into resource_categories (type, resource_id) values ('XSS', 249);
insert into resource_categories (type, resource_id) values ('CD Mastering', 984);
insert into resource_categories (type, resource_id) values ('UB04', 945);
insert into resource_categories (type, resource_id) values ('WLAN', 905);
insert into resource_categories (type, resource_id) values ('Thermal Oxidizers', 266);
insert into resource_categories (type, resource_id) values ('Hotel Management', 253);
insert into resource_categories (type, resource_id) values ('JTIDS', 447);
insert into resource_categories (type, resource_id) values ('Oxidative Stress', 395);
insert into resource_categories (type, resource_id) values ('JBoss ESB', 618);
insert into resource_categories (type, resource_id) values ('ADP HRB', 929);
insert into resource_categories (type, resource_id) values ('FMLA', 764);
insert into resource_categories (type, resource_id) values ('401k Rollovers', 11);
insert into resource_categories (type, resource_id) values ('Corona SDK', 827);
insert into resource_categories (type, resource_id) values ('WDF', 50);
insert into resource_categories (type, resource_id) values ('DSI', 672);
insert into resource_categories (type, resource_id) values ('CTFL', 927);
insert into resource_categories (type, resource_id) values ('Inventory Control', 70);
insert into resource_categories (type, resource_id) values ('JCAPS', 227);
insert into resource_categories (type, resource_id) values ('HPLC-MS', 926);
insert into resource_categories (type, resource_id) values ('Smart Metering', 475);
insert into resource_categories (type, resource_id) values ('Animal Work', 117);
insert into resource_categories (type, resource_id) values ('ENOVIA LCA', 785);
insert into resource_categories (type, resource_id) values ('SSBI', 799);
insert into resource_categories (type, resource_id) values ('Timber', 733);
insert into resource_categories (type, resource_id) values ('Young Adult Literature', 875);
insert into resource_categories (type, resource_id) values ('HSE auditing', 726);
insert into resource_categories (type, resource_id) values ('Okuma', 255);
insert into resource_categories (type, resource_id) values ('IGMP', 479);
insert into resource_categories (type, resource_id) values ('LCS', 929);
insert into resource_categories (type, resource_id) values ('Office Administration', 729);
insert into resource_categories (type, resource_id) values ('Active DoD Secret Clearance', 196);
insert into resource_categories (type, resource_id) values ('Cell Biology', 364);
insert into resource_categories (type, resource_id) values ('PDMS Draft', 986);
insert into resource_categories (type, resource_id) values ('Kundalini', 536);
insert into resource_categories (type, resource_id) values ('Wireless', 39);
insert into resource_categories (type, resource_id) values ('CSA 2010', 845);
insert into resource_categories (type, resource_id) values ('CQT', 176);
insert into resource_categories (type, resource_id) values ('Norton Utilities', 375);
insert into resource_categories (type, resource_id) values ('Snort', 531);
insert into resource_categories (type, resource_id) values ('ACLS', 921);
insert into resource_categories (type, resource_id) values ('Military Justice', 890);
insert into resource_categories (type, resource_id) values ('Cell Biology', 951);
insert into resource_categories (type, resource_id) values ('Xactly', 663);
insert into resource_categories (type, resource_id) values ('Geometric Dimensioning &amp; Tolerancing', 952);
insert into resource_categories (type, resource_id) values ('HttpUnit', 581);
insert into resource_categories (type, resource_id) values ('CBEST', 758);
insert into resource_categories (type, resource_id) values ('InfoComm CTS', 327);
insert into resource_categories (type, resource_id) values ('Financial Statements', 533);
insert into resource_categories (type, resource_id) values ('MKS Integrity', 671);
insert into resource_categories (type, resource_id) values ('Personal Training', 892);
insert into resource_categories (type, resource_id) values ('RGB', 472);
insert into resource_categories (type, resource_id) values ('System Administration', 602);
insert into resource_categories (type, resource_id) values ('Family Medicine', 976);
insert into resource_categories (type, resource_id) values ('SFX Editing', 385);
insert into resource_categories (type, resource_id) values ('SRP', 694);
insert into resource_categories (type, resource_id) values ('SharePoint Server', 863);
insert into resource_categories (type, resource_id) values ('LGBT Rights', 568);
insert into resource_categories (type, resource_id) values ('TCR', 489);
insert into resource_categories (type, resource_id) values ('Client Services', 861);
insert into resource_categories (type, resource_id) values ('Character Rigging', 23);
insert into resource_categories (type, resource_id) values ('Counseling Psychology', 730);
insert into resource_categories (type, resource_id) values ('IPv6', 178);
insert into resource_categories (type, resource_id) values ('IBM Mainframe', 37);
insert into resource_categories (type, resource_id) values ('OA Framework', 743);
insert into resource_categories (type, resource_id) values ('HSM', 424);
insert into resource_categories (type, resource_id) values ('DDM', 390);
insert into resource_categories (type, resource_id) values ('ASP.NET', 991);
insert into resource_categories (type, resource_id) values ('SVT', 534);
insert into resource_categories (type, resource_id) values ('Tally ERP', 13);
insert into resource_categories (type, resource_id) values ('CFII', 718);
insert into resource_categories (type, resource_id) values ('TV series', 589);
insert into resource_categories (type, resource_id) values ('EHS', 8);
insert into resource_categories (type, resource_id) values ('HW Design', 887);
insert into resource_categories (type, resource_id) values ('Supervisory Skills', 882);
insert into resource_categories (type, resource_id) values ('Market Knowledge', 406);
insert into resource_categories (type, resource_id) values ('DV', 376);
insert into resource_categories (type, resource_id) values ('Agility', 661);
insert into resource_categories (type, resource_id) values ('Commercial Banking', 732);
insert into resource_categories (type, resource_id) values ('Lynx', 404);
insert into resource_categories (type, resource_id) values ('Fly Tying', 21);
insert into resource_categories (type, resource_id) values ('CTA', 619);
insert into resource_categories (type, resource_id) values ('Eggs', 44);
insert into resource_categories (type, resource_id) values ('RTO', 18);
insert into resource_categories (type, resource_id) values ('MDI', 268);
insert into resource_categories (type, resource_id) values ('uCOS', 463);
insert into resource_categories (type, resource_id) values ('TPL', 336);
insert into resource_categories (type, resource_id) values ('Supplier Evaluation', 124);
insert into resource_categories (type, resource_id) values ('Blues', 139);
insert into resource_categories (type, resource_id) values ('RNP', 738);
insert into resource_categories (type, resource_id) values ('UPS Shipping', 591);
insert into resource_categories (type, resource_id) values ('iPhoto', 569);
insert into resource_categories (type, resource_id) values ('Negotiation', 855);
insert into resource_categories (type, resource_id) values ('Civil Aviation', 542);
insert into resource_categories (type, resource_id) values ('SAP ERP', 148);
insert into resource_categories (type, resource_id) values ('Project Management', 107);
insert into resource_categories (type, resource_id) values ('User Experience', 321);
insert into resource_categories (type, resource_id) values ('NCover', 163);
insert into resource_categories (type, resource_id) values ('OSHA Instruction', 592);
insert into resource_categories (type, resource_id) values ('Lyric Soprano', 571);
insert into resource_categories (type, resource_id) values ('CICS', 209);
insert into resource_categories (type, resource_id) values ('Media Planning', 202);
insert into resource_categories (type, resource_id) values ('Fixed Income', 129);
insert into resource_categories (type, resource_id) values ('Omegamon', 48);
insert into resource_categories (type, resource_id) values ('Spectroscopy', 99);
insert into resource_categories (type, resource_id) values ('SVM', 762);
insert into resource_categories (type, resource_id) values ('FF&amp;E', 551);
insert into resource_categories (type, resource_id) values ('AJAX Toolkit', 304);
insert into resource_categories (type, resource_id) values ('Design Patterns', 557);
insert into resource_categories (type, resource_id) values ('MSDS', 57);
insert into resource_categories (type, resource_id) values ('WLL', 465);
insert into resource_categories (type, resource_id) values ('NDMP', 536);
insert into resource_categories (type, resource_id) values ('RTSP', 22);
insert into resource_categories (type, resource_id) values ('DMMs', 645);
insert into resource_categories (type, resource_id) values ('BSC', 577);
insert into resource_categories (type, resource_id) values ('Internet Yellow Pages', 51);
insert into resource_categories (type, resource_id) values ('XP Professional', 649);
insert into resource_categories (type, resource_id) values ('Offshoring', 567);
insert into resource_categories (type, resource_id) values ('Petrochemical', 251);
insert into resource_categories (type, resource_id) values ('Yard Signs', 524);
insert into resource_categories (type, resource_id) values ('LSP', 79);
insert into resource_categories (type, resource_id) values ('Cvent', 951);
insert into resource_categories (type, resource_id) values ('OLAP Cube Studio', 456);
insert into resource_categories (type, resource_id) values ('Social Media', 27);
insert into resource_categories (type, resource_id) values ('IT Strategy', 698);
insert into resource_categories (type, resource_id) values ('IT Recruitment', 217);
insert into resource_categories (type, resource_id) values ('International NGOs', 97);
insert into resource_categories (type, resource_id) values ('Integration', 283);
insert into resource_categories (type, resource_id) values ('Thermal Oxidizers', 34);
insert into resource_categories (type, resource_id) values ('Errors &amp; Omissions', 950);
insert into resource_categories (type, resource_id) values ('WC', 68);
insert into resource_categories (type, resource_id) values ('Kontakt', 633);
insert into resource_categories (type, resource_id) values ('LLC', 452);
insert into resource_categories (type, resource_id) values ('Private Equity', 860);
insert into resource_categories (type, resource_id) values ('UltraTax', 375);
insert into resource_categories (type, resource_id) values ('KWP2000', 670);
insert into resource_categories (type, resource_id) values ('Data Warehousing', 576);
insert into resource_categories (type, resource_id) values ('Lecturing', 597);
insert into resource_categories (type, resource_id) values ('Device Drivers', 695);
insert into resource_categories (type, resource_id) values ('Yacht Deliveries', 894);
insert into resource_categories (type, resource_id) values ('WBTs', 126);
insert into resource_categories (type, resource_id) values ('Photojournalism', 805);
insert into resource_categories (type, resource_id) values ('CGEIT', 7);
insert into resource_categories (type, resource_id) values ('TSCA', 24);
insert into resource_categories (type, resource_id) values ('Crisis Communications', 155);
insert into resource_categories (type, resource_id) values ('Computer Graphics', 738);
insert into resource_categories (type, resource_id) values ('TPM', 411);
insert into resource_categories (type, resource_id) values ('UV', 972);
insert into resource_categories (type, resource_id) values ('Business Owner Planning', 703);
insert into resource_categories (type, resource_id) values ('Test Planning', 534);
insert into resource_categories (type, resource_id) values ('Job Search Strategies', 996);
insert into resource_categories (type, resource_id) values ('Tally ERP', 524);
insert into resource_categories (type, resource_id) values ('Real Estate Financing', 176);
insert into resource_categories (type, resource_id) values ('Theatre', 817);
insert into resource_categories (type, resource_id) values ('NREMT', 246);
insert into resource_categories (type, resource_id) values ('Gastroenterology', 764);
insert into resource_categories (type, resource_id) values ('Cyber-security', 31);
insert into resource_categories (type, resource_id) values ('Hypnotherapy', 989);
insert into resource_categories (type, resource_id) values ('Economic Research', 274);
insert into resource_categories (type, resource_id) values ('5 Why', 897);
insert into resource_categories (type, resource_id) values ('OMB Circular A-133', 84);
insert into resource_categories (type, resource_id) values ('Process Scheduler', 567);
insert into resource_categories (type, resource_id) values ('FDICIA', 97);
insert into resource_categories (type, resource_id) values ('Brain Gym', 448);
insert into resource_categories (type, resource_id) values ('Manual Therapy', 285);
insert into resource_categories (type, resource_id) values ('Military Logistics', 97);
insert into resource_categories (type, resource_id) values ('Sports Writing', 750);
insert into resource_categories (type, resource_id) values ('Lean Manufacturing', 207);
insert into resource_categories (type, resource_id) values ('Smart GWT', 200);
insert into resource_categories (type, resource_id) values ('NBS Specification', 321);
insert into resource_categories (type, resource_id) values ('IOS-XR', 427);
insert into resource_categories (type, resource_id) values ('Blender', 880);
insert into resource_categories (type, resource_id) values ('IKE', 143);
insert into resource_categories (type, resource_id) values ('Xbox', 754);
insert into resource_categories (type, resource_id) values ('Ships', 802);
insert into resource_categories (type, resource_id) values ('Quantitative Analytics', 236);
insert into resource_categories (type, resource_id) values ('Sustainable Agriculture', 369);
insert into resource_categories (type, resource_id) values ('Environmental Awareness', 270);
insert into resource_categories (type, resource_id) values ('Compliance Oversight', 356);
insert into resource_categories (type, resource_id) values ('Data Mining', 114);
insert into resource_categories (type, resource_id) values ('Small Boat Operations', 268);
insert into resource_categories (type, resource_id) values ('Lyra', 730);
insert into resource_categories (type, resource_id) values ('Civil Engineering', 514);
insert into resource_categories (type, resource_id) values ('GMDSS', 269);
insert into resource_categories (type, resource_id) values ('AAR', 121);
insert into resource_categories (type, resource_id) values ('RCMS', 940);
insert into resource_categories (type, resource_id) values ('Otoplasty', 333);
insert into resource_categories (type, resource_id) values ('Abstraction', 459);
insert into resource_categories (type, resource_id) values ('Process Automation', 544);
insert into resource_categories (type, resource_id) values ('ArcGIS', 903);
insert into resource_categories (type, resource_id) values ('MHP', 936);
insert into resource_categories (type, resource_id) values ('BMC Portal', 950);
insert into resource_categories (type, resource_id) values ('Qik', 792);
insert into resource_categories (type, resource_id) values ('First Aid', 260);
insert into resource_categories (type, resource_id) values ('Titration', 92);
insert into resource_categories (type, resource_id) values ('DMP', 293);
insert into resource_categories (type, resource_id) values ('LPI', 362);
insert into resource_categories (type, resource_id) values ('FM200', 928);
insert into resource_categories (type, resource_id) values ('Facilities Management', 891);
insert into resource_categories (type, resource_id) values ('RP', 146);
insert into resource_categories (type, resource_id) values ('FDM', 362);
insert into resource_categories (type, resource_id) values ('Kyocera', 919);
insert into resource_categories (type, resource_id) values ('Organization Skills', 906);
insert into resource_categories (type, resource_id) values ('OSHA Instruction', 747);
insert into resource_categories (type, resource_id) values ('Editing', 518);
insert into resource_categories (type, resource_id) values ('Beauty Industry', 295);
insert into resource_categories (type, resource_id) values ('eCTD', 966);
insert into resource_categories (type, resource_id) values ('NGOs', 839);
insert into resource_categories (type, resource_id) values ('Unreal Editor', 839);
insert into resource_categories (type, resource_id) values ('Valves', 853);
insert into resource_categories (type, resource_id) values ('FSA', 166);
insert into resource_categories (type, resource_id) values ('Museum Collections', 5);
insert into resource_categories (type, resource_id) values ('HRIS Database Management', 235);
insert into resource_categories (type, resource_id) values ('Yin Yoga', 784);
insert into resource_categories (type, resource_id) values ('Peer Tutoring', 214);
insert into resource_categories (type, resource_id) values ('Title Searches', 17);
insert into resource_categories (type, resource_id) values ('Management by Objectives', 678);
insert into resource_categories (type, resource_id) values ('Wwise', 786);
insert into resource_categories (type, resource_id) values ('Critical Illness', 252);
insert into resource_categories (type, resource_id) values ('Valves', 995);
insert into resource_categories (type, resource_id) values ('Policy', 514);
insert into resource_categories (type, resource_id) values ('Unreal Engine 3', 183);
insert into resource_categories (type, resource_id) values ('Zotero', 77);
insert into resource_categories (type, resource_id) values ('Physical Oceanography', 951);
insert into resource_categories (type, resource_id) values ('European History', 387);
insert into resource_categories (type, resource_id) values ('PyMEL', 174);
insert into resource_categories (type, resource_id) values ('Apache ZooKeeper', 8);
insert into resource_categories (type, resource_id) values ('TK Solver', 786);
insert into resource_categories (type, resource_id) values ('Branding', 833);
insert into resource_categories (type, resource_id) values ('MSBuild', 587);
insert into resource_categories (type, resource_id) values ('Switches', 105);
insert into resource_categories (type, resource_id) values ('Yahoo Search', 933);
insert into resource_categories (type, resource_id) values ('Human Capital', 257);
insert into resource_categories (type, resource_id) values ('Ethnography', 597);
insert into resource_categories (type, resource_id) values ('Avid Newscutter', 503);
insert into resource_categories (type, resource_id) values ('Vegetables', 571);
insert into resource_categories (type, resource_id) values ('Pyrometallurgy', 377);
insert into resource_categories (type, resource_id) values ('DVB-S', 588);
insert into resource_categories (type, resource_id) values ('Entrepreneurship', 709);
insert into resource_categories (type, resource_id) values ('Airport Management', 717);
insert into resource_categories (type, resource_id) values ('Document Drafting', 39);
insert into resource_categories (type, resource_id) values ('Life Cycle Assessment', 642);
insert into resource_categories (type, resource_id) values ('Interactive Whiteboard', 870);
insert into resource_categories (type, resource_id) values ('Financial Planning', 947);
insert into resource_categories (type, resource_id) values ('Eggs', 73);
insert into resource_categories (type, resource_id) values ('Xpress', 370);
insert into resource_categories (type, resource_id) values ('CSS', 500);
insert into resource_categories (type, resource_id) values ('Oncology', 769);
insert into resource_categories (type, resource_id) values ('IGMP Snooping', 441);
insert into resource_categories (type, resource_id) values ('Visual Effects', 301);
insert into resource_categories (type, resource_id) values ('Overseas Production', 335);
insert into resource_categories (type, resource_id) values ('Turbo C++', 923);
insert into resource_categories (type, resource_id) values ('IBM iSeries', 799);
insert into resource_categories (type, resource_id) values ('HTC', 973);
insert into resource_categories (type, resource_id) values ('Social Media Blogging', 436);
insert into resource_categories (type, resource_id) values ('GT-Power', 156);
insert into resource_categories (type, resource_id) values ('DGFT', 161);
insert into resource_categories (type, resource_id) values ('Special Education', 72);
insert into resource_categories (type, resource_id) values ('UNIX Utilities', 411);
insert into resource_categories (type, resource_id) values ('IT Project &amp; Program Management', 479);
insert into resource_categories (type, resource_id) values ('Earth Science', 471);
insert into resource_categories (type, resource_id) values ('DCL', 556);
insert into resource_categories (type, resource_id) values ('GS1', 83);
insert into resource_categories (type, resource_id) values ('Ruby', 168);
insert into resource_categories (type, resource_id) values ('Xing', 60);
insert into resource_categories (type, resource_id) values ('Fashion Illustration', 349);
insert into resource_categories (type, resource_id) values ('Production Efficiency', 658);
insert into resource_categories (type, resource_id) values ('Omniture', 388);
