insert into resource_categories (type, resource_id) values ('Russian ', 54);
insert into resource_categories (type, resource_id) values ('Geology ', 44);
insert into resource_categories (type, resource_id) values ('Economics ', 31);
insert into resource_categories (type, resource_id) values ('History ', 7);
insert into resource_categories (type, resource_id) values ('Arabic ', 79);
insert into resource_categories (type, resource_id) values ('Neuropsychology ', 3);
insert into resource_categories (type, resource_id) values ('Neuropsychology ', 30);
insert into resource_categories (type, resource_id) values ('History ', 72);
insert into resource_categories (type, resource_id) values ('Behavioural Psychology ', 70);
insert into resource_categories (type, resource_id) values (' Business ', 32);
insert into resource_categories (type, resource_id) values (' Mathematics ', 78);
insert into resource_categories (type, resource_id) values (' Mathematics ', 76);
insert into resource_categories (type, resource_id) values (' Inorganic Chemistry ', 81);
insert into resource_categories (type, resource_id) values (' Physiology ', 1);
insert into resource_categories (type, resource_id) values (' Astrophysics ', 86);
insert into resource_categories (type, resource_id) values (' Astrophysics ', 29);
insert into resource_categories (type, resource_id) values (' Russian ', 93);
insert into resource_categories (type, resource_id) values (' Classics ', 93);
insert into resource_categories (type, resource_id) values (' Mathematics ', 25);
insert into resource_categories (type, resource_id) values (' Sociology ', 85);
insert into resource_categories (type, resource_id) values (' Astronomy ', 35);
insert into resource_categories (type, resource_id) values (' Sociology ', 26);
insert into resource_categories (type, resource_id) values (' French ', 25);
insert into resource_categories (type, resource_id) values (' Arabic ', 46);
insert into resource_categories (type, resource_id) values (' English ', 54);
insert into resource_categories (type, resource_id) values (' Sociology ', 82);
insert into resource_categories (type, resource_id) values (' Marine Biology ', 52);
insert into resource_categories (type, resource_id) values (' Microbiology ', 13);
insert into resource_categories (type, resource_id) values (' Russian ', 91);
insert into resource_categories (type, resource_id) values (' Economics ', 26);
insert into resource_categories (type, resource_id) values ('History ', 36);
insert into resource_categories (type, resource_id) values ('Geophysics ', 97);
insert into resource_categories (type, resource_id) values ('Literature ', 83);
insert into resource_categories (type, resource_id) values ('Anthropology ', 76);
insert into resource_categories (type, resource_id) values ('Cognitive Psychology ', 7);
insert into resource_categories (type, resource_id) values ('English ', 66);
insert into resource_categories (type, resource_id) values ('Literature ', 12);
insert into resource_categories (type, resource_id) values ('Cell Biology ', 93);
insert into resource_categories (type, resource_id) values ('Philosophy ', 54);
insert into resource_categories (type, resource_id) values ('Language ', 33);
insert into resource_categories (type, resource_id) values ('Physics ', 37);
insert into resource_categories (type, resource_id) values ('Arabic ', 55);
insert into resource_categories (type, resource_id) values ('Linguistics ', 33);
insert into resource_categories (type, resource_id) values ('Science ', 46);
insert into resource_categories (type, resource_id) values ('Geography ', 53);
insert into resource_categories (type, resource_id) values ('Geography ', 50);
insert into resource_categories (type, resource_id) values ('German ', 95);
insert into resource_categories (type, resource_id) values ('Marine Biology ', 89);
insert into resource_categories (type, resource_id) values ('Physiology ', 21);
insert into resource_categories (type, resource_id) values ('Inorganic Chemistry ', 90);
insert into resource_categories (type, resource_id) values ('Macroeconomics ', 20);
insert into resource_categories (type, resource_id) values ('Geophysics ', 90);
insert into resource_categories (type, resource_id) values ('Ancient History ', 92);
insert into resource_categories (type, resource_id) values ('Geology ', 74);
insert into resource_categories (type, resource_id) values ('Russian ', 2);
insert into resource_categories (type, resource_id) values ('Geophysics ', 74);
insert into resource_categories (type, resource_id) values ('German ', 4);
insert into resource_categories (type, resource_id) values ('Literature ', 35);
insert into resource_categories (type, resource_id) values ('Psychology', 78);
insert into resource_categories (type, resource_id) values ('Cell Biology ', 72);
insert into resource_categories (type, resource_id) values ('German ', 62);
insert into resource_categories (type, resource_id) values ('Spanish ', 44);
insert into resource_categories (type, resource_id) values ('Physiology ', 15);
insert into resource_categories (type, resource_id) values ('Ancient History ', 86);
insert into resource_categories (type, resource_id) values ('Microeconomics ', 10);
insert into resource_categories (type, resource_id) values ('Astrophysics ', 15);
insert into resource_categories (type, resource_id) values ('Macroeconomics ', 65);
insert into resource_categories (type, resource_id) values ('History ', 21);
insert into resource_categories (type, resource_id) values ('Microeconomics', 45);
insert into resource_categories (type, resource_id) values ('English', 12);
insert into resource_categories (type, resource_id) values ('Microbiology', 47);
insert into resource_categories (type, resource_id) values ('Neuroscience', 87);
insert into resource_categories (type, resource_id) values ('Geography', 30);
insert into resource_categories (type, resource_id) values ('Cognitive Psychology', 55);
insert into resource_categories (type, resource_id) values ('Geology', 55);
insert into resource_categories (type, resource_id) values ('Inorganic Chemistry', 99);
insert into resource_categories (type, resource_id) values ('Neuroscience', 44);
insert into resource_categories (type, resource_id) values ('Neuropsychology', 96);
insert into resource_categories (type, resource_id) values ('Philosophy', 99);
insert into resource_categories (type, resource_id) values ('Language', 30);
insert into resource_categories (type, resource_id) values ('History', 11);
insert into resource_categories (type, resource_id) values ('Cell Biology', 80);
insert into resource_categories (type, resource_id) values ('Geography', 22);
insert into resource_categories (type, resource_id) values ('Russian', 66);
insert into resource_categories (type, resource_id) values ('History', 69);
insert into resource_categories (type, resource_id) values ('Classics', 51);
insert into resource_categories (type, resource_id) values ('Literature', 79);
insert into resource_categories (type, resource_id) values ('English', 28);
insert into resource_categories (type, resource_id) values ('German', 2);
insert into resource_categories (type, resource_id) values ('Linguistics', 22);
insert into resource_categories (type, resource_id) values ('Language', 24);
insert into resource_categories (type, resource_id) values ('Anthropology', 55);
insert into resource_categories (type, resource_id) values ('Mathematics', 25);
insert into resource_categories (type, resource_id) values ('Psychology', 25);
insert into resource_categories (type, resource_id) values ('Mandarin', 52);
insert into resource_categories (type, resource_id) values ('Business', 23);
insert into resource_categories (type, resource_id) values ('French', 24);
insert into resource_categories (type, resource_id) values ('Spanish', 47);
insert into resource_categories (type, resource_id) values ('Astronomy', 10);
insert into resource_categories (type, resource_id) values ('Geography', 4);
