insert into resource_categories (type, resource_id) values ('PDMS', '156');
insert into resource_categories (type, resource_id) values ('Hatha Yoga', '238');
insert into resource_categories (type, resource_id) values ('XaaS', '127');
insert into resource_categories (type, resource_id) values ('Purchase Management', '317');
insert into resource_categories (type, resource_id) values ('CSS Sprites', '355');
insert into resource_categories (type, resource_id) values ('UV', '479');
insert into resource_categories (type, resource_id) values ('MyBatis', '63');
insert into resource_categories (type, resource_id) values ('Topographic Surveys', '252');
insert into resource_categories (type, resource_id) values ('EFTPOS', '273');
insert into resource_categories (type, resource_id) values ('Accounts Payable', '141');
insert into resource_categories (type, resource_id) values ('Eyewonder', '223');
insert into resource_categories (type, resource_id) values ('Bioinformatics', '269');
insert into resource_categories (type, resource_id) values ('MTA', '132');
insert into resource_categories (type, resource_id) values ('Indoor Air Quality', '38');
insert into resource_categories (type, resource_id) values ('UTP', '276');
insert into resource_categories (type, resource_id) values ('Tomcat', '161');
insert into resource_categories (type, resource_id) values ('Classical', '88');
insert into resource_categories (type, resource_id) values ('Hardware Diagnostics', '108');
insert into resource_categories (type, resource_id) values ('Software Project Management', '495');
insert into resource_categories (type, resource_id) values ('TyMetrix', '147');
insert into resource_categories (type, resource_id) values ('Tenacious Work Ethic', '452');
insert into resource_categories (type, resource_id) values ('Kernel Programming', '278');
insert into resource_categories (type, resource_id) values ('PDM', '434');
insert into resource_categories (type, resource_id) values ('Small Business', '341');
insert into resource_categories (type, resource_id) values ('MRO Management', '468');
insert into resource_categories (type, resource_id) values ('Dog Training', '75');
insert into resource_categories (type, resource_id) values ('Loans', '448');
insert into resource_categories (type, resource_id) values ('GMLAN', '147');
insert into resource_categories (type, resource_id) values ('Festivals', '233');
insert into resource_categories (type, resource_id) values ('OTDR', '354');
insert into resource_categories (type, resource_id) values ('HMI Configuration', '219');
insert into resource_categories (type, resource_id) values ('Topographic Surveys', '433');
insert into resource_categories (type, resource_id) values ('SDL', '193');
insert into resource_categories (type, resource_id) values ('BDMS', '126');
insert into resource_categories (type, resource_id) values ('NTFS', '203');
insert into resource_categories (type, resource_id) values ('Credit Risk', '203');
insert into resource_categories (type, resource_id) values ('OAS Gold', '477');
insert into resource_categories (type, resource_id) values ('HW Design', '300');
insert into resource_categories (type, resource_id) values ('Oasys', '38');
insert into resource_categories (type, resource_id) values ('SQL*Plus', '43');
insert into resource_categories (type, resource_id) values ('Tax', '476');
insert into resource_categories (type, resource_id) values ('Xeriscaping', '498');
insert into resource_categories (type, resource_id) values ('XRR', '225');
insert into resource_categories (type, resource_id) values ('Athletic Training', '373');
insert into resource_categories (type, resource_id) values ('WCS', '445');
insert into resource_categories (type, resource_id) values ('RSView', '416');
insert into resource_categories (type, resource_id) values ('Editing', '177');
insert into resource_categories (type, resource_id) values ('Zemax', '337');
insert into resource_categories (type, resource_id) values ('NCFM Certified', '354');
insert into resource_categories (type, resource_id) values ('Zeus', '346');
insert into resource_categories (type, resource_id) values ('Gifts', '140');
insert into resource_categories (type, resource_id) values ('Aircraft Design', '466');
insert into resource_categories (type, resource_id) values ('Pthreads', '461');
insert into resource_categories (type, resource_id) values ('BTL Activations', '222');
insert into resource_categories (type, resource_id) values ('SMTP', '240');
insert into resource_categories (type, resource_id) values ('FTIR', '261');
insert into resource_categories (type, resource_id) values ('PostgreSQL', '91');
insert into resource_categories (type, resource_id) values ('Trade Shows', '358');
insert into resource_categories (type, resource_id) values ('UHF', '489');
insert into resource_categories (type, resource_id) values ('Twitter API', '140');
insert into resource_categories (type, resource_id) values ('MVS', '280');
insert into resource_categories (type, resource_id) values ('WTP', '299');
insert into resource_categories (type, resource_id) values ('Petroleum', '224');
insert into resource_categories (type, resource_id) values ('Music Videos', '333');
insert into resource_categories (type, resource_id) values ('BGP', '223');
insert into resource_categories (type, resource_id) values ('Branding', '304');
insert into resource_categories (type, resource_id) values ('SSO', '21');
insert into resource_categories (type, resource_id) values ('LN', '170');
insert into resource_categories (type, resource_id) values ('VDI', '129');
insert into resource_categories (type, resource_id) values ('Cyber-security', '475');
insert into resource_categories (type, resource_id) values ('Diabetes', '283');
insert into resource_categories (type, resource_id) values ('Underground Mining', '367');
insert into resource_categories (type, resource_id) values ('Young People', '4');
insert into resource_categories (type, resource_id) values ('Guardianship', '309');
insert into resource_categories (type, resource_id) values ('FFA', '384');
insert into resource_categories (type, resource_id) values ('Computer Games', '370');
insert into resource_categories (type, resource_id) values ('Hydrography', '423');
insert into resource_categories (type, resource_id) values ('Loss Prevention', '494');
insert into resource_categories (type, resource_id) values ('IGRT', '2');
insert into resource_categories (type, resource_id) values ('Content Strategy', '34');
insert into resource_categories (type, resource_id) values ('Geography', '475');
insert into resource_categories (type, resource_id) values ('Clinical Psychology', '272');
insert into resource_categories (type, resource_id) values ('FCRA', '119');
insert into resource_categories (type, resource_id) values ('FPC 1', '133');
insert into resource_categories (type, resource_id) values ('SBEM', '39');
insert into resource_categories (type, resource_id) values ('DSLR', '134');
insert into resource_categories (type, resource_id) values ('Underground Mining', '464');
insert into resource_categories (type, resource_id) values ('FCC License', '472');
insert into resource_categories (type, resource_id) values ('Family Medicine', '398');
insert into resource_categories (type, resource_id) values ('Offshoring', '403');
insert into resource_categories (type, resource_id) values ('Nanoparticles', '295');
insert into resource_categories (type, resource_id) values ('OMAP', '322');
insert into resource_categories (type, resource_id) values ('Art Direction', '222');
insert into resource_categories (type, resource_id) values ('TJC', '70');
insert into resource_categories (type, resource_id) values ('IP VPN', '140');
insert into resource_categories (type, resource_id) values ('Medicine', '108');
insert into resource_categories (type, resource_id) values ('Rollout', '401');
insert into resource_categories (type, resource_id) values ('XTRACT', '172');
insert into resource_categories (type, resource_id) values ('PJM', '61');
insert into resource_categories (type, resource_id) values ('IOS Firewall', '406');
insert into resource_categories (type, resource_id) values ('JiBX', '326');
insert into resource_categories (type, resource_id) values ('Gstreamer', '91');
insert into resource_categories (type, resource_id) values ('JCAHO', '434');
insert into resource_categories (type, resource_id) values ('HDPE', '272');
insert into resource_categories (type, resource_id) values ('Eclipse', '123');
insert into resource_categories (type, resource_id) values ('Air Quality', '71');
insert into resource_categories (type, resource_id) values ('SolidWorks', '22');
insert into resource_categories (type, resource_id) values ('Twilio', '86');
insert into resource_categories (type, resource_id) values ('Tcsh', '308');
insert into resource_categories (type, resource_id) values ('Road', '355');
insert into resource_categories (type, resource_id) values ('Electrical Troubleshooting', '322');
insert into resource_categories (type, resource_id) values ('Vulnerability Management', '278');
insert into resource_categories (type, resource_id) values ('Chromatography', '410');
insert into resource_categories (type, resource_id) values ('Volleyball', '339');
insert into resource_categories (type, resource_id) values ('qRT-PCR', '467');
insert into resource_categories (type, resource_id) values ('BPWin', '239');
insert into resource_categories (type, resource_id) values ('Working Abroad', '338');
insert into resource_categories (type, resource_id) values ('SLA', '305');
insert into resource_categories (type, resource_id) values ('Combined Cycle', '427');
insert into resource_categories (type, resource_id) values ('Post Production', '69');
insert into resource_categories (type, resource_id) values ('Electric Utility', '478');
insert into resource_categories (type, resource_id) values ('Short Stories', '84');
insert into resource_categories (type, resource_id) values ('HSI', '13');
insert into resource_categories (type, resource_id) values ('PKMS', '257');
insert into resource_categories (type, resource_id) values ('HCFA', '307');
insert into resource_categories (type, resource_id) values ('Hand Knitting', '77');
insert into resource_categories (type, resource_id) values ('What-if Analysis', '376');
insert into resource_categories (type, resource_id) values ('DMU', '160');
insert into resource_categories (type, resource_id) values ('GC-FID', '355');
insert into resource_categories (type, resource_id) values ('Zeolites', '132');
insert into resource_categories (type, resource_id) values ('eHRPD', '337');
insert into resource_categories (type, resource_id) values ('ABR', '267');
insert into resource_categories (type, resource_id) values ('OMT', '213');
insert into resource_categories (type, resource_id) values ('Working Abroad', '93');
insert into resource_categories (type, resource_id) values ('Radar', '489');
insert into resource_categories (type, resource_id) values ('UFC', '336');
insert into resource_categories (type, resource_id) values ('MRPII', '341');
insert into resource_categories (type, resource_id) values ('Google Webmaster Tools', '324');
insert into resource_categories (type, resource_id) values ('Ducting', '307');
insert into resource_categories (type, resource_id) values ('Zeta Potential', '408');
insert into resource_categories (type, resource_id) values ('Member of IEEE', '281');
insert into resource_categories (type, resource_id) values ('Oil Painting', '408');
insert into resource_categories (type, resource_id) values ('OWA', '365');
insert into resource_categories (type, resource_id) values ('NCIC', '201');
insert into resource_categories (type, resource_id) values ('RF', '180');
insert into resource_categories (type, resource_id) values ('User Scenarios', '297');
insert into resource_categories (type, resource_id) values ('SPSS', '142');
insert into resource_categories (type, resource_id) values ('Brand Equity', '215');
insert into resource_categories (type, resource_id) values ('CDL Class A', '373');
insert into resource_categories (type, resource_id) values ('Physics', '377');
insert into resource_categories (type, resource_id) values ('Branding &amp; Identity', '182');
insert into resource_categories (type, resource_id) values ('Pensions', '330');
insert into resource_categories (type, resource_id) values ('Directing Others', '161');
insert into resource_categories (type, resource_id) values ('Claim', '234');
insert into resource_categories (type, resource_id) values ('Software Testing Life Cycle', '22');
insert into resource_categories (type, resource_id) values ('MPEG2', '230');
insert into resource_categories (type, resource_id) values ('VTR', '416');
insert into resource_categories (type, resource_id) values ('Japanese', '397');
insert into resource_categories (type, resource_id) values ('Blogger', '293');
insert into resource_categories (type, resource_id) values ('Kaspersky', '19');
insert into resource_categories (type, resource_id) values ('Evangelism', '200');
insert into resource_categories (type, resource_id) values ('SWIFT Messaging', '405');
insert into resource_categories (type, resource_id) values ('Rugs', '232');
insert into resource_categories (type, resource_id) values ('Slovak', '57');
insert into resource_categories (type, resource_id) values ('Equipment Repair', '425');
insert into resource_categories (type, resource_id) values ('EOU', '83');
insert into resource_categories (type, resource_id) values ('UV', '172');
insert into resource_categories (type, resource_id) values ('Wellbeing', '');
insert into resource_categories (type, resource_id) values ('Close Protection', '334');
insert into resource_categories (type, resource_id) values ('Lubrication', '373');
insert into resource_categories (type, resource_id) values ('EIFS', '25');
insert into resource_categories (type, resource_id) values ('Nios II', '390');
insert into resource_categories (type, resource_id) values ('Pymol', '43');
insert into resource_categories (type, resource_id) values ('Philanthropy', '368');
insert into resource_categories (type, resource_id) values ('Hypnosis', '146');
insert into resource_categories (type, resource_id) values ('IEC 60601', '291');
insert into resource_categories (type, resource_id) values ('GPP', '496');
insert into resource_categories (type, resource_id) values ('Outdoor Recreation', '203');
insert into resource_categories (type, resource_id) values ('Axys', '268');
insert into resource_categories (type, resource_id) values ('Technical Illustration', '159');
insert into resource_categories (type, resource_id) values ('Bylined Articles', '225');
insert into resource_categories (type, resource_id) values ('Programming', '168');
insert into resource_categories (type, resource_id) values ('IO', '244');
insert into resource_categories (type, resource_id) values ('RRSP', '261');
insert into resource_categories (type, resource_id) values ('Fashion Design', '283');
insert into resource_categories (type, resource_id) values ('SBS', '115');
insert into resource_categories (type, resource_id) values ('iPhoto', '111');
insert into resource_categories (type, resource_id) values ('UK GAAP', '336');
insert into resource_categories (type, resource_id) values ('TTD', '423');
insert into resource_categories (type, resource_id) values ('Agile Application Development', '65');
insert into resource_categories (type, resource_id) values ('Zemax', '192');
insert into resource_categories (type, resource_id) values ('HCS12', '64');
insert into resource_categories (type, resource_id) values ('Ultiboard', '426');
insert into resource_categories (type, resource_id) values ('CVA', '89');
insert into resource_categories (type, resource_id) values ('Xplan', '245');
insert into resource_categories (type, resource_id) values ('Avaya Communication Manager', '104');
insert into resource_categories (type, resource_id) values ('MLOAD', '453');
insert into resource_categories (type, resource_id) values ('YUM', '425');
insert into resource_categories (type, resource_id) values ('Oracle Identity Manager', '213');
insert into resource_categories (type, resource_id) values ('BTLS', '490');
insert into resource_categories (type, resource_id) values ('Aerospace', '53');
insert into resource_categories (type, resource_id) values ('CNC Operation', '320');
insert into resource_categories (type, resource_id) values ('XPS', '158');
insert into resource_categories (type, resource_id) values ('Customer Satisfaction', '182');
insert into resource_categories (type, resource_id) values ('Structural Dynamics', '473');
insert into resource_categories (type, resource_id) values ('Lead Generation', '368');
insert into resource_categories (type, resource_id) values ('ISO 22000', '122');
insert into resource_categories (type, resource_id) values ('VCL', '436');
insert into resource_categories (type, resource_id) values ('GFS', '267');
insert into resource_categories (type, resource_id) values ('Performance Improvement', '237');
insert into resource_categories (type, resource_id) values ('Sports Marketing', '305');
insert into resource_categories (type, resource_id) values ('UL', '150');
insert into resource_categories (type, resource_id) values ('Ultrasonic Testing', '260');
insert into resource_categories (type, resource_id) values ('Kanban', '67');
insert into resource_categories (type, resource_id) values ('TK Solver', '449');
insert into resource_categories (type, resource_id) values ('Software Development', '68');
insert into resource_categories (type, resource_id) values ('Year End Accounts', '233');
insert into resource_categories (type, resource_id) values ('Teeth Whitening', '436');
insert into resource_categories (type, resource_id) values ('VRRP', '340');
insert into resource_categories (type, resource_id) values ('Turbo Pascal', '171');
insert into resource_categories (type, resource_id) values ('Jenkins', '453');
insert into resource_categories (type, resource_id) values ('Consulting', '343');
insert into resource_categories (type, resource_id) values ('Yardi', '81');
insert into resource_categories (type, resource_id) values ('VSS', '215');
insert into resource_categories (type, resource_id) values ('PET-CT', '301');
insert into resource_categories (type, resource_id) values ('DXL', '209');
insert into resource_categories (type, resource_id) values ('Simulink', '369');
insert into resource_categories (type, resource_id) values ('XNA', '227');
insert into resource_categories (type, resource_id) values ('XTRAC', '153');
insert into resource_categories (type, resource_id) values ('Secretarial Skills', '445');
insert into resource_categories (type, resource_id) values ('Project Bidding', '15');
insert into resource_categories (type, resource_id) values ('CQT', '14');
insert into resource_categories (type, resource_id) values ('Research', '490');
insert into resource_categories (type, resource_id) values ('MDT', '364');
insert into resource_categories (type, resource_id) values ('Participant Observation', '24');
insert into resource_categories (type, resource_id) values ('Animation', '10');
insert into resource_categories (type, resource_id) values ('Service Delivery', '163');
insert into resource_categories (type, resource_id) values ('Published Author', '251');
insert into resource_categories (type, resource_id) values ('MBS', '400');
insert into resource_categories (type, resource_id) values ('AJAX', '37');
insert into resource_categories (type, resource_id) values ('GPS Devices', '61');
insert into resource_categories (type, resource_id) values ('NHL', '455');
insert into resource_categories (type, resource_id) values ('Mobile Marketing', '66');
insert into resource_categories (type, resource_id) values ('NLog', '420');
insert into resource_categories (type, resource_id) values ('Cycle Counting', '89');
insert into resource_categories (type, resource_id) values ('RTC', '235');
insert into resource_categories (type, resource_id) values ('WCF Services', '500');
insert into resource_categories (type, resource_id) values ('Aquatic Ecology', '22');
insert into resource_categories (type, resource_id) values ('DTT', '325');
insert into resource_categories (type, resource_id) values ('eZ Publish', '318');
insert into resource_categories (type, resource_id) values ('xCP', '88');
insert into resource_categories (type, resource_id) values ('MyEclipse', '373');
insert into resource_categories (type, resource_id) values ('Tactics', '107');
insert into resource_categories (type, resource_id) values ('Capital Equipment Sales', '324');
insert into resource_categories (type, resource_id) values ('VTP', '');
insert into resource_categories (type, resource_id) values ('NSE', '182');
insert into resource_categories (type, resource_id) values ('Situational Awareness', '274');
insert into resource_categories (type, resource_id) values ('ebXML', '29');
insert into resource_categories (type, resource_id) values ('Twitter API', '143');
insert into resource_categories (type, resource_id) values ('DMX', '55');
insert into resource_categories (type, resource_id) values ('SDL', '486');
insert into resource_categories (type, resource_id) values ('People Management', '170');
insert into resource_categories (type, resource_id) values ('Routers', '99');
insert into resource_categories (type, resource_id) values ('Pyrometallurgy', '217');
insert into resource_categories (type, resource_id) values ('Airframe', '415');
insert into resource_categories (type, resource_id) values ('Embedded SQL', '206');
insert into resource_categories (type, resource_id) values ('MMSC', '292');
insert into resource_categories (type, resource_id) values ('Universal Life', '253');
insert into resource_categories (type, resource_id) values ('International Relations', '469');
insert into resource_categories (type, resource_id) values ('ICT Governance', '16');
insert into resource_categories (type, resource_id) values ('Switchboard', '141');
insert into resource_categories (type, resource_id) values ('Infor XA', '264');
insert into resource_categories (type, resource_id) values ('YUI', '232');
insert into resource_categories (type, resource_id) values ('Workshop Facilitation', '259');
insert into resource_categories (type, resource_id) values ('HTTPS', '55');
insert into resource_categories (type, resource_id) values ('Front Office', '443');
insert into resource_categories (type, resource_id) values ('QALoad', '215');
insert into resource_categories (type, resource_id) values ('Funding', '307');
insert into resource_categories (type, resource_id) values ('Embedded Software', '100');
insert into resource_categories (type, resource_id) values ('Vi', '9');
insert into resource_categories (type, resource_id) values ('Shotokan Karate', '272');
insert into resource_categories (type, resource_id) values ('CNC Machine', '12');
insert into resource_categories (type, resource_id) values ('RDBMS', '408');
insert into resource_categories (type, resource_id) values ('xCAT', '247');
insert into resource_categories (type, resource_id) values ('RBAC', '40');
insert into resource_categories (type, resource_id) values ('Gourmet', '107');
insert into resource_categories (type, resource_id) values ('DDoS', '78');
insert into resource_categories (type, resource_id) values ('Pharmaceutics', '404');
insert into resource_categories (type, resource_id) values ('HW/SW integration', '376');
insert into resource_categories (type, resource_id) values ('PCI Standards', '431');
insert into resource_categories (type, resource_id) values ('LCR', '434');
insert into resource_categories (type, resource_id) values ('JDE Enterprise One', '414');
insert into resource_categories (type, resource_id) values ('1H NMR', '8');
insert into resource_categories (type, resource_id) values ('Power Systems', '195');
insert into resource_categories (type, resource_id) values ('Information Assurance', '291');
insert into resource_categories (type, resource_id) values ('Zuken', '375');
insert into resource_categories (type, resource_id) values ('Iron Ore', '16');
insert into resource_categories (type, resource_id) values ('Lightroom', '363');
insert into resource_categories (type, resource_id) values ('Frame Relay', '240');
insert into resource_categories (type, resource_id) values ('Regulatory Affairs', '126');
insert into resource_categories (type, resource_id) values ('Small Business Online Marketing', '376');
insert into resource_categories (type, resource_id) values ('NCARB', '42');
insert into resource_categories (type, resource_id) values ('HIPAA', '186');
insert into resource_categories (type, resource_id) values ('TF-CBT', '334');
insert into resource_categories (type, resource_id) values ('Reverse Logistics', '96');
insert into resource_categories (type, resource_id) values ('DVD Studio Pro', '113');
insert into resource_categories (type, resource_id) values ('NMLS', '287');
insert into resource_categories (type, resource_id) values ('BMP design', '83');
insert into resource_categories (type, resource_id) values ('Earned Value Management', '50');
insert into resource_categories (type, resource_id) values ('Wholesale Purchasing', '336');
insert into resource_categories (type, resource_id) values ('EWM', '24');
insert into resource_categories (type, resource_id) values ('CDISC', '191');
insert into resource_categories (type, resource_id) values ('LLC', '146');
insert into resource_categories (type, resource_id) values ('Zebrafish', '465');
insert into resource_categories (type, resource_id) values ('Hazard Identification', '231');
insert into resource_categories (type, resource_id) values ('OCR', '432');
insert into resource_categories (type, resource_id) values ('DDA', '53');
insert into resource_categories (type, resource_id) values ('MPBN', '157');
insert into resource_categories (type, resource_id) values ('WTX', '363');
insert into resource_categories (type, resource_id) values ('Bloomberg', '195');
insert into resource_categories (type, resource_id) values ('Ironport', '164');
insert into resource_categories (type, resource_id) values ('RNA Biology', '495');
insert into resource_categories (type, resource_id) values ('JSLint', '476');
insert into resource_categories (type, resource_id) values ('Boating', '367');
insert into resource_categories (type, resource_id) values ('Kontakt', '42');
insert into resource_categories (type, resource_id) values ('Virtualization', '282');
insert into resource_categories (type, resource_id) values ('Tenacious Work Ethic', '325');
insert into resource_categories (type, resource_id) values ('Sony Vegas', '286');
insert into resource_categories (type, resource_id) values ('DSI', '253');
insert into resource_categories (type, resource_id) values ('Medical Imaging', '85');
insert into resource_categories (type, resource_id) values ('NICE Call Recording', '97');
insert into resource_categories (type, resource_id) values ('QML', '393');
insert into resource_categories (type, resource_id) values ('European History', '445');
insert into resource_categories (type, resource_id) values ('Exercise Physiology', '283');
insert into resource_categories (type, resource_id) values ('MMIS', '124');
insert into resource_categories (type, resource_id) values ('KBOX', '411');
insert into resource_categories (type, resource_id) values ('Lloyds', '263');
insert into resource_categories (type, resource_id) values ('SFDC', '469');
insert into resource_categories (type, resource_id) values ('Executive Protection', '92');
insert into resource_categories (type, resource_id) values ('WSGI', '382');
insert into resource_categories (type, resource_id) values ('Upholstery', '158');
insert into resource_categories (type, resource_id) values ('Electrical Controls', '200');
insert into resource_categories (type, resource_id) values ('Internal Controls', '45');
insert into resource_categories (type, resource_id) values ('Contact Centers', '140');
insert into resource_categories (type, resource_id) values ('Urban Redevelopment', '198');
insert into resource_categories (type, resource_id) values ('Managerial Finance', '342');
insert into resource_categories (type, resource_id) values ('MCSA + Messaging', '176');
insert into resource_categories (type, resource_id) values ('MPEG Streamclip', '482');
insert into resource_categories (type, resource_id) values ('SPSS', '38');
insert into resource_categories (type, resource_id) values ('Information Architecture', '285');
insert into resource_categories (type, resource_id) values ('cXML', '267');
insert into resource_categories (type, resource_id) values ('Value Engineering', '206');
insert into resource_categories (type, resource_id) values ('KDE', '81');
insert into resource_categories (type, resource_id) values ('DL1', '106');
insert into resource_categories (type, resource_id) values ('Klocwork', '191');
insert into resource_categories (type, resource_id) values ('Teacher Training', '72');
insert into resource_categories (type, resource_id) values ('PDMS', '346');
insert into resource_categories (type, resource_id) values ('Zultys', '323');
insert into resource_categories (type, resource_id) values ('Gmail', '386');
insert into resource_categories (type, resource_id) values ('Oleochemicals', '481');
insert into resource_categories (type, resource_id) values ('Kickboxing', '462');
insert into resource_categories (type, resource_id) values ('Lytec', '445');
insert into resource_categories (type, resource_id) values ('Sniffer', '200');
insert into resource_categories (type, resource_id) values ('TGA', '280');
insert into resource_categories (type, resource_id) values ('Home Care', '470');
insert into resource_categories (type, resource_id) values ('jQuery', '207');
insert into resource_categories (type, resource_id) values ('TCF', '246');
insert into resource_categories (type, resource_id) values ('Organizational Design', '40');
insert into resource_categories (type, resource_id) values ('Practice CS', '163');
insert into resource_categories (type, resource_id) values ('Urban Infill', '380');
insert into resource_categories (type, resource_id) values ('EPM', '231');
insert into resource_categories (type, resource_id) values ('UIM', '222');
insert into resource_categories (type, resource_id) values ('BGAN', '497');
insert into resource_categories (type, resource_id) values ('Ultrafast Spectroscopy', '247');
insert into resource_categories (type, resource_id) values ('Legal Advice', '444');
insert into resource_categories (type, resource_id) values ('jQuery Mobile', '53');
insert into resource_categories (type, resource_id) values ('CPT', '468');
insert into resource_categories (type, resource_id) values ('Student Affairs', '243');
insert into resource_categories (type, resource_id) values ('Uranium', '359');
insert into resource_categories (type, resource_id) values ('PCRF', '97');
insert into resource_categories (type, resource_id) values ('Node.js', '491');
insert into resource_categories (type, resource_id) values ('NCP', '39');
insert into resource_categories (type, resource_id) values ('Medical Affairs', '483');
insert into resource_categories (type, resource_id) values ('EPCM', '137');
insert into resource_categories (type, resource_id) values ('DV', '227');
insert into resource_categories (type, resource_id) values ('PVS', '314');
insert into resource_categories (type, resource_id) values ('XAMPP', '440');
insert into resource_categories (type, resource_id) values ('Sybase IQ', '468');
insert into resource_categories (type, resource_id) values ('IABP', '220');
insert into resource_categories (type, resource_id) values ('LN', '163');
insert into resource_categories (type, resource_id) values ('MLD', '270');
insert into resource_categories (type, resource_id) values ('ICAO', '323');
insert into resource_categories (type, resource_id) values ('PIX', '43');
insert into resource_categories (type, resource_id) values ('Speech Writing', '298');
insert into resource_categories (type, resource_id) values ('DS4000', '267');
insert into resource_categories (type, resource_id) values ('MBCS', '384');
insert into resource_categories (type, resource_id) values ('Working With Children', '472');
insert into resource_categories (type, resource_id) values ('SSH', '247');
insert into resource_categories (type, resource_id) values ('Komodo', '459');
insert into resource_categories (type, resource_id) values ('BOSIET', '412');
insert into resource_categories (type, resource_id) values ('Site Development', '254');
insert into resource_categories (type, resource_id) values ('Mineral Exploration', '228');
insert into resource_categories (type, resource_id) values ('Seismic Attributes', '469');
insert into resource_categories (type, resource_id) values ('Xactly', '250');
insert into resource_categories (type, resource_id) values ('Embedded C', '76');
insert into resource_categories (type, resource_id) values ('Iyengar Yoga', '171');
insert into resource_categories (type, resource_id) values ('SSO', '110');
insert into resource_categories (type, resource_id) values ('Wide Format Printing', '225');
insert into resource_categories (type, resource_id) values ('Photography', '28');
insert into resource_categories (type, resource_id) values ('Nutrition Education', '314');
insert into resource_categories (type, resource_id) values ('Press Releases', '253');
insert into resource_categories (type, resource_id) values ('Successful Business Owner', '488');
insert into resource_categories (type, resource_id) values ('Akamai', '366');
insert into resource_categories (type, resource_id) values ('Pinterest', '1');
insert into resource_categories (type, resource_id) values ('XRY', '437');
insert into resource_categories (type, resource_id) values ('eBay', '328');
insert into resource_categories (type, resource_id) values ('Data Migration', '372');
insert into resource_categories (type, resource_id) values ('Google Apps', '237');
insert into resource_categories (type, resource_id) values ('Health Insurance', '420');
insert into resource_categories (type, resource_id) values ('BSI Tax Factory', '491');
insert into resource_categories (type, resource_id) values ('Adult Education', '318');
insert into resource_categories (type, resource_id) values ('FHLMC', '303');
insert into resource_categories (type, resource_id) values ('OID', '241');
insert into resource_categories (type, resource_id) values ('Financial Accounting', '415');
insert into resource_categories (type, resource_id) values ('Business Aviation', '16');
insert into resource_categories (type, resource_id) values ('Emergency Management', '408');
insert into resource_categories (type, resource_id) values ('Whiplash', '456');
insert into resource_categories (type, resource_id) values ('Patient Advocacy', '166');
insert into resource_categories (type, resource_id) values ('HCS 2000', '79');
insert into resource_categories (type, resource_id) values ('ION Marketview', '235');
insert into resource_categories (type, resource_id) values ('Alternative Medicine', '328');
insert into resource_categories (type, resource_id) values ('Microsoft Dynamics NAV', '445');
insert into resource_categories (type, resource_id) values ('Environmental Issues', '5');
insert into resource_categories (type, resource_id) values ('WCF', '369');
insert into resource_categories (type, resource_id) values ('NICET', '192');
insert into resource_categories (type, resource_id) values ('DDI Certified', '360');
insert into resource_categories (type, resource_id) values ('Quality by Design', '66');
insert into resource_categories (type, resource_id) values ('EBITDA', '326');
insert into resource_categories (type, resource_id) values ('Backbone.js', '162');
insert into resource_categories (type, resource_id) values ('CXF', '318');
insert into resource_categories (type, resource_id) values ('Recruitment Advertising', '255');
insert into resource_categories (type, resource_id) values ('SAP OM', '323');
insert into resource_categories (type, resource_id) values ('Police', '364');
insert into resource_categories (type, resource_id) values ('LWUIT', '201');
insert into resource_categories (type, resource_id) values ('QAC', '88');
insert into resource_categories (type, resource_id) values ('Red Hat Linux', '181');
insert into resource_categories (type, resource_id) values ('Kodak', '367');
insert into resource_categories (type, resource_id) values ('Bluetooth', '463');
insert into resource_categories (type, resource_id) values ('Yarn', '305');
insert into resource_categories (type, resource_id) values ('LS9', '81');
insert into resource_categories (type, resource_id) values ('MVA', '353');
insert into resource_categories (type, resource_id) values ('ACLS', '287');
insert into resource_categories (type, resource_id) values ('Mobile Technology', '152');
insert into resource_categories (type, resource_id) values ('Patient Safety', '61');
insert into resource_categories (type, resource_id) values ('IM', '105');
insert into resource_categories (type, resource_id) values ('Oz Principle', '388');
insert into resource_categories (type, resource_id) values ('PFI', '313');
insert into resource_categories (type, resource_id) values ('Eastern Europe', '164');
insert into resource_categories (type, resource_id) values ('JDBC', '151');
insert into resource_categories (type, resource_id) values ('Lithium-ion Batteries', '244');
insert into resource_categories (type, resource_id) values ('MVT', '407');
insert into resource_categories (type, resource_id) values ('Animal Nutrition', '416');
insert into resource_categories (type, resource_id) values ('RPAS', '334');
insert into resource_categories (type, resource_id) values ('Molecular Biology', '16');
insert into resource_categories (type, resource_id) values ('JIRA', '400');
insert into resource_categories (type, resource_id) values ('BDC', '446');
insert into resource_categories (type, resource_id) values ('VMware Workstation', '198');
insert into resource_categories (type, resource_id) values ('AWS CWI', '479');
insert into resource_categories (type, resource_id) values ('Interviews', '2');
insert into resource_categories (type, resource_id) values ('RUP Methodologies', '177');
insert into resource_categories (type, resource_id) values ('Facilities Management', '90');
insert into resource_categories (type, resource_id) values ('SPSS', '11');
insert into resource_categories (type, resource_id) values ('HR Project Management', '308');
insert into resource_categories (type, resource_id) values ('Alcohol Awareness', '342');
insert into resource_categories (type, resource_id) values ('EU Law', '193');
insert into resource_categories (type, resource_id) values ('NMLS Licensed', '73');
insert into resource_categories (type, resource_id) values ('Variable Frequency Drives', '120');
insert into resource_categories (type, resource_id) values ('Wide Format Printing', '179');
insert into resource_categories (type, resource_id) values ('RNO', '431');
insert into resource_categories (type, resource_id) values ('Kompozer', '9');
insert into resource_categories (type, resource_id) values ('RSA Tokens', '436');
insert into resource_categories (type, resource_id) values ('International Economics', '435');
insert into resource_categories (type, resource_id) values ('Guided Tours', '291');
insert into resource_categories (type, resource_id) values ('Aquariums', '19');
insert into resource_categories (type, resource_id) values ('Online Gambling', '416');
insert into resource_categories (type, resource_id) values ('Early-stage Startups', '92');
insert into resource_categories (type, resource_id) values ('TBS', '75');
insert into resource_categories (type, resource_id) values ('Plant Identification', '306');
insert into resource_categories (type, resource_id) values ('Arbitration', '261');
insert into resource_categories (type, resource_id) values ('MDRs', '300');
insert into resource_categories (type, resource_id) values ('EP', '314');
insert into resource_categories (type, resource_id) values ('NHibernate', '34');
insert into resource_categories (type, resource_id) values ('Instructional Design', '402');
insert into resource_categories (type, resource_id) values ('MBE', '50');
insert into resource_categories (type, resource_id) values ('TCP/IP', '149');
insert into resource_categories (type, resource_id) values ('HSEQ', '393');
insert into resource_categories (type, resource_id) values ('Cycle Time Reduction', '204');
insert into resource_categories (type, resource_id) values ('LP', '302');
insert into resource_categories (type, resource_id) values ('HQL', '82');
insert into resource_categories (type, resource_id) values ('MHP', '339');
insert into resource_categories (type, resource_id) values ('HNW', '41');
insert into resource_categories (type, resource_id) values ('FW', '255');
insert into resource_categories (type, resource_id) values ('Jets', '271');
insert into resource_categories (type, resource_id) values ('Ultrasonic Testing', '432');
insert into resource_categories (type, resource_id) values ('Jive', '345');
insert into resource_categories (type, resource_id) values ('Timber', '312');
insert into resource_categories (type, resource_id) values ('Know-how', '186');
insert into resource_categories (type, resource_id) values ('Drawing', '283');
insert into resource_categories (type, resource_id) values ('FFT', '17');
insert into resource_categories (type, resource_id) values ('MXP', '367');
insert into resource_categories (type, resource_id) values ('DC-9', '370');
insert into resource_categories (type, resource_id) values ('Tutoring', '87');
insert into resource_categories (type, resource_id) values ('DTD', '111');
insert into resource_categories (type, resource_id) values ('EWSD', '312');
insert into resource_categories (type, resource_id) values ('Wireless', '339');
insert into resource_categories (type, resource_id) values ('Fitness', '47');
insert into resource_categories (type, resource_id) values ('IRB', '187');
insert into resource_categories (type, resource_id) values ('Trading', '37');
insert into resource_categories (type, resource_id) values ('SSAE 16', '111');
insert into resource_categories (type, resource_id) values ('Purchasing', '99');
insert into resource_categories (type, resource_id) values ('CCIE', '422');
insert into resource_categories (type, resource_id) values ('DNSSEC', '340');
insert into resource_categories (type, resource_id) values ('CQI', '366');
insert into resource_categories (type, resource_id) values ('Lubricants', '263');
insert into resource_categories (type, resource_id) values ('WLI', '410');
insert into resource_categories (type, resource_id) values ('Flyers', '102');
insert into resource_categories (type, resource_id) values ('OTDR', '271');
insert into resource_categories (type, resource_id) values ('Special Effects', '367');
insert into resource_categories (type, resource_id) values ('JSA', '73');
insert into resource_categories (type, resource_id) values ('Quality Patient Care', '117');
insert into resource_categories (type, resource_id) values ('Leases', '418');
insert into resource_categories (type, resource_id) values ('Typing', '464');
insert into resource_categories (type, resource_id) values ('Overcome Objections', '37');
insert into resource_categories (type, resource_id) values ('JUNOS', '107');
insert into resource_categories (type, resource_id) values ('Zuken', '78');
insert into resource_categories (type, resource_id) values ('RSoft', '360');
insert into resource_categories (type, resource_id) values ('Final Cut Pro', '468');
insert into resource_categories (type, resource_id) values ('Erlang', '146');
insert into resource_categories (type, resource_id) values ('MCSA', '149');
insert into resource_categories (type, resource_id) values ('DNA electrophoresis', '282');
insert into resource_categories (type, resource_id) values ('Administration', '346');
insert into resource_categories (type, resource_id) values ('BDC programming', '32');
insert into resource_categories (type, resource_id) values ('Teeth Whitening', '452');
insert into resource_categories (type, resource_id) values ('Engineering Management', '256');
insert into resource_categories (type, resource_id) values ('Fashion Buying', '319');
insert into resource_categories (type, resource_id) values ('IQ Navigator', '199');
insert into resource_categories (type, resource_id) values ('Museums', '424');
insert into resource_categories (type, resource_id) values ('Qualitative Research', '404');
insert into resource_categories (type, resource_id) values ('Food Quality', '173');
insert into resource_categories (type, resource_id) values ('PV', '328');
insert into resource_categories (type, resource_id) values ('Aquatic Therapy', '417');
insert into resource_categories (type, resource_id) values ('Lytec', '61');
insert into resource_categories (type, resource_id) values ('CDISC', '217');
insert into resource_categories (type, resource_id) values ('Database Design', '192');
insert into resource_categories (type, resource_id) values ('DLS', '95');
insert into resource_categories (type, resource_id) values ('SSL', '42');
insert into resource_categories (type, resource_id) values ('Whisky', '374');
insert into resource_categories (type, resource_id) values ('Igloo', '455');
insert into resource_categories (type, resource_id) values ('Trail Running', '474');
insert into resource_categories (type, resource_id) values ('Joomla', '480');
insert into resource_categories (type, resource_id) values ('Jitterbit', '373');
insert into resource_categories (type, resource_id) values ('Business Ethics', '266');
insert into resource_categories (type, resource_id) values ('SDS-PAGE', '69');
insert into resource_categories (type, resource_id) values ('IOS-XR', '189');
insert into resource_categories (type, resource_id) values ('Glasses', '461');
insert into resource_categories (type, resource_id) values ('MWS', '189');
insert into resource_categories (type, resource_id) values ('MTTR', '120');
insert into resource_categories (type, resource_id) values ('Voice Acting', '146');
insert into resource_categories (type, resource_id) values ('VTune', '258');
insert into resource_categories (type, resource_id) values ('MCSD', '119');
insert into resource_categories (type, resource_id) values ('Sickness Absence Management', '436');
insert into resource_categories (type, resource_id) values ('Automotive Aftermarket', '403');
insert into resource_categories (type, resource_id) values ('OS/390', '97');
insert into resource_categories (type, resource_id) values ('PPAP', '162');
insert into resource_categories (type, resource_id) values ('JVs', '286');
insert into resource_categories (type, resource_id) values ('Sellers', '430');
insert into resource_categories (type, resource_id) values ('Microsoft Word', '272');
insert into resource_categories (type, resource_id) values ('ADP Payroll', '183');
insert into resource_categories (type, resource_id) values ('User-centered Design', '242');
insert into resource_categories (type, resource_id) values ('MSS', '165');
insert into resource_categories (type, resource_id) values ('IAD', '207');
insert into resource_categories (type, resource_id) values ('FFIEC', '268');
insert into resource_categories (type, resource_id) values ('European Studies', '413');
insert into resource_categories (type, resource_id) values ('Home Equity Loans', '47');
insert into resource_categories (type, resource_id) values ('CDS', '261');
insert into resource_categories (type, resource_id) values ('GPC', '53');
insert into resource_categories (type, resource_id) values ('Type Design', '279');
insert into resource_categories (type, resource_id) values ('PCI Standards', '152');
insert into resource_categories (type, resource_id) values ('Tcpdump', '396');
insert into resource_categories (type, resource_id) values ('Epistemology', '46');
insert into resource_categories (type, resource_id) values ('Data Mining', '118');
insert into resource_categories (type, resource_id) values ('Field Work', '417');
insert into resource_categories (type, resource_id) values ('VGA', '486');
insert into resource_categories (type, resource_id) values ('Group Therapy', '226');
insert into resource_categories (type, resource_id) values ('Applicant Tracking Systems', '348');
insert into resource_categories (type, resource_id) values ('Infor XA', '327');
insert into resource_categories (type, resource_id) values ('Natural Gas', '337');
insert into resource_categories (type, resource_id) values ('Petroleum Geology', '196');
insert into resource_categories (type, resource_id) values ('RMF', '371');
insert into resource_categories (type, resource_id) values ('MS Axapta', '445');
insert into resource_categories (type, resource_id) values ('Xbox One', '60');
insert into resource_categories (type, resource_id) values ('Eggs', '384');
insert into resource_categories (type, resource_id) values ('Yield Management', '412');
insert into resource_categories (type, resource_id) values ('WordPress', '245');
insert into resource_categories (type, resource_id) values ('FCIP', '352');
insert into resource_categories (type, resource_id) values ('Wovens', '165');
insert into resource_categories (type, resource_id) values ('AWS CWI', '260');
insert into resource_categories (type, resource_id) values ('Group Dynamics', '217');
insert into resource_categories (type, resource_id) values ('Biostatistics', '207');
insert into resource_categories (type, resource_id) values ('Screenwriting', '316');
insert into resource_categories (type, resource_id) values ('MDRs', '493');
insert into resource_categories (type, resource_id) values ('Ignite-UX', '377');
insert into resource_categories (type, resource_id) values ('Branding', '43');
insert into resource_categories (type, resource_id) values ('OOH', '202');
insert into resource_categories (type, resource_id) values ('GSD', '321');
insert into resource_categories (type, resource_id) values ('MSC Patran', '1');
insert into resource_categories (type, resource_id) values ('Powers of Attorney', '329');
insert into resource_categories (type, resource_id) values ('GXT', '133');
insert into resource_categories (type, resource_id) values ('SAP HR', '398');
insert into resource_categories (type, resource_id) values ('PC Games', '273');
insert into resource_categories (type, resource_id) values ('Renewable Energy', '276');
insert into resource_categories (type, resource_id) values ('Certified DDI Facilitator', '483');
insert into resource_categories (type, resource_id) values ('Copywriting', '329');
insert into resource_categories (type, resource_id) values ('Logic Pro', '39');
insert into resource_categories (type, resource_id) values ('IT Outsourcing', '453');
insert into resource_categories (type, resource_id) values ('GSA Schedule', '10');
insert into resource_categories (type, resource_id) values ('RSLinx', '351');
insert into resource_categories (type, resource_id) values ('HSI', '352');
insert into resource_categories (type, resource_id) values ('RMF', '390');
insert into resource_categories (type, resource_id) values ('WCF', '58');
insert into resource_categories (type, resource_id) values ('OJEU', '159');
insert into resource_categories (type, resource_id) values ('AAR', '174');
insert into resource_categories (type, resource_id) values ('Bodywork', '80');
insert into resource_categories (type, resource_id) values ('HLA', '481');
insert into resource_categories (type, resource_id) values ('z/VM', '337');
insert into resource_categories (type, resource_id) values ('XP Professional', '338');
insert into resource_categories (type, resource_id) values ('PCM', '226');
insert into resource_categories (type, resource_id) values ('DCP', '386');
insert into resource_categories (type, resource_id) values ('After FX', '186');
insert into resource_categories (type, resource_id) values ('IP Cameras', '416');
insert into resource_categories (type, resource_id) values ('CPIM', '61');
insert into resource_categories (type, resource_id) values ('OTS', '391');
insert into resource_categories (type, resource_id) values ('SLES', '156');
insert into resource_categories (type, resource_id) values ('Java', '489');
insert into resource_categories (type, resource_id) values ('Lunix', '256');
insert into resource_categories (type, resource_id) values ('BGA', '431');
insert into resource_categories (type, resource_id) values ('5 Why', '59');
insert into resource_categories (type, resource_id) values ('Food', '350');
insert into resource_categories (type, resource_id) values ('Drama', '10');
insert into resource_categories (type, resource_id) values ('nMarket', '209');
insert into resource_categories (type, resource_id) values ('Radio Broadcasting', '84');
insert into resource_categories (type, resource_id) values ('Occupational Therapists', '167');
insert into resource_categories (type, resource_id) values ('OHS', '1');
insert into resource_categories (type, resource_id) values ('JavaBeans', '138');
insert into resource_categories (type, resource_id) values ('System Testing', '268');
insert into resource_categories (type, resource_id) values ('UltraTax', '92');
insert into resource_categories (type, resource_id) values ('ASP.NET', '500');
insert into resource_categories (type, resource_id) values ('QALoad', '88');
insert into resource_categories (type, resource_id) values ('IIA Standards', '193');
insert into resource_categories (type, resource_id) values ('Volunteering', '332');
insert into resource_categories (type, resource_id) values ('BMC Remedy Ticketing System', '42');
insert into resource_categories (type, resource_id) values ('LDRA', '54');
insert into resource_categories (type, resource_id) values ('Qik', '112');
insert into resource_categories (type, resource_id) values ('Yardi Voyager', '192');
insert into resource_categories (type, resource_id) values ('Octave', '380');
insert into resource_categories (type, resource_id) values ('RFQ Development', '28');
insert into resource_categories (type, resource_id) values ('XDCAM', '270');
insert into resource_categories (type, resource_id) values ('ZBrush', '153');
insert into resource_categories (type, resource_id) values ('Hyperion HFM', '500');
insert into resource_categories (type, resource_id) values ('DMU', '301');
insert into resource_categories (type, resource_id) values ('Ab Initio', '119');
insert into resource_categories (type, resource_id) values ('JMX', '72');
insert into resource_categories (type, resource_id) values ('Jewelry Design', '437');
insert into resource_categories (type, resource_id) values ('Fashion Blogging', '348');
insert into resource_categories (type, resource_id) values ('CISSP', '403');
insert into resource_categories (type, resource_id) values ('Operations Management', '197');
insert into resource_categories (type, resource_id) values ('eCTD', '253');
insert into resource_categories (type, resource_id) values ('Vascular', '146');
insert into resource_categories (type, resource_id) values ('Dtrace', '369');
insert into resource_categories (type, resource_id) values ('Long-term Care', '232');
insert into resource_categories (type, resource_id) values ('JTIDS', '49');
insert into resource_categories (type, resource_id) values ('Industrial Hygiene', '492');
insert into resource_categories (type, resource_id) values ('DMAIC', '378');
insert into resource_categories (type, resource_id) values ('TCAS', '494');
insert into resource_categories (type, resource_id) values ('Cycling', '36');
insert into resource_categories (type, resource_id) values ('MQSI', '498');
insert into resource_categories (type, resource_id) values ('SPSS', '446');
insert into resource_categories (type, resource_id) values ('Inspection', '383');
insert into resource_categories (type, resource_id) values ('SBT', '426');
insert into resource_categories (type, resource_id) values ('Laboratory', '30');
insert into resource_categories (type, resource_id) values ('Project Portfolio Management', '252');
insert into resource_categories (type, resource_id) values ('Factory', '126');
insert into resource_categories (type, resource_id) values ('NDC', '252');
insert into resource_categories (type, resource_id) values ('NTFS', '263');
insert into resource_categories (type, resource_id) values ('Oscilloscope', '486');
insert into resource_categories (type, resource_id) values ('Quality Control', '495');
insert into resource_categories (type, resource_id) values ('FTTH', '14');
insert into resource_categories (type, resource_id) values ('PNF', '383');
insert into resource_categories (type, resource_id) values ('Banking', '72');
insert into resource_categories (type, resource_id) values ('Project Estimation', '441');
insert into resource_categories (type, resource_id) values ('JBL', '482');
insert into resource_categories (type, resource_id) values ('IED', '83');
insert into resource_categories (type, resource_id) values ('Black &amp; White', '230');
insert into resource_categories (type, resource_id) values ('PK/PD', '97');
insert into resource_categories (type, resource_id) values ('Axis2', '87');
insert into resource_categories (type, resource_id) values ('Root Cause Analysis', '73');
insert into resource_categories (type, resource_id) values ('Xetra', '443');
insert into resource_categories (type, resource_id) values ('Aerospace Structures', '43');
insert into resource_categories (type, resource_id) values ('Air Quality', '463');
insert into resource_categories (type, resource_id) values ('DOS', '403');
insert into resource_categories (type, resource_id) values ('JBoss ESB', '304');
insert into resource_categories (type, resource_id) values ('Image Processing', '412');
insert into resource_categories (type, resource_id) values ('Business Objects', '88');
insert into resource_categories (type, resource_id) values ('global HCM', '341');
insert into resource_categories (type, resource_id) values ('Chromatography', '425');
insert into resource_categories (type, resource_id) values ('IETF', '442');
insert into resource_categories (type, resource_id) values ('EH&amp;S Compliance', '193');
insert into resource_categories (type, resource_id) values ('GNSS', '133');
insert into resource_categories (type, resource_id) values ('Rock Climbing', '44');
insert into resource_categories (type, resource_id) values ('Drywall', '101');
insert into resource_categories (type, resource_id) values ('Myofascial Release Therapy', '214');
insert into resource_categories (type, resource_id) values ('Wellbeing', '333');
insert into resource_categories (type, resource_id) values ('Inventory Control', '14');
insert into resource_categories (type, resource_id) values ('CMS-1500', '459');
insert into resource_categories (type, resource_id) values ('ERP', '299');
insert into resource_categories (type, resource_id) values ('After Effects', '267');
insert into resource_categories (type, resource_id) values ('Airlines', '482');
insert into resource_categories (type, resource_id) values ('Variable Data Printing', '472');
insert into resource_categories (type, resource_id) values ('Iron', '252');
insert into resource_categories (type, resource_id) values ('Visual Merchandising', '343');
insert into resource_categories (type, resource_id) values ('Semantic HTML', '97');
insert into resource_categories (type, resource_id) values ('Hotel Management', '423');
insert into resource_categories (type, resource_id) values ('FTSE 100', '170');
insert into resource_categories (type, resource_id) values ('AQL', '186');
insert into resource_categories (type, resource_id) values ('CAD', '149');
insert into resource_categories (type, resource_id) values ('SQL Server Management Studio', '31');
insert into resource_categories (type, resource_id) values ('Project Implementation', '405');
insert into resource_categories (type, resource_id) values ('PSpice', '355');
insert into resource_categories (type, resource_id) values ('Quantitative Research', '432');
insert into resource_categories (type, resource_id) values ('HP Procurve Networking', '394');
insert into resource_categories (type, resource_id) values ('PPC Bid Management', '302');
insert into resource_categories (type, resource_id) values ('Vulnerability Research', '159');
insert into resource_categories (type, resource_id) values ('1H NMR', '24');
insert into resource_categories (type, resource_id) values ('UCITS', '23');
insert into resource_categories (type, resource_id) values ('Sound FX Editing', '123');
insert into resource_categories (type, resource_id) values ('Historical Research', '85');
insert into resource_categories (type, resource_id) values ('SAP OM', '83');
insert into resource_categories (type, resource_id) values ('TFTP', '307');
insert into resource_categories (type, resource_id) values ('PnL', '238');
insert into resource_categories (type, resource_id) values ('GCS', '192');
insert into resource_categories (type, resource_id) values ('Yacc', '184');
insert into resource_categories (type, resource_id) values ('VMware Fusion', '498');
insert into resource_categories (type, resource_id) values ('MVC Architecture', '166');
insert into resource_categories (type, resource_id) values ('Electrical Troubleshooting', '453');
insert into resource_categories (type, resource_id) values ('Kofax', '221');
insert into resource_categories (type, resource_id) values ('Gx', '443');
insert into resource_categories (type, resource_id) values ('Call center start-up', '245');
insert into resource_categories (type, resource_id) values ('Water Treatment', '221');
insert into resource_categories (type, resource_id) values ('XCAP', '275');
insert into resource_categories (type, resource_id) values ('Web Analytics', '59');
insert into resource_categories (type, resource_id) values ('Occupational Therapists', '17');
insert into resource_categories (type, resource_id) values ('OMB A-123', '500');
insert into resource_categories (type, resource_id) values ('IO', '131');
insert into resource_categories (type, resource_id) values ('IM', '46');
insert into resource_categories (type, resource_id) values ('Criminal Justice', '381');
insert into resource_categories (type, resource_id) values ('LVDS', '355');
insert into resource_categories (type, resource_id) values ('Canon XH-A1', '424');
insert into resource_categories (type, resource_id) values ('Overseas Experience', '381');
insert into resource_categories (type, resource_id) values ('EOL', '122');
insert into resource_categories (type, resource_id) values ('Linux', '88');
insert into resource_categories (type, resource_id) values ('Data Mining', '231');
insert into resource_categories (type, resource_id) values ('WFO', '252');
insert into resource_categories (type, resource_id) values ('Outpatient Orthopedics', '474');
insert into resource_categories (type, resource_id) values ('OC RDC', '254');
insert into resource_categories (type, resource_id) values ('IT Project &amp; Program Management', '449');
insert into resource_categories (type, resource_id) values ('CVE', '462');
insert into resource_categories (type, resource_id) values ('WFL', '51');
insert into resource_categories (type, resource_id) values ('SGW', '463');
insert into resource_categories (type, resource_id) values ('QlikView', '349');
insert into resource_categories (type, resource_id) values ('LabVIEW', '192');
insert into resource_categories (type, resource_id) values ('Zillow', '47');
insert into resource_categories (type, resource_id) values ('CTQ', '140');
insert into resource_categories (type, resource_id) values ('DLP', '342');
insert into resource_categories (type, resource_id) values ('Sports Play-by-play', '330');
insert into resource_categories (type, resource_id) values ('Shipbuilding', '223');
insert into resource_categories (type, resource_id) values ('OTN', '145');
insert into resource_categories (type, resource_id) values ('LSAMS', '112');
insert into resource_categories (type, resource_id) values ('AJAX Toolkit', '47');
insert into resource_categories (type, resource_id) values ('wxWidgets', '160');
insert into resource_categories (type, resource_id) values ('LN', '420');
insert into resource_categories (type, resource_id) values ('Hybrid Cloud', '320');
insert into resource_categories (type, resource_id) values ('MBAL', '414');
insert into resource_categories (type, resource_id) values ('SS7', '240');
insert into resource_categories (type, resource_id) values ('UNIX Utilities', '95');
insert into resource_categories (type, resource_id) values ('Social Justice', '317');
insert into resource_categories (type, resource_id) values ('FW', '222');
insert into resource_categories (type, resource_id) values ('XACML', '129');
insert into resource_categories (type, resource_id) values ('MXF', '294');
insert into resource_categories (type, resource_id) values ('Pediatrics', '489');
insert into resource_categories (type, resource_id) values ('RCV', '484');
insert into resource_categories (type, resource_id) values ('Eagle PCB', '336');
insert into resource_categories (type, resource_id) values ('NCover', '105');
insert into resource_categories (type, resource_id) values ('NCMR', '190');
insert into resource_categories (type, resource_id) values ('FTSE 100', '332');
insert into resource_categories (type, resource_id) values ('Zope', '337');
insert into resource_categories (type, resource_id) values ('OC RDC', '4');
insert into resource_categories (type, resource_id) values ('DDR3', '459');
insert into resource_categories (type, resource_id) values ('OSHA Certified', '351');
insert into resource_categories (type, resource_id) values ('KDB', '343');
insert into resource_categories (type, resource_id) values ('LPS Desktop', '444');
insert into resource_categories (type, resource_id) values ('XML Databases', '147');
insert into resource_categories (type, resource_id) values ('RF Engineering', '490');
insert into resource_categories (type, resource_id) values ('IVIG', '419');
insert into resource_categories (type, resource_id) values ('RNA Isolation', '381');
insert into resource_categories (type, resource_id) values ('Occupational Therapists', '61');
insert into resource_categories (type, resource_id) values ('Broadcast Television', '128');
insert into resource_categories (type, resource_id) values ('Jewelry', '224');
insert into resource_categories (type, resource_id) values ('Industrial Hygiene', '464');
insert into resource_categories (type, resource_id) values ('MDB', '140');
insert into resource_categories (type, resource_id) values ('SQL Tuning', '230');
insert into resource_categories (type, resource_id) values ('PET-CT', '335');
insert into resource_categories (type, resource_id) values ('Failure Analysis', '240');
insert into resource_categories (type, resource_id) values ('Cardiology', '180');
insert into resource_categories (type, resource_id) values ('Healthcare Information Technology', '223');
insert into resource_categories (type, resource_id) values ('MP2', '209');
insert into resource_categories (type, resource_id) values ('CTQ', '278');
insert into resource_categories (type, resource_id) values ('ERP', '467');
insert into resource_categories (type, resource_id) values ('XML Databases', '453');
insert into resource_categories (type, resource_id) values ('Joint Military Operations', '285');
insert into resource_categories (type, resource_id) values ('IEC 60601', '236');
insert into resource_categories (type, resource_id) values ('HQL', '');
insert into resource_categories (type, resource_id) values ('Personal Training', '263');
insert into resource_categories (type, resource_id) values ('Identity Management', '314');
insert into resource_categories (type, resource_id) values ('UCP 600', '125');
insert into resource_categories (type, resource_id) values ('Mental Health', '180');
insert into resource_categories (type, resource_id) values ('IHT', '229');
insert into resource_categories (type, resource_id) values ('Lifestyle', '390');
insert into resource_categories (type, resource_id) values ('BC/DR', '491');
insert into resource_categories (type, resource_id) values ('VC#', '207');
insert into resource_categories (type, resource_id) values ('Fixed Assets', '451');
insert into resource_categories (type, resource_id) values ('Animal Husbandry', '295');
insert into resource_categories (type, resource_id) values ('Offshoring', '293');
insert into resource_categories (type, resource_id) values ('DOT Regulations', '327');
insert into resource_categories (type, resource_id) values ('SQR', '457');
insert into resource_categories (type, resource_id) values ('Drilling Engineering', '296');
insert into resource_categories (type, resource_id) values ('Old English', '193');
insert into resource_categories (type, resource_id) values ('Process Scheduler', '445');
insert into resource_categories (type, resource_id) values ('RLM', '377');
insert into resource_categories (type, resource_id) values ('Three.js', '164');
insert into resource_categories (type, resource_id) values ('Slate', '220');
insert into resource_categories (type, resource_id) values ('PFMEA', '283');
insert into resource_categories (type, resource_id) values ('IT Infrastructure Management', '363');
insert into resource_categories (type, resource_id) values ('Consulting', '118');
insert into resource_categories (type, resource_id) values ('MyBatis', '230');
insert into resource_categories (type, resource_id) values ('HP Openview', '438');
insert into resource_categories (type, resource_id) values ('Classroom Management', '362');
insert into resource_categories (type, resource_id) values ('Data Center', '483');
insert into resource_categories (type, resource_id) values ('Hypnosis', '367');
insert into resource_categories (type, resource_id) values ('MMORPG', '10');
insert into resource_categories (type, resource_id) values ('Long Distance Running', '376');
insert into resource_categories (type, resource_id) values ('Enterprise Software', '169');
insert into resource_categories (type, resource_id) values ('Yeast', '352');
insert into resource_categories (type, resource_id) values ('Ulcerative Colitis', '88');
insert into resource_categories (type, resource_id) values ('PQQ', '448');
insert into resource_categories (type, resource_id) values ('Rhino 3D', '456');
insert into resource_categories (type, resource_id) values ('Microsoft Word', '426');
insert into resource_categories (type, resource_id) values ('Poka Yoke', '308');
insert into resource_categories (type, resource_id) values ('Copy Typing', '446');
insert into resource_categories (type, resource_id) values ('PMI', '187');
insert into resource_categories (type, resource_id) values ('SSL', '376');
insert into resource_categories (type, resource_id) values ('Zero Waste', '108');
insert into resource_categories (type, resource_id) values ('SFX Editing', '409');
insert into resource_categories (type, resource_id) values ('IC', '125');
insert into resource_categories (type, resource_id) values ('Online Help', '498');
insert into resource_categories (type, resource_id) values ('Organizational Effectiveness', '314');
insert into resource_categories (type, resource_id) values ('Galleries', '256');
insert into resource_categories (type, resource_id) values ('Human Capital Management', '89');
insert into resource_categories (type, resource_id) values ('NICET', '378');
insert into resource_categories (type, resource_id) values ('Fluid Dynamics', '118');
insert into resource_categories (type, resource_id) values ('Xing', '318');
insert into resource_categories (type, resource_id) values ('Graphics', '396');
insert into resource_categories (type, resource_id) values ('Apartments', '500');
insert into resource_categories (type, resource_id) values ('ZPL', '30');
insert into resource_categories (type, resource_id) values ('Kundalini Yoga', '371');
insert into resource_categories (type, resource_id) values ('Electricity', '474');
insert into resource_categories (type, resource_id) values ('BDD', '443');
insert into resource_categories (type, resource_id) values ('XFS', '359');
insert into resource_categories (type, resource_id) values ('MFG-Pro', '242');
insert into resource_categories (type, resource_id) values ('Pediatrics', '467');
insert into resource_categories (type, resource_id) values ('Tax Advisory', '284');
insert into resource_categories (type, resource_id) values ('Xalan', '386');
insert into resource_categories (type, resource_id) values ('Target Costing', '115');
insert into resource_categories (type, resource_id) values ('UWB', '387');
insert into resource_categories (type, resource_id) values ('VMware Workstation', '43');
insert into resource_categories (type, resource_id) values ('Graphic Illustrations', '200');
insert into resource_categories (type, resource_id) values ('NMS', '202');
insert into resource_categories (type, resource_id) values ('UED', '237');
insert into resource_categories (type, resource_id) values ('UMTS', '14');
insert into resource_categories (type, resource_id) values ('Program Development', '218');
insert into resource_categories (type, resource_id) values ('AJAX', '185');
insert into resource_categories (type, resource_id) values ('Current Affairs', '366');
insert into resource_categories (type, resource_id) values ('ClearCase', '452');
insert into resource_categories (type, resource_id) values ('Pyrosequencing', '396');
insert into resource_categories (type, resource_id) values ('Yamaha PM5D', '470');
insert into resource_categories (type, resource_id) values ('IES VE', '289');
insert into resource_categories (type, resource_id) values ('Certified DDI Facilitator', '118');
insert into resource_categories (type, resource_id) values ('Owner Representation', '409');
insert into resource_categories (type, resource_id) values ('Aesthetics', '408');
insert into resource_categories (type, resource_id) values ('Bloomberg', '441');
insert into resource_categories (type, resource_id) values ('DBAccess', '435');
insert into resource_categories (type, resource_id) values ('XATA', '119');
insert into resource_categories (type, resource_id) values ('Piano', '320');
insert into resource_categories (type, resource_id) values ('DWR', '127');
insert into resource_categories (type, resource_id) values ('Title Searches', '309');
insert into resource_categories (type, resource_id) values ('EoMPLS', '436');
insert into resource_categories (type, resource_id) values ('DGFT', '466');
insert into resource_categories (type, resource_id) values ('Pthreads', '434');
insert into resource_categories (type, resource_id) values ('Prenuptial Agreements', '341');
insert into resource_categories (type, resource_id) values ('Academic Tutoring', '306');
insert into resource_categories (type, resource_id) values ('RFP Generation', '249');
insert into resource_categories (type, resource_id) values ('OJEU', '378');
insert into resource_categories (type, resource_id) values ('Unreal Editor', '484');
insert into resource_categories (type, resource_id) values ('MVC Architecture', '415');
insert into resource_categories (type, resource_id) values ('EHR', '149');
insert into resource_categories (type, resource_id) values ('UCINET', '227');
insert into resource_categories (type, resource_id) values ('GFAAS', '149');
insert into resource_categories (type, resource_id) values ('Lesson Planning', '457');
insert into resource_categories (type, resource_id) values ('PCR', '500');
insert into resource_categories (type, resource_id) values ('ATM Networks', '273');
insert into resource_categories (type, resource_id) values ('Wiring', '69');
insert into resource_categories (type, resource_id) values ('Strategic Sourcing', '419');
insert into resource_categories (type, resource_id) values ('Knowledge Management', '351');
insert into resource_categories (type, resource_id) values ('TMJ Treatment', '165');
insert into resource_categories (type, resource_id) values ('FSA', '350');
insert into resource_categories (type, resource_id) values ('CNC Operation', '366');
insert into resource_categories (type, resource_id) values ('Mycology', '57');
insert into resource_categories (type, resource_id) values ('Jury Trials', '487');
insert into resource_categories (type, resource_id) values ('Go', '266');
insert into resource_categories (type, resource_id) values ('Outlook', '213');
insert into resource_categories (type, resource_id) values ('Trimble GPS', '110');
insert into resource_categories (type, resource_id) values ('Fine Dining', '154');
insert into resource_categories (type, resource_id) values ('Legal Research', '444');
insert into resource_categories (type, resource_id) values ('XSLT', '373');
insert into resource_categories (type, resource_id) values ('GMC', '60');
insert into resource_categories (type, resource_id) values ('RPAS', '60');
insert into resource_categories (type, resource_id) values ('Xpediter', '102');
insert into resource_categories (type, resource_id) values ('JES2', '59');
insert into resource_categories (type, resource_id) values ('iOS Design', '96');
insert into resource_categories (type, resource_id) values ('Consulting', '68');
insert into resource_categories (type, resource_id) values ('DGGE', '99');
insert into resource_categories (type, resource_id) values ('Loss Prevention', '323');
insert into resource_categories (type, resource_id) values ('OEIC', '424');
insert into resource_categories (type, resource_id) values ('InfoComm CTS', '308');
insert into resource_categories (type, resource_id) values ('eWFM', '40');
insert into resource_categories (type, resource_id) values ('AOI', '401');
insert into resource_categories (type, resource_id) values ('SAP HR', '230');
insert into resource_categories (type, resource_id) values ('EKG', '276');
insert into resource_categories (type, resource_id) values ('FPGA', '192');
insert into resource_categories (type, resource_id) values ('IRS', '300');
insert into resource_categories (type, resource_id) values ('Documentaries', '117');
insert into resource_categories (type, resource_id) values ('TSP', '428');
insert into resource_categories (type, resource_id) values ('NYMEX', '334');
insert into resource_categories (type, resource_id) values ('HSI', '317');
insert into resource_categories (type, resource_id) values ('GIS Application', '433');
insert into resource_categories (type, resource_id) values ('PTLLS', '28');
insert into resource_categories (type, resource_id) values ('Interactive Whiteboard', '92');
insert into resource_categories (type, resource_id) values ('Global Sourcing', '221');
insert into resource_categories (type, resource_id) values ('OGC Gateway Reviews', '185');
insert into resource_categories (type, resource_id) values ('Journals', '393');
insert into resource_categories (type, resource_id) values ('Franchising', '112');
insert into resource_categories (type, resource_id) values ('ESRI', '132');
insert into resource_categories (type, resource_id) values ('TQM', '157');
insert into resource_categories (type, resource_id) values ('Production Efficiency', '33');
insert into resource_categories (type, resource_id) values ('Hyperion Planning', '266');
insert into resource_categories (type, resource_id) values ('UVLayout', '429');
insert into resource_categories (type, resource_id) values ('BMD', '87');
insert into resource_categories (type, resource_id) values ('Electricity', '209');
insert into resource_categories (type, resource_id) values ('VXML', '471');
insert into resource_categories (type, resource_id) values ('Process Automation', '214');
insert into resource_categories (type, resource_id) values ('Staff Development', '152');
insert into resource_categories (type, resource_id) values ('SAP BI', '161');
insert into resource_categories (type, resource_id) values ('eGate', '229');
insert into resource_categories (type, resource_id) values ('MyBatis', '52');
insert into resource_categories (type, resource_id) values ('Ambulance', '57');
insert into resource_categories (type, resource_id) values ('RCV', '51');
insert into resource_categories (type, resource_id) values ('Active TS/SCI Clearance', '306');
insert into resource_categories (type, resource_id) values ('CD Mastering', '239');
insert into resource_categories (type, resource_id) values ('Blood Pressure', '339');
insert into resource_categories (type, resource_id) values ('Roofers', '405');
insert into resource_categories (type, resource_id) values ('DSO', '220');
insert into resource_categories (type, resource_id) values ('QA Engineering', '58');
insert into resource_categories (type, resource_id) values ('IBM pSeries', '260');
insert into resource_categories (type, resource_id) values ('Systems Analysis', '124');
insert into resource_categories (type, resource_id) values ('BS25999', '40');
insert into resource_categories (type, resource_id) values ('Klocwork', '110');
insert into resource_categories (type, resource_id) values ('Wastewater Treatment', '473');
insert into resource_categories (type, resource_id) values ('MV', '461');
insert into resource_categories (type, resource_id) values ('MCSA', '89');
insert into resource_categories (type, resource_id) values ('Film Production', '371');
insert into resource_categories (type, resource_id) values ('Event Photography', '345');
