-- Get all boards
-- Get all boards (order by highest/lowest rated)
-- Get all boards (order by most commented)
-- Get all boards (order by most eclectic/esoteric (i.e. 100% Maths or contains many categories))
-- Get all in order of highest number of resources
-- Get board by name ()
-- Get board by category ()
-- Get board by owner (username)
-- Get board by owner (name)
