DROP TABLE IF EXISTS resource_ratings CASCADE;

CREATE TABLE resource_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  rater_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  resource_id INTEGER NOT NULL REFERENCES resources(id)  ON DELETE CASCADE,
  rating INTEGER NOT NULL
);

