DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE comments (
  id SERIAL PRIMARY KEY NOT NULL,
  author_id INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
  resource_id INTEGER NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  date_posted DATETIME NOT NULL
);
